### PR TITLE
[WIP] #1035: dc.feat to accept lists/arrays of smiles

### PR DESCRIPTION
**Pull request by vsomnath**
Addressing #1035 , this PR adds in:

1. Use of smiles argument to the `Featurizer.featurize` and `Featurizer.__call__` methods
2. Updated tests for the same in the corresponding test docs.

Tasks remaining/questions:
1. Dealing with classes where featurize method overrides the one from the base class (e.g Binding Pocket Featurizer)
2. Tests for `AtomicCoordinates` featurizer, which uses _featurize() in tests, instead of `featurize/__call__`

### CODE REVIEW

**Comment by rbharath** [comment]
@VIGS25 This is a really nice start! I have a couple design comments. When we first created `Featurizer` we handled only molecular data. Nowadays, we regularly handle 3D structure data, microscopy data and more. I think it might make sense to rename the current `Featurizer` class to `MoleculeFeaturizer` and make an abstract superclass `Featurizer` that both `MoleculeFeaturizer` and `ComplexFeaturizer` should inherit from.

@peastman @lilleswing What are your comments?

**Comment by VIGS25** [comment]
Any thoughts on changing the class definitions and inheritances?

**Comment by rbharath** [comment]
@VIGS25 I think the modifications I proposed above should probably work

**Comment by VIGS25** [comment]
@rbharath: Yes!
I forgot to add @peastman & @lilleswing, if they had any additional suggestions as well, and then I could work on it all together

**Comment by rbharath** [comment]
I've rolled this feature upstream into #1792. I'll try to slice out an updated PR with feature in the next week or two

**Comment by vsomnath** [comment]
I'll close this for now then. It can always be reopened if needed.

**Comment by rbharath** [comment]
As a quick note, I've rolled part of this PR into #1792, so I should be able to get the featurizer support for lists/arrays out in a separate PR in a few weeks. If it's alright, I'll tag you for review on it soon :)

**Comment by vsomnath** [comment]
Sounds good! Apologies for being quite inactive over the last week

**Pull request closed without merging**
