### PR TITLE
New parameter name

### PR DESCRIPTION
**Pull request by kyscg**

### CODE REVIEW

**Comment by kyscg** [comment]
I felt this was more descriptive, inform me if it was unnecessary. Review @rbharath

**Comment by kyscg** [comment]
Any updates?

**Comment by rbharath** [comment]
I think this change looks innocuous, but the tests seem to be failing here. I've restarted the build. We should be OK to merge if everything is green.

**Comment by rbharath** [comment]
Taking a look again, the issue in this PR seems to have been fixed in the latest branch (in #1792). Going to close this PR

**Pull request closed without merging**
