### PR TITLE
Updated conda recipe for 2.3

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by rbharath** [comment]
Looks like some strange failures on travis with version issues here.

**Comment by peastman** [comment]
Apparently, this is caused by pbr (https://docs.openstack.org/pbr/3.1.0/index.html), which I'd never heard of before.  You created a tag with the number 2.3.0.  It sees that tag, and that the current revision is more recent than that, so it declares that the version number *must* be 2.3.1, and throws an error if we list any version number other than that.

How do you want to handle this?

**Comment by rbharath** [comment]
I think we can do a version bump to 2.3.1 in setup.py to fix this. I don't believe any other code has gone in since the 2.3.0 cut so I don't think we need to update the release formally

**Comment by peastman** [comment]
Ok, tests are passing.

**Pull request merged**
