### PR TITLE
Update model cheatsheet

### LINKED ISSUE #2861: Reorganising models section of DeepChem docs
Currently, models section of DeepChem docs is organized as keras model, torch model, sklearn model etc. It will be more useful if it is organized as molecular models, materials models etc. A good first step will be improving the model cheatsheet and categorizing DeepChem models into different groups.

CC @rbharath @peastman

### PR DESCRIPTION
**Pull request by j-frie**
# Pull Request Template

## Description

Fix #2861

As discussed in the issue, I have split the existing table in the model cheatsheet into 3 separate tables for general models, molecules, and materials.
The new tables contain a column with a link to the reference paper, and a column with the backend used in the implementation.
Input type was removed from the tables, transformations and fit_method are mentioned in a "comment" column.

I have also added MATModel to the documentation, so that the already existing docstring is displayed in the docs.

I hope this new overview is going to be helpful for deepchem users :-)

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ x] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by arunppsg** [comment]
Hey, thanks for the PR. The details are great and it renders nice. I am just wondering, will it be possible to create a csv file containing the table with the corresponding column and just reference it in the `model_cheatsheet.rst`, like ([ref](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html#csv-files))
```
.. csv-table:: Table Title
   :file: CSV file path and name
   :widths: 30, 70
   :header-rows: 1
```

We might have to create 3 csv files - `general_purpose_models.csv`, `molecular_models.csv`, `material_models.csv`. It will be easier to add new models in a csv file without the need to tinker with the layout.

**Comment by j-frie** [comment]
Hey, that's a good idea! I had used csv files to generate the tables anyway, so I have now added these instead.
Best regards, Jana

**Comment by rbharath** [comment]
A bit late to this discussion but I like splitting up the table. I would suggest that we break the molecule models into molecular molecules and molecular complex models (AtomicConvModel is conceptually a different type of model than a GraphConvModel). In future we will add additional types of models (for bioinformatics, fluids etc)

**Comment by j-frie** [comment]
I agree that the list of molecular models is still a bit too diverse.
From what I have understood so far (please correct me if I am wrong), AtomicConvModel, BasicMolGAN and ScScore are quite different from most of the other molecular models regarding their application...

Maybe this topic should be revisited, when some bioinformatics models are added to see what kind of separation of tables makes sense?

**Pull request merged**
