### PR TITLE
Overhaul tutorial sequence

### PR DESCRIPTION
**Pull request by peastman**
This is the beginning of the reorganized tutorial sequence described in #2112.  So far I've written the first two tutorials.

Tutorial 3 is supposed to be the introduction to MoleculeNet.  It would be better if @rbharath or @miaecle could write that one, since you're more familiar with the datasets than I am.  I'll go on to tutorial 4.

### CODE REVIEW

**Comment by rbharath** [comment]
@peastman These rewritten tutorials looks awesome! This is a giant improvement over our earlier tutorials :). I'm looking forward to seeing the remaining tutorials as you get to them.

I'm glad to take a pass at a tutorial 3 for MoleculeNet in a subsequent pass

**Comment by peastman** [comment]
Tutorials 1, 2, 4, 5, and 6 of the new sequence are now done.  If these look ok, let's merge this.  That will be easier than building up too many things in one PR.

**Comment by nd-02110114** [comment]
These tutorials are really good!
But, I have one suggestion. I think it is better to train all models using early stopping. Currently, all model was trained by fixed epochs and valid datasets are not used in many tutorials. I think it is not usual.

**Comment by peastman** [comment]
I'll get to that in a later tutorial.  I'm trying to take things one step at a time not present too many new things in any one tutorial.

**Comment by rbharath** [comment]
The new series looks great! Going to go ahead and merge this in :)

**Pull request merged**
