### PR TITLE
Fix import failure

### PR DESCRIPTION
**Pull request by nd-02110114**
The HEAD of master branch failed importing and also the readthedocs build has been broken. 

readthedocs build : https://readthedocs.org/projects/deepchem/builds/

Error message

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/deepchem/checkouts/latest/deepchem/feat/molecule_featurizers/circular_fingerprint.py", line 59, in __init__
    from rdkit import Chem  # noqa
ModuleNotFoundError: No module named 'rdkit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/deepchem/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/deepchem/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/deepchem/checkouts/latest/docs/conf.py", line 80, in <module>
    import deepchem
  File "/home/docs/checkouts/readthedocs.org/user_builds/deepchem/checkouts/latest/deepchem/__init__.py", line 18, in <module>
    import deepchem.molnet
  File "/home/docs/checkouts/readthedocs.org/user_builds/deepchem/checkouts/latest/deepchem/molnet/__init__.py", line 8, in <module>
    from deepchem.molnet.load_function.delaney_datasets import load_delaney
  File "/home/docs/checkouts/readthedocs.org/user_builds/deepchem/checkouts/latest/deepchem/molnet/load_function/delaney_datasets.py", line 7, in <module>
    from deepchem.molnet.load_function.molnet_loader import TransformerGenerator, _MolnetLoader
  File "/home/docs/checkouts/readthedocs.org/user_builds/deepchem/checkouts/latest/deepchem/molnet/load_function/molnet_loader.py", line 50, in <module>
    'ecfp': dc.feat.CircularFingerprint(size=1024),
  File "/home/docs/checkouts/readthedocs.org/user_builds/deepchem/checkouts/latest/deepchem/feat/molecule_featurizers/circular_fingerprint.py", line 62, in __init__
    raise ValueError("This class requires RDKit to be installed.")
ValueError: This class requires RDKit to be installed.
```

This reason is to instantiate the featurizer which depends on RDKit in `deepchem/molnet/load_function/molnet_loader.py`.  The current DeepChem require RDKit  as a hard requirement.

https://github.com/deepchem/deepchem/blob/7e745b93840d1f646a74c48af5c9320d233a1932/deepchem/molnet/load_function/molnet_loader.py#L49-L55

So, I fixed by moving the these instantiation to class constructor.

### CODE REVIEW

**Comment by peastman** [comment]
Those fields need to stay at the top level.  They're part of the public API.  Instead you can do this:

```python
try:
  featurizers['ecfp'] = dc.feat.CircularFingerprint(size=1024)
except ModuleNotFoundError:
  pass
```

**Comment by nd-02110114** [comment]
Thank you for comments! 
Before fixing, I wonder why `featurizers`, `splitters` and `transformers` need to be public API?  I couldn't understand the usecase of these dictionaries.

**Comment by peastman** [comment]
They define what string shortcuts are supported.  In the old version of the API, the list of shortcuts was different for each loader, undocumented, and impossible to query programmatically.  Putting them in top level dictionaries fixes all three of those.

https://github.com/deepchem/deepchem/blob/7e745b93840d1f646a74c48af5c9320d233a1932/deepchem/molnet/load_function/delaney_datasets.py#L56-L58

**Comment by nd-02110114** [comment]
Thank you for your comments! I could understand why they need to be public. 
So, I fixed by following your comments.

**Comment by peastman** [comment]
Looks good!  I suggest two other minor changes.  Put each featurizer into its own try/except block.  In the future we may have featurizers with different dependencies, so just because one fails that doesn't mean all of them will fail.  And change it to `except ModuleNotFoundError`.  If any other exception gets thrown, it may indicate a problem we should know about.

**Comment by nd-02110114** [comment]
> Put each featurizer into its own try/except block. In the future we may have featurizers with different dependencies, so just because one fails that doesn't mean all of them will fail.

OK! Currently, all of them depends on only RDKit.
So, I remain the code, but I will add some comments. 
I have already realized the same problem about exporting PyTorch models. 
https://github.com/deepchem/deepchem/blob/63af0c9bb73ba19552c0f9455d089749990f8a82/deepchem/models/__init__.py#L32-L37

> And change it to except ModuleNotFoundError. If any other exception gets thrown, it may indicate a problem we should know about. 

I seem `except ModuleNotFoundError` doesn't  work well. This is because the featurizer catch `ModuleNotFoundError` and then rethrow `ValueError`. (By the way, I think `ValueError` should be changed  to `ImportError`. )

https://github.com/deepchem/deepchem/blob/63af0c9bb73ba19552c0f9455d089749990f8a82/deepchem/feat/molecule_featurizers/circular_fingerprint.py#L58-L62

**Comment by nd-02110114** [comment]
This PR is ready to merge.

**Comment by peastman** [comment]
It's still better to put each one in a separate try/except block.  The reason is that when people add new code, they tend to follow the pattern of whatever is already there.  If all of them are in one block, people will tend to add new featurizers in the same block, even if they depend on a different library.  It's also possible the implementations of the existing featurizers could change in the future and one of them could add a dependence on another library.  Putting each one in a separate block is more robust long term.

**Comment by nd-02110114** [comment]
> It's still better to put each one in a separate try/except block. The reason is that when people add new code, they tend to follow the pattern of whatever is already there. If all of them are in one block, people will tend to add new featurizers in the same block, even if they depend on a different library. It's also possible the implementations of the existing featurizers could change in the future and one of them could add a dependence on another library. Putting each one in a separate block is more robust long term.

Totally agree. I fixed.

**Comment by peastman** [comment]
Looks good!

**Comment by rbharath** [comment]
There are test failures for `test_gcn_regression` on a couple of the builds, but that's not related to this PR. I'm going to go ahead and merge this in to hopefully fix the docs build

**Pull request merged**
