### PR TITLE
Fixed tutorial names, links and numbering in examples/tutorials

### PR DESCRIPTION
**Pull request by atreyamaj**
## Description
Most of the links in `examples/tutorials` were broken. I have fixed the numbering as well as the links as per the notebooks available and their order in the repository.
Referencing #2494 
## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [x] Documentations (modification for documents)

@rbharath  @alat-rights

### CODE REVIEW

**Comment by peastman** [comment]
See https://github.com/deepchem/deepchem/issues/2112#issuecomment-705695780.  We're in the middle of overhauling the tutorial sequence.  Some of the numbering is currently inconsistent, but that's just because we haven't finished all of them.

**Comment by atreyamaj** [comment]
> See [#2112 (comment)](https://github.com/deepchem/deepchem/issues/2112#issuecomment-705695780). We're in the middle of overhauling the tutorial sequence. Some of the numbering is currently inconsistent, but that's just because we haven't finished all of them.

Thank you for the heads up! I must have missed that.

Closing the PR.

**Comment by alat-rights** [comment]
Hey @atreyamaj , in the future, if you ever make somewhat big pull requests, you might want to open a issue discussing your fix before opening the pull request so that you can prevent scenarios like this? :)

**Comment by atreyamaj** [comment]
> Hey @atreyamaj , in the future, if you ever make somewhat big pull requests, you might want to open a issue discussing your fix before opening the pull request so that you can prevent scenarios like this? :)

Thank you @alat-rights , I will keep this in mind for future PRs.

**Pull request closed without merging**
