### PR TITLE
WIP:Fix #1403

### LINKED ISSUE #1403: Error in deepchem/examples/low_data/sider_graph_conv_one_fold.py
**Description:**
Could you please update the code for  deepchem/examples/low_data/sider_graph_conv_one_fold.py
?
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-40006f1f4570> in <module>()
      1 # Train support model on train
----> 2 support_model = dc.nn.SequentialSupportGraph(n_feat)
      3 
      4 # Add layers
      5 support_model.add(dc.nn.GraphConv(64, n_feat, activation='relu'))

AttributeError: module 'deepchem' has no attribute 'nn'
```

### PR DESCRIPTION
**Pull request by vsag96**
Creating PR to fix #1403 
 - [x] Load dataset

- [x] Change the model.

Disclaimer the code is not working, I just want a couple of answers before I make final changes to the patch. Is the way I load the dataset correct? and Is the model defined same as the model in the previous revision(From my unserstanding it is same with addition of a BN layers.) What I did not understand was why were the supports generated from the test dataset? How many classes are there in the dataset so I can pass it to GraphConvmodel? I agree this might not be my first ideal contribution, I have just seen the issue lying around and decided to take a stab at it.

### CODE REVIEW

**Comment by rbharath** [comment]
The way you're loading your dataset looks correct. The precise definition of the model has probably changed a bit, but is qualitatively right (`GraphConvModel` has had a number of speed improvements made to it).

The point of this file was to compare a low data architecture against one that uses simple graph convolutions (without any metalearning going on). So the supports were generated so that the comparison could be performed in an apples-to-apples fashion.

Good luck on the rest of the changes!

**Comment by vsag96** [comment]
Hi,

The code now works. If you are okay with the changes to the code I'll squash these  commits and rebase them for you to merge. On a side-note why are tests failing?

**Comment by vsag96** [comment]
Re-open request

**Comment by vsag96** [comment]
Oh just seen that the tests are failing, did I do something wrong?

**Comment by rbharath** [comment]
There's a couple of flaky errors, but it looks like the major issue is `yapf`. Can you run `yapf` on your files and update the PR? That should fix the formatting issues.

**Comment by vsag96** [comment]
I have done the formatting and this time the build has terminated halfway. I have zero idea of whats going on.

**Comment by vsag96** [comment]
@rbharath  Are you okay with the changes? It has passed all tests and I'll rebase if you want to merge.

**Comment by lilleswing** [comment]
@vsag96 thanks for the contribution!

**Comment by vsag96** [comment]
Whoah! my pleasure.

**Comment by rbharath** [comment]
@vsag96 Thanks for the changes!

**Pull request merged**
