### PR TITLE
[WIP] AtomicConvFeaturizer test fixes

### PR DESCRIPTION
**Pull request by ncfrey**
## Description

Partial fix for #2373

This PR fixes the errors in `test_atomic_conv_feat.py`. The errors were caused by the number of atoms in the protein and complex changing during featurization because of the `_strip_hydrogens` step. The coordinates list and Z-matrix features are padded to match the number of atoms specified in the input, while the neighbor list is not, which was causing the errors. 

I've uncommented the failing tests, fixed them, and added a few more explicit tests to make sure that the featurizer is generating non-zero outputs.

## Type of change

Please check the option that is related to your PR.

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by rbharath — COMMENTED** [review]
This looks great so far! Good catch on the number of atoms changing being the root of the issue with the failure

**Comment by ncfrey** [comment]
Getting the same `torch` install errors here that have popped up in recent PRs. Looks like it's related to the new release of [pytorch spline conv](https://github.com/rusty1s/pytorch_spline_conv/releases/tag/1.2.1)

**Comment by ncfrey** [comment]
`models.atomic_conv.py` will show up as a changed file, but that is only reformatting that was required because the file was altered in previous commits. I will address fixes for the actual model and model tests in a future PR.

**Comment by ncfrey** [comment]
Flaky tests are failing but `AtomicConvFeaturizer` tests are now passing!
CC @rbharath

**Review by rbharath — APPROVED** [review]
Changes to `AtomicConvFeaturizer` look good! I think this PR should be good to merge ince once you're ready

**Comment by ncfrey** [comment]
Going to go ahead and merge this in and move on to fixing the slow tests for `AtomicConvModel`!

**Pull request merged**
