### PR TITLE
simple install one-liner

### PR DESCRIPTION
**Pull request by UnixJunkie**
Note that many people are allergic to conda/miniconda.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I tested on a Mac.

**Comment by UnixJunkie** [comment]
Also works like a charm on Linux.

**Comment by UnixJunkie** [comment]
I don't know why pip3 doesn't install the required dependencies automatically (joblib pandas sklearn tensorflow pillow).
But hey, I know almost nothing about Python and its ecosystem.

**Comment by rbharath** [comment]
@UnixJunkie Thanks for the suggestion! Would you mind signing the CLA? I think we can merge in this PR afterwards :)

**Comment by UnixJunkie** [comment]
What does CLA mean?

**Comment by UnixJunkie** [comment]
OK, I signed this:
https://www.clahub.com/agreements/deepchem/deepchem

**Comment by rbharath** [comment]
@UnixJunkie Congrats on your first merged DeepChem PR! Hope to see more coming our way

**Pull request merged**
