### PR TITLE
Custom directories and SmilesToImage for MolNet

### PR DESCRIPTION
**Pull request by VIGS25**
Added option of downloading and saving to custom directories for MolNet, and also the SmilesToImage featurizer, whereever applicable.

This in principle, would allow us to run the ChemCeption model with any of the datasets now.

### CODE REVIEW

**Comment by VIGS25** [comment]
Travis Failure is only in Python 2.7 and on unrelated tests. 
Also, I am seeing that the `test_maml` fails on Python 2.7 more regularly. Maybe this can be made flaky?

**Comment by peastman** [comment]
It's a lot of code to go through, but as far as I can tell it looks good.

**Comment by rbharath** [comment]
@VIGS25 Feel free to merge once ready

**Comment by VIGS25** [comment]
Good to merge, but I don't have write access.

**Pull request merged**
