### PR TITLE
Fix bug for Mol2VecFingerprint

### PR DESCRIPTION
**Pull request by nd-02110114**
I found the bug about the usage of mol2vec function,  so I fixed.

### CODE REVIEW

**Comment by peastman** [comment]
What bug is this fixing?

**Comment by nd-02110114** [comment]
We should pass the List for the first argument of `sentences2vec` function, but I didn't pass. 
Therefore, the return value of `sentences2vec` was not a vector (N×M matrix) and I misunderstood that we should apply the some aggregation method like sum or mean to comvert the  N×M matrix to a M dim vector.

**Comment by nd-02110114** [comment]
I think this PR is ready for the review

The CI failed by test_weave_fit_simple_infinity_distance, which is not related to this PR.
Recently, the CI is broken by test_weave_fit_simple_infinity_distance

**Review by rbharath — APPROVED** [review]
This looks good from my pass!

@nd-02110114 You know this featurizator much better than I do, so feel free to merge in once you feel this is ready :)

**Comment by nd-02110114** [comment]
Thanks you for checking! I merge in!

**Pull request merged**
