### PR TITLE
Optimize BPS symmetry functions to avoid using CPU

### PR DESCRIPTION
**Pull request by proteneer**
Optimizes tensor contractions with a reshape trick to avoid using the CPU.

### CODE REVIEW

**Comment by proteneer** [comment]
Address #787

**Comment by proteneer** [comment]
Did travis break?
```
/home/travis/build/deepchem/deepchem/deepchem/data/datasets.py", line 11, in <module>
    from deepchem.utils.save import save_to_disk
  File "/home/travis/build/deepchem/deepchem/deepchem/utils/__init__.py", line 14, in <module>
    from rdkit import Chem
  File "/home/travis/anaconda/envs/deepchem/lib/python3.5/site-packages/rdkit/Chem/__init__.py", line 28, in <module>
    from rdkit.Chem.rdmolops import *
ImportError: /home/travis/anaconda/envs/deepchem/lib/python3.5/lib-dynload/../../libz.so.1: version `ZLIB_1.2.9' not found (required by /home/travis/anaconda/envs/deepchem/lib/python3.5/site-packages/rdkit/Chem/../../../.././libpng16.so.16)
```

**Comment by rbharath** [comment]
Restarted build. Hopefully will fix itself

**Comment by rbharath** [comment]
Unfortunately, build still looks broken. Not sure what's going on here.

**Comment by proteneer** [comment]
Can you restart the build?

**Comment by proteneer** [comment]
Looks like build passed, feel free to merge when ready.

**Comment by rbharath** [comment]
LGTM

**Pull request merged**
