### PR TITLE
Move tensorflow_models and autoencoder_models into contrib

### PR DESCRIPTION
**Pull request by rbharath**
We're entering the last innings of our transition over to `TensorGraph` as the basis for all DeepChem tensorflow models. This PR moves modules `dc.models.tensorflow_models` and `dc.models.autoencoder_models` over to the contrib/ folder. The `TensorGraph` models that happened to live in `dc.models.tensorflow_models` have been migrated over into `dc.models.tensorgraph`.

### CODE REVIEW

**Comment by lilleswing** [comment]
Do we have a "Robust" multiask?  That is a multitask with a pass through for each task?  @miaecle

**Comment by rbharath** [comment]
No, not for `TensorGraph`. This is one of our potential TODOs for the DeepChem 2.0 release that @miaecle is working on I believe.

**Comment by miaecle** [comment]
@lilleswing @rbharath I am working on robust multitask and progressive, should finish within several days.

**Comment by rbharath** [comment]
Ok, going to go ahead and merge this one in since it's been open for a bit.

**Pull request merged**
