### PR TITLE
Code to run distributed MultitaskClassifier

### PR DESCRIPTION
**Pull request by saurabhclusterone**
This code is the example for how to run Deepchem MultitaskClassifier in distributed mode for distributed training and linear speed up.

### CODE REVIEW

**Comment by rbharath** [comment]
@saurabhclusterone Thanks for the contribution! This looks like a really cool addition.

As a couple of comments, this might be a better fit for the contrib directory since it shows a cool example of how to use DeepChem in practice. In addition, could you please sign the CLA? That will let us accept the contribution.

**Comment by saurabhclusterone** [comment]
@rbharath 

I had to confirm before signing the CLA, hence it took time. But now, I have contributed the code to contrib folder. Please confirm and accept the changes in new pull request. Thanks @rbharath !

**Comment by rbharath** [comment]
@saurabhclusterone Thanks for signing the CLA!

We're almost ready to merge. As a last change, can you remove the example for the core tensorgraph directory so it's only in contrib? We should be good to merge after.

**Comment by saurabhclusterone** [comment]
@rbharath 

I am sorry, I did not follow what you said. Currently I have the code file in contrib->tensorflow_models. 
So what do you mean by "remove the example for the core tensorgraph directory so it's only in contrib" .

**Comment by rbharath** [comment]
It looks in the files modified section of the PR like the original file is still in the core tensorgraph directory in addition to being in contrib. You'll need to run `git rm path_to_original_tensorgraph_file` in addition to moving the file in your local repository.

**Comment by saurabhclusterone** [comment]
@rbharath 

Is the PR done properly? I think so there was no conflict. If it is done, I will close the issue.

Let me know please.  Thank You!

**Comment by rbharath** [comment]
@saurabhclusterone Everything looks good! Congrats on your first merged PR :)

LGTM

**Comment by saurabhclusterone** [comment]
@rbharath 

Thank You!

**Pull request merged**
