### PR TITLE
Documentation fix for issue #613

### PR DESCRIPTION
**Pull request by LRParser**
Small documentation update

### CODE REVIEW

**Comment by LRParser** [comment]
Further adding a documentation example for pdbbind. One question is, how to focus analysis on a specific base protein? Example given here is 14HR

**Comment by rbharath** [comment]
@LRParser Additional documentation much appreciated! Thanks for your first deepchem PR :-)

Focusing analysis on a particular protein would entail using the trained model and making predictions on ligands for the given protein.

**Comment by rbharath** [comment]
@LRParser Going to go ahead and merge this in so people can benefit from the improved notes. More PRs welcome, and congrats on your first merged deepchem PR!

LGTM.

**Comment by LRParser** [comment]
Thanks!

**Pull request merged**
