### PR TITLE
PAINS filtering for Large_Scale_Chemical_Screens.ipynb#1355

### PR DESCRIPTION
**Pull request by puaykaipoh**
# Pull Request Template

## Description

Fix #(1355)

[Issue 1355](https://github.com/deepchem/deepchem/issues/1355) requires an addition of PAINS filter from [here](https://github.com/PatWalters/rd_filters). This PR added the PAINS filter

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist
#I followed the coding style of the tutorial which is a Jupyter Notebook

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [X ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by rbharath — APPROVED** [review]
This is an excellent contribution! I'm marking this ready to merge but will wait for the CI to finish running first

**Comment by rbharath** [comment]
@arunppsg I think test failures aren't related to this PR. Could you take a quick look and confirm this is ready to merge?

**Comment by arunppsg** [comment]
Hey, it looks good from my side except for one minor change: can you move `alert_collection.csv` from `examples/tutorials` to `examples/tutorials/assets` directory so that all assets for the tutorial are at the proper place?

**Comment by puaykaipoh** [comment]
> Hey, it looks good from my side except for one minor change: can you move `alert_collection.csv` from `examples/tutorials` to `examples/tutorials/assets` directory so that all assets for the tutorial are at the proper place?

Sir, i have moved `alert_collection.csv` to `examples/tutorials`

**Review by rbharath — APPROVED** [review]
LGTM! (Looks good to me)

Will merge in once tests pass

**Pull request merged**
