### PR TITLE
Adding the Freesolv dataset

### PR DESCRIPTION
**Pull request by atreyamaj**
## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [x] Documentations (modification for documents)

## Checklist

- [x] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [x] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [x] Run `mypy -p deepchem` and check no errors
  - [x] Run `flake8 <modified file> --count` and check no errors
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by atreyamaj** [comment]
This is a work in progress. I currently need to iron out a few kinks. When I test the Normalization Transformer individually on my local set-up it works fine, however when I try to do the same with the Transformer Generator implemented in the `MolnetLoader` class it throws an error saying that the dataset's shape couldn't be retrieved, which I can do pretty easily, as is shown here:

Error with MolNetLoader class:
Screenshot from 2021-07-01 06-00-19


The same thing but done explicitly without using predefined classes:
Screenshot from 2021-07-01 06-00-31

Currently trying to troubleshoot this, will add the doc string right afterwards.

**Comment by atreyamaj** [comment]
I am currently thinking of maybe overriding the transformer argument in `load_freesolv` while declaring the `loader` variable, however I am a bit skeptical in doing this.

**Comment by atreyamaj** [comment]
After a few changes, things seem to be working. I don't think the errors are related to Freesolv.

**Comment by vsomnath** [comment]
Looks good to me, and the test failures are unrelated to the loader.

**Review by rbharath — APPROVED** [review]
LGTM

**Pull request merged**
