### PR TITLE
Make TensorGraph Models inherit from sklearn.base.BaseEstimator

### PR DESCRIPTION
**Pull request by cxhernandez**
Fairly simple change. I also updated `meta.yaml` so that conda-build can execute via:

```bash
$ conda build -c conda-forge -c omnia devtools/conda-recipe/
```

And actually runs.

### CODE REVIEW

**Comment by rbharath** [comment]
Checking the definition of `sklearn.base.BaseEstimator` [here](http://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html), it looks like we'd need to implement `get_params` and `set_params`. Does this make sense for us?

**Comment by cxhernandez** [comment]
It should [inherit](https://github.com/scikit-learn/scikit-learn/blob/14031f6/sklearn/base.py#L183-L316) those methods. These methods are necessary for Osprey to try out different parameters with the same `Model` object.

I can make a test to see if they do indeed work.

**Comment by rbharath** [comment]
Adding a test sounds good! Would be OK to merge in with a test added and Travis passing.

**Comment by cxhernandez** [comment]
Seems to work locally! Let's see if Travis behaves....

**Comment by rbharath** [comment]
LGTM.

**Comment by rbharath** [comment]
Going to go ahead and merge, but I suspect getting osprey integration working will take a good chunk more effort since none of the existing models use `get_params` or `set_params` to store model hyperparameters.

**Comment by cxhernandez** [comment]
> Going to go ahead and merge, but I suspect getting osprey integration working will take a good chunk more effort since none of the existing models use get_params or set_params to store model hyperparameters.

If the hyperparameters are available in the `__init__` method of each `Model`, then we should be good. Otherwise, I'll have to interrogate you further about how this darn API works 😝

**Comment by rbharath** [comment]
I think hyperparameters are generally set in the `__init__` method for models, so we should be good.

**Comment by cxhernandez** [comment]
Btw I think with the changes made to `meta.yaml`, we could look into making a conda package for DC under the omnia or conda-forge channels.

**Comment by rbharath** [comment]
There is actually a deepchem omnia package. Just hasn't been updated in a long time (it's on 0.0.4) :-)

**Comment by cxhernandez** [comment]
lolll, well update it then

**Comment by rbharath** [comment]
Anyone can do it :-) Just need to make a PR to https://github.com/omnia-md/conda-recipes

**Pull request merged**
