### PR TITLE
Tensorflow independent environment

### LINKED ISSUE #2561: Make TensorFlow optional
Now that TensorFlow is only one of several frameworks we use, we should make it an optional dependency.  Currently if you don't have TensorFlow installed, `import deepchem` will fail.  We should put the imports for TF based features inside try/except blocks or only `import tensorflow` inside functions, the same way we do for PyTorch.

### PR DESCRIPTION
**Pull request by VIGNESHinZONE**
Fix #2561

- I have added `try` & `catch` based on a few sub-packages in deepchem like `metalearning`, `keras_models`, `rl` because these sub-packages are `tensorflow` dependent. 
- Didn't have a lot of problem in `trans` subpackage because the `TensorFlow` dependency was local.

cc: @peastman @rbharath

https://github.com/deepchem/deepchem/pull/2563 requires a tensorflow free environment for smoothly creating a `deepchem-[torch]` environment.

### CODE REVIEW

**Comment by VIGNESHinZONE** [comment]
In `transformer` subpackage, only `IRVTransformer` & `ANITransformer` have `tensorflow` depedency. 
https://github.com/deepchem/deepchem/blob/eab6ee63c1b3e958abe72a40efb2f5064201731b/deepchem/trans/transformers.py#L1540

https://github.com/deepchem/deepchem/blob/eab6ee63c1b3e958abe72a40efb2f5064201731b/deepchem/trans/transformers.py#L1977

Can we move these features into a seperate file called `tensorflow_transformers` and eventually do this in `__init__.py`

```
try:
  from deepchem.trans.transformers import IRVTransformer
  from deepchem.trans.transformers import ANITransformer
except:
  pass
```

**Comment by peastman** [comment]
It looks to me like they're just using TensorFlow for a bunch of standard math operations that could just as easily be done with Numpy.  I suggest we convert them.

I notice though that there don't seem to be any tests for ANITransformer, and also that it's written in TensorFlow 1.x style.  I wouldn't be surprised if it doesn't actually work, but no one noticed due to the lack of tests and because no one is using it.

**Comment by VIGNESHinZONE** [comment]
So should i put ANITransformer in a separate file like mentioned above or remove it completely? 
removed `tf` dependency from `IRVtransformer`

**Comment by rbharath** [comment]
@VIGNESHinZONE I think for ANITransformer, it's been known to be broken for some time so let's just comment it out. We'll have to note it in https://github.com/deepchem/deepchem/issues/2553.

**Comment by rbharath** [comment]
I think this PR will also need to be rebased since some merge conflicts have crept it

**Comment by VIGNESHinZONE** [comment]
@rbharath  I have made the changes.

**Review by rbharath — APPROVED** [review]
Ok, I think this is ready to merge in. I'm seeing only 1 test failure on a test unrelated to this PR.

@peastman Do you have any remaining review comments?

**Comment by peastman** [comment]
Looks good to me.

**Pull request merged**
