### PR TITLE
Adding Dragonn Example to contrib/

### PR DESCRIPTION
**Pull request by rbharath**
This PR starts the process of adapting Dragonn models developed by @jisraeli and others in https://github.com/kundajelab/dragonn into DeepChem. This PR copies over the Dragonn tutorial (https://github.com/kundajelab/dragonn/blob/master/examples/GTC_workshop_tutorial.ipynb) and attempts to get it functional.

### CODE REVIEW

**Comment by jisraeli** [comment]
Awesome. Might be good to idea to have a separate pip/conda/docker file for this?

**Comment by LRParser** [comment]
Awesome!

**Comment by lilleswing** [comment]
Are we waiting on anything besides yapf for this one?

**Comment by rbharath** [comment]
Need to do a little more cleanup and this should be ready to merge.

**Comment by rbharath** [comment]
This PR gets a basic DragoNN example partially running in DeepChem. There's a lot of work to be done to improve DragoNN integration with DeepChem, but I think there's enough work that will be involved that it's best to split up over multiple PRs rather than having one massive PR. Will open a new issue to coordinate.

Going to merge in.

**Pull request merged**
