### PR TITLE
Tensorflow 1.0.1

### PR DESCRIPTION
**Pull request by lilleswing**
Used auto-convert script to make tensorflow==1.0.1

I suggest after this pull request is accepted we do a git tag to deepchem 1.0.0

### CODE REVIEW

**Comment by lilleswing** [comment]
Please Tag This branch as 1.0.0
``` bash
git tag 1.0.0
git push origin --tags
```

After this is done I can create the docker image for 1.0.0

**Comment by lilleswing** [comment]
@rbharath this is ready whenever you want to start requiring tensorflow 1.0

**Comment by rbharath** [comment]
Yeah, I think we should go ahead and get this one in.

Does anyone have any reasons not to upgrade to TF 1.0? Will wait a day and then merge in if no one has any strong reasons.

**Comment by rbharath** [comment]
@lilleswing Tags pushed

**Pull request merged**
