### PR TITLE
Benchmark script clean-up

### PR DESCRIPTION
**Pull request by miaecle**
This PR replaces the old `benchmark.py` by the new `benchmark2.py` which utilizes `dc.molnet` module. 
It supports all the previous datasets/models/splits as well as new ones. Command line options and arguments should be the same, output format is a bit different(may cause breaks).

### CODE REVIEW

**Comment by lilleswing** [comment]
does 
```bash
python benchmark.py -d tox21

nosetests -v devtools/jenkins/compare_results.py --with-xunit
```
still work?

**Comment by rbharath** [comment]
I really like this change. Makes it much easier for new users to come in and duplicate MoleculeNet numbers.

Once @lilleswing's questions are addressed, should be good to merge.

**Comment by miaecle** [comment]
@lilleswing Good call, there is a subtle difference there. I fix it manually, do you know is there anywhere else may related to the change?

**Comment by rbharath** [comment]
LGTM

**Pull request merged**
