### PR TITLE
Fix pymatgen subclasses import error

### PR DESCRIPTION
**Pull request by JainSamyak8840**
## Description

Fix #(2459)
I am fixing sub class import error issue.
I changed all the  import statements of pymatgen that are importing classes relates to pymatgen.core module :
` from pymatgen import Structure`
 to
`from pymatgen.core import Structure`

## Type of change

Please check the option that is related to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [x] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [x] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [x] Run `mypy -p deepchem` and check no errors
  - [x] Run `flake8 <modified file> --count` and check no errors
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by rbharath — COMMENTED** [review]
Sorry for the slow response!

Looks good on my end but definitely not an expert at pymatgen.

@ncfrey @nissy-dev Could one of you take a quick look to approve?

**Comment by ncfrey** [comment]
Looks good! I think one of the latest versions of pmg made the core classes only accessible from `pymatgen.core`, so thanks for this fix!

**Comment by rbharath** [comment]
@JainSamyak8840 Is this PR ready to merge in?

**Comment by JainSamyak8840** [comment]
> 
> 
> @JainSamyak8840 Is this PR ready to merge in?

@rbharath  I was trying to create new pull request for another issue but it appended my new commits with #2460 pull request. I reset the new commits and  it is ready to merge now

**Review by rbharath — APPROVED** [review]
Looks good!

**Pull request merged**
