### PR TITLE
removing package pin

### PR DESCRIPTION
**Pull request by arunppsg**
Changes made:
- removed pin for yapf

### CODE REVIEW

**Comment by peastman** [comment]
If we remove the pin, no one will know which version they need to use, and every time a new version comes out everyone's PRs will immediately start giving errors.  I suggest we continue to pin it, just to a newer version.

**Comment by arunppsg** [comment]
Makes sense, I will pin it to the latest version of yapf (0.32.0).

**Comment by arunppsg** [comment]
Yapf version bump does not seem to cause additional failures in CI.

**Comment by arunppsg** [comment]
Merging this in as the 2 observed failures in CI are due to the usual ones (jax in windows).

**Pull request merged**
