### PR TITLE
API simplification to RL

### PR DESCRIPTION
**Pull request by peastman**
For flexibility, I defined the state of an environment to be a list of arrays.  But in practice, it usually is just a single array, and having to treat it as a list makes user code more complicated.  So I've now made it optional: the state can be either a single array or list of arrays as you choose.

### CODE REVIEW

**Comment by lilleswing** [comment]
@peastman open question are we anticipating needing an agent which can take multiple actions at each "step"?  
An example would be an a super mario RL agent which has to both jump and run forward at the same time.

Right now our implementation implicitly does a softmax and selects a single action for each evaluation of the policy network.

**Comment by peastman** [comment]
That's just another action.  For example, the OpenAI Gym Atari environments have 18 actions.  That's nine positions for the joystick, times two positions for the button (up or down).  An alternate description would be to say you're selecting two different actions at each step (joystick position and button position), but it's simpler to just multiply them and have a single action with more options.

**Comment by peastman** [comment]
The failure is an unrelated error in test_overfit.py.  All tests related to this change passed.

**Comment by rbharath** [comment]
LGTM.

I thought we nailed down most of the flaky tests. We might need to add that test to the flaky list too.

**Pull request merged**
