### PR TITLE
Tutorial detailing the creation of a deepchem dataset from novel data

### PR DESCRIPTION
**Pull request by kmckiern**
Regarding #820

### CODE REVIEW

**Comment by rbharath** [comment]
@kmckiern This looks amazing! The notebook will be a great resource for newcomers to DeepChem

Couple of small requests:
- Could you add a test for this notebook to https://github.com/deepchem/deepchem/blob/master/examples/notebooks/tests.py? (This will ensure the notebook is tested on Jenkins and stays functional).
- Would you mind adding a `.rst` file to the Notebooks directory for this notebook (https://github.com/deepchem/deepchem/tree/master/docs/source/notebooks) and linking to it from the index file (https://github.com/deepchem/deepchem/blob/master/docs/source/notebooks/index.rst)? That will let us render the notebook on the website.

**Comment by peastman** [comment]
Very cool!

**Comment by kmckiern** [comment]
So two complications regarding the test:
1. This data is still private.  I could potentially create a stripped down or randomized version.
2. I use a few packages that are not deepchem dependencies (pubchempy, seaborn, scipy)

Thoughts on how to address these?

**Comment by rbharath** [comment]
Great points. Some thoughts:

- A stripped down or randomized version of the data would be very useful. (Ideally users could try running through the tutorial themselves).
- No worries about the extra deps. The current notebooks already use extra dependencies (https://github.com/deepchem/deepchem/issues/810). Let's punt on the Jenkins test to a separate PR.

We should be good to merge once the `.rst` files are updated and data is stripped/randomized.

**Comment by kmckiern** [comment]
Sounds good, will do :)

**Comment by lilleswing** [comment]
The tutorial looks great!

p.s. you add additional deps for the notebook tests [here](https://github.com/deepchem/deepchem/blob/master/devtools/jenkins/test_notebooks.sh).

**Comment by kmckiern** [comment]
K, added a "safe" version of the data.

Looking over the tutorial again:

1. I lead by mentioning how when you get a random data file, it's useful to use a GUI to look at it.  Then I load a screenshot (png file) and explain how to use the visual to slice the pandas excel file.  Is there somewhere I can put the png?  I could potentially cut this part and just explain in words.

2. At the end, I save the csv to disk, as well as a dataset object, then reload for a sanity check.  Is this okay?

**Comment by lilleswing** [comment]
@kmckiern  I would suggest creating a folder deepchem/examples/notebooks/assets for the screenshot.  Images are nice :)

saving and reloading sanity check is good.

**Comment by rbharath** [comment]
@kmckiern Looking good! Just a couple more comments:

- Did a quick review pass through the tutorial and noticed `Image(filename='raw_data/dataset_gui.png')`. Should the `raw_data` folder be swapped out to the new assets folder? Similarly for the xlsx loading call.
- Would you mind tossing in the new deps into https://github.com/deepchem/deepchem/blob/master/devtools/jenkins/test_notebooks.sh as @lilleswing suggests and adding on a test in https://github.com/deepchem/deepchem/blob/master/examples/notebooks/tests.py? This should be easy enough that we might as well get it out of the way.

Almost there!

**Comment by kmckiern** [comment]
@rbharath @lilleswing 

Thank you for your suggestions, I think they're all addressed!

**Comment by lilleswing** [comment]
```bash
yapf -i examples/notebooks/tests.py
```

You need one more blank line before your new test

**Comment by kmckiern** [comment]
@lilleswing thanks!

**Comment by kmckiern** [comment]
Sorry my internet connect is bad at the moment, thought I'd try just adding a space.  Need to actually run yapf.  Will do this in 1-2 hrs.

**Comment by kmckiern** [comment]
K, assuming everything passes, I'm finished with edits :smile:

**Comment by rbharath** [comment]
@kmckiern Everything looks good. Congrats on your first accepted DeepChem PR!

LGTM

**Pull request merged**
