### PR TITLE
fix gpu installation

### PR DESCRIPTION
**Pull request by Chahalprincy**
Fix GPU installation. #2793 this changed the installation process and there were few updates needed for GPU installation.

## Type of change

Please check the option that is related to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rbharath** [comment]
Thanks for the contribution!

@arunppsg Could you do a quick review pass when you get a chance?

**Comment by arunppsg** [comment]
LGTM! 

Hey @Chahalprincy, I have also forgotten to add tensorflow and jax gpu installation there (they are only there for the CPU right now) earlier. Will you be interested in adding them? Thanks!

**Comment by Chahalprincy** [comment]
Thanks, @arunppsg. I've added the Jax GPU dependencies, I didn't see any TensorFlow GPU dependencies in the previous version also. So, I have not added those in. Please let me know if you need any changes.

**Comment by arunppsg** [comment]
The failures seems unrelated to this PR, will merge this in. Thanks for your contribution!

**Pull request merged**
