### PR TITLE
Add performance counter.

### PR DESCRIPTION
**Pull request by proteneer**
This is a small quality of life change that tells you the # of samples trained per minute with a given model.

### CODE REVIEW

**Comment by proteneer** [comment]
eg: with ANI1:

```
Starting epoch 0
Ending global_step: 99 Average loss: 103.903, Samples Per Minute: 43824.5
Ending global_step: 199 Average loss: 0.0889479, Samples Per Minute: 44928.9
Ending global_step: 299 Average loss: 0.0492182, Samples Per Minute: 45330
Ending global_step: 399 Average loss: 0.0312314, Samples Per Minute: 45391.3
Ending global_step: 499 Average loss: 0.0209619, Samples Per Minute: 45476
```

**Comment by proteneer** [comment]
Oddly enough using the queue (use_queue=True) seems to have made no difference, if anything it seems to have made things a little slower.

**Comment by peastman** [comment]
Do you want to reset `start_time` and `start_step` each time you print it out?  Since the loss refers to just the most recent interval, I would have expected the speed to do the same.

**Comment by proteneer** [comment]
Do you want the performance counter to oscillate over time? For performance tuning, I generally find it more intuitive if it converges (whereas for loss this isn't necessarily true.)

**Comment by rbharath** [comment]
I'm going to go ahead and close this old PR.

**Pull request closed without merging**
