### PR TITLE
Parallelize RdkitGridFeaturizer

### LINKED ISSUE #1361: Speed up PDB complex featurization to use multiple cores
The PDBBind featurization example introduced in https://github.com/deepchem/deepchem/pull/1360 does featurization of complexes on a single core. This takes roughly a minute per molecule, the majority of which time is used to load the protein PDB into RDKit.

This code should be modified to use multiple cores to speed up the featurization. Otherwise, featurizing the refined and full subsets of PDBBind won't be feasible.

### PR DESCRIPTION
**Pull request by peastman**
Fixes #1361.

Since RDKit doesn't release the GIL, I had to use multiprocessing.  That requires that every object involved (including the RdkitGridFeaturizer itself) can be pickled, which required restructuring it.  For example, I had to get rid of all the lambdas.  A bit of a pain, but it works.

There's one remaining problem which I'm kind of stuck on.  When I run the test_rdkit_grid_features.py suite on my Mac, it hangs part way through.  On a different computer running Linux it works fine.  And it isn't a problem with any individual test.  I can run each one and it works fine.  But that file contains several separate test classes (`TestHelperFunctions`, `TestFeaturizationFunctions`, `TestRdkitGridFeaturizer`, etc.), each with multiple tests.  Running all the tests in any one of those works.  But if I run all the tests in all classes at once, it hangs.  The hang occurs when calling into RDKit, so it appears to be some kind of a deadlock inside RDKit, not in the Python code.  If anyone can help with this, I'd be very grateful.

### CODE REVIEW

**Comment by proteneer** [comment]
@bpkelley @greglandrum - any ideas on the deadlock inside RDKit? AFAIK RDKit should be multiprocess/fork safe but best to confirm with these two.

**Comment by peastman** [comment]
If you want to reproduce it, check out this branch and run `nosetests deepchem/feat/tests/test_rdkit_grid_features.py`.  I've encountered it with RDKit 2017.09.3.0 on Python 3.6.1 on macOS 10.13.6.

**Comment by greglandrum** [comment]
We definitely keep thread safety in mind and do run a number of tests to verify it. Having said that, those tests are not comprehensive, so it's likely that there are thread safety problems. We fix them whenever they come up.

Digging into a large codebase like deepchem to try and figure out what it's doing with the RDKit that is causing a problem is not something I'm likely to have time to do in the foreseeable future. I'd love to help, but that's a big ask.

If you have a minimal reproducible (ideally that's more or less "pure" RDKit), I'd be happy to try and figure out what's going on.

**Comment by peastman** [comment]
I think you can mostly ignore all the DeepChem code.  Just run the one command I listed and wait for it to hang.  It will then be stalled inside RDKit.  If you can figure out what it's waiting on, I can figure out what in DeepChem is triggering it.

**Comment by bp-kelley** [comment]
With the latest rdkit (2018.03)

```
nosetests deepchem/feat/tests/test_rdkit_grid_features.py
........................./Users/kellebr5/devel/deep_learning/deepchem/deepchem/feat/rdkit_grid_featurizer.py:1067: UserWarning: Flat features are used, output will be flattened
  warn('Flat features are used, output will be flattened')
..../Users/kellebr5/devel/deep_learning/deepchem/deepchem/feat/rdkit_grid_featurizer.py:1055: UserWarning: ecfp_hashed feature is used, output will be flattened
  warn('%s feature is used, output will be flattened' % feature_type)
...
----------------------------------------------------------------------
Ran 32 tests in 68.083s

OK
```

**Comment by peastman** [comment]
I just tried upgrading to the latest RDKit, but I still get the hang.  Are you on a Mac?  (It works for me on Linux.)  Also, are you using the code from this PR, not the master branch?

**Comment by bp-kelley** [comment]
yes to both.  However, I can pretty much say my test environment is not the same as yours.  Any chance you could tar up your anaconda environment and stick it somewhere?   Building dev environments for deepchem is getting harder and harder :)

**Comment by peastman** [comment]
> Building dev environments for deepchem is getting harder and harder :)

That is sadly true!  I've been trying to make it easier, but there's a tension between wanting to reduce the number of dependencies and wanting to use libraries other people have written.

The following should let you reproduce the problem.  It creates an environment, installs everything required, and runs the test.  It's based on https://github.com/deepchem/deepchem/blob/master/scripts/install_deepchem_conda.sh.  On my computer, the test hangs.

```
conda create -y --name test python=3.6.1
source activate test
conda install -y -c omnia -c conda-forge pdbfixer=1.4
conda install -y -c rdkit rdkit=2017.09.1
conda install -y -c conda-forge joblib=0.11 \
    six=1.11.0 \
    scikit-learn=0.19.1 \
    networkx=2.1 \
    pillow=5.0.0 \
    pandas=0.22.0 \
    nose=1.3.7 \
    nose-timer=0.7.0 \
    flaky=3.3.0 \
    zlib=1.2.11 \
    requests=2.18.4 \
    xgboost=0.6a2 \
    simdna=0.4.2 \
    jupyter=1.0.0 \
    pbr=3.1.1 \
    setuptools=39.0.1 \
    biopython=1.71 \
    numpy=1.15
pip install tensorflow
git clone https://github.com/peastman/deepchem.git
cd deepchem
git checkout parallelrdkit
python setup.py develop
nosetests deepchem/feat/tests/test_rdkit_grid_features.py
```

**Comment by rbharath** [comment]
@peastman Would it be OK to merge in this PR and track the hang on a different issue? I'm curious to try this out on a linux box and get some example models training

**Comment by peastman** [comment]
Ok.  And we can see who else encounters the hang.

**Comment by rbharath** [comment]
This is really, really slick! Here's an htop screenshot showing it maxing out all my cores. 

screenshot from 2018-08-25 20-34-22

**Pull request merged**
