### PR TITLE
Small updates for atomic convs

### PR DESCRIPTION
**Pull request by lilleswing**
Test Dataset can't be transformed as it doesn't have y values -- I changed it to a prediction.

Main change is the documentation of the atomic convolution layer getting the number of channels correct.

This is surprising to me -- my intuition in line with convolutions would be to SUM over all the atom type masks instead of making each one a feature.

### CODE REVIEW

**Comment by joegomes** [comment]
@lilleswing The test dataset transformer error was caused by an empty `tasks` attribute in the dataset.  I've re-uploaded the fixed dataset, can you try evaluating again?

Summing over atom types will throw out any information you give the network about atom types.  We sum over all neighbor atoms of a specific type for a given radial filter.

**Comment by rbharath** [comment]
@lilleswing Changes look good with only yapf failures. Let me know once you think it's ready to merge.

I'd recommend trying a head-to-head test with both variants. There are many architectural choices which can be tweaked here.

**Comment by joegomes** [comment]
I agree it would be good to compare.

**Comment by lilleswing** [comment]
Well my intuition is wrong until we start learning atom_type filters instead of one-hot encoding for each atom type..  Pushed update which should fix travis and reverted opt_scaffold as it works now.

**Comment by rbharath** [comment]
LGTM.

**Pull request merged**
