### PR TITLE
Merges in tensorflow implementation of Massively Multitask Networks from tfvs

### PR DESCRIPTION
**Pull request by rbharath**

### CODE REVIEW

**Comment by rbharath** [comment]
This PR adds:

1. Google's tensorflow implementation of massively multitask networks (see [tfvs](https://code.googlesource.com/tfvs/+/master)). This code has been significantly changed from the original google implementation
..1. The `model_config` proto is no longer used to store model state. Instead, the `model_params` dict is used as in the rest of `deepchem`.
..2. `tfvs` usese the global tensorflow graph. This causes terrible problems when using multiple tensorflow objects simultaneously. This has been fixed by using scoped tensorflow graphs throughout the code.
..3. The tensorflow models now inherit from the `Model` class like all other deepchem models. Dependencies on google internal protos have been removed. Dependencies on `input_generator` have been replaced to use `deepchem`'s `Dataset` object instead.
2. The `iterbatches` method has been added to `Dataset` to allow for easy iteration over minibatches of data. 
3. The `deepchem.models` submodule has been restructured. All `sklearn` models are in `deepchem.sklearn_models`, all `keras` models in `deepchem.keras_models` etc.

**Comment by hainm** [comment]
It is still non-trivial to install tensorflow correctly  :(

https://github.com/tensorflow/tensorflow/issues/350

**Comment by rbharath** [comment]
@hainm Yes, agreed, this is a major pain point :-(. Unfortunately, tensorflow has a lot of goodies that the other python deep-learning libraries just don't yet (multi-GPU, multi-Node training especially). My personal experience is that things are pretty pain-free on Ubuntu 14.04 and up, but on older Ubuntu versions, it's pretty bad. I'm trying to see what I can do to make this less painful.

**Comment by hainm** [comment]
Cool

**Pull request merged**
