### PR TITLE
user_defined_features usage in featurize.py

### PR DESCRIPTION
**Pull request by joegomes**
user_defined_features were previously discarded during data frame standardization in featurize.py.  Featurization with user_defined_features works now.  Fixed the usage of DataFeaturizer.featurize in examples/pdbbind_nnscore.py

### CODE REVIEW

**Comment by joegomes** [comment]
TODO: Once I have QuantumMachine deep-chem running I will add a test for user_defined_features feature type

**Comment by rbharath** [comment]
@joegomes Thanks for the fix! Would you like me to merge now (once Travis finishes running) or would you like to add the test before merging in?

**Comment by joegomes** [comment]
@rbharath Either is fine with me assuming Travis is successful.  You could wait since I will have the test added in a day or two

**Comment by rbharath** [comment]
Ack, it looks like the Travis build is failing. Could you look into this locally? You can debug by running `nosetests -v deepchem` and run the same suite that's running on Travis.

If the test will be added in a day or two, I'll just go ahead and wait for the test (having that in here will make sure we won't break ```user_specified_features``` again.

**Comment by rbharath** [comment]
To follow up on this thread, is this fix still needed? Our discussion on Friday IRL suggested that the needed information might have been in the original df to begin with.

**Comment by joegomes** [comment]
@rbharath The original problem this fixed was that the user-defined data was not moved from raw df to the standardized df.  I figured out a better way to do that by moving the add_user_defined_data function into the standardize_df function, so this pull req is a bit outdated.  I'm going to add some commits later today that include this, a few small fixes, and an api test.

**Comment by joegomes** [comment]
I've finished the code for this pull req in a different branch.  I'll close this and submit a new pull req once I get pathos running.

**Pull request closed without merging**
