### PR TITLE
A3C works with recurrent layers

### LINKED ISSUE #639: GRU layer with RL
I want to use a TensorGraph GRU layer as part of a model for reinforcement learning.  It's not clear how to make that work.  I'm pretty sure it's going to need some modifications, but I'm not certain of the best way to do it.

The GRU layer doesn't expose its internal state in any way.  Every time you call `session.run()`, it reinitializes the state to all zeros, runs that batch through it, and throws away the final state.  But for RL, we call `run()` repeatedly to select the action for the next step, and we somehow need to be able to preserve that state from one step to the next.  Separately from that, we also sometimes call `run()` to evaluate the loss on a rollout, and in that case it is appropriate to reinitialize the state to zero for the start of the rollout.

How can we modify the GRU layer to make it work with this?

### PR DESCRIPTION
**Pull request by peastman**
Fixes #639.

### CODE REVIEW

**Comment by lilleswing** [comment]
have you tested it on any more complex environments?

**Comment by peastman** [comment]
Yes, I have it playing Pong with it right now.

**Comment by lilleswing** [comment]
Nice!  Is it CPU constrained for running the environment or GPU constrained for applying the gradients and evaluating the policy and value networks?

**Comment by peastman** [comment]
Using the GPU is slower than running everything on the CPU.  The amount of computation it's doing there isn't enough to outweigh the cost of sending data back and forth.

**Comment by peastman** [comment]
@rbharath can this be merged?  I have a couple of other PRs ready to go, but they involve the same files as this one, so I don't want to submit them until this has been merged.

**Comment by rbharath** [comment]
Yep, this PR looks good.

LGTM.

**Pull request merged**
