### PR TITLE
Adding MoleculeNet tutorial 3

### PR DESCRIPTION
**Pull request by rbharath**
This PR adds a tutorial introducing MoleculeNet and should slot in as the new tutorial 3 in our sequence.

CC @peastman

### CODE REVIEW

**Comment by peastman** [comment]
Looks good!  How about adding an overview of what's in molnet?  List the major categories of datasets, and the particular ones in each category.  Also a link to https://deepchem.readthedocs.io/en/latest/moleculenet.html, which has more information on each one.

**Comment by peastman** [comment]
> This keyword API is a little awkward. It doesn't provide for a convenient way for you to use a custom featurizer/splitter or to specify the transformations you want to apply to the dataset. We're working on ways to refactor this API to make it more friendly.

Maybe we should just update the API, then update all the tutorials to use the new version.  I can give that a try if you like.

**Comment by rbharath** [comment]
Good feedback! Let me update the tutorial to add an overview.
 
> Maybe we should just update the API, then update all the tutorials to use the new version. I can give that a try if you like.

Yes please go for it! That would be very helpful :)

**Comment by rbharath** [comment]
I've added an overview of all our datasets. It's not super detailed yet, but that might be enough work that's it's better left for a future PR.

@peastman Should we merge in this PR now or should we wait for the MoleculeNet API fix PR to come in first?

**Comment by peastman** [comment]
I don't think we need to wait for the API change.  That will take a while.

Can we make the link to the API docs a bit more prominent?  Maybe at the top of the list of categories, say something like, "More details on each of these datasets can be found at..."

**Comment by rbharath** [comment]
Just updated  with a more prominent link at the top of the categories. Also cleaned up the category listing a bit. Does it look clear now?

**Comment by peastman** [comment]
Looks good!

**Pull request merged**
