### PR TITLE
Weave model

### PR DESCRIPTION
**Pull request by miaecle**
This PR adds in:

- Weave models based on Steven Kearnes's graph convolution model: [https://arxiv.org/abs/1603.00856](url)

results on tox21(index):
train, 0.850, valid, 0.782
results on delaney
train, 0.909, valid, 0.825

### CODE REVIEW

**Comment by rbharath** [comment]
@miaecle Awesome, thanks for getting this in! It looks like there are yapf issues on a file. Once those are fixed, glad to merge this in.

**Comment by miaecle** [comment]
@rbharath A submodule of the method(gaussian membership expansion) updated, all parts are finished. Now it seems the delaney performance could be increased to over 0.86

**Comment by lilleswing** [comment]
New High Score for delaney!

**Comment by miaecle** [comment]
@lilleswing @rbharath benchmark result on delaney(index): train, 0.986, valid, 0.875 Yeah!

**Comment by rbharath** [comment]
@miaecle Nice! Looking forward to seeing how Weave does on the wider MoleculeNet benchmarks.

**Pull request merged**
