### PR TITLE
Progressive multitask classifier

### PR DESCRIPTION
**Pull request by miaecle**
This PR adds:

- Progressive multitask classifier #1144

### CODE REVIEW

**Comment by peastman** [comment]
Every new model should include a test case in test_estimators.py to make sure `make_estimator()` works correctly with it.  See #1142.

**Comment by rbharath** [comment]
@miaecle Could you add the test @peastman suggested? We should be good to merge once that's in.

**Comment by miaecle** [comment]
@peastman I have tried to fit the two progressive models to the estimator framework, but they are built on the submodels of tensorgraph, which don't seem to be compatible with estimator right now.(multiple loss functions) Also an estimator-compatible IRV Classifier is been updated through this PR. #1142 
@rbharath Sorry for the delay, I think this is the best we can achieve right now, let me know if anything else is needed.

**Comment by rbharath** [comment]
@miaecle Thanks for looking into this! Will go ahead and merge this PR. Let's discuss the submodel support in https://github.com/deepchem/deepchem/issues/1142.

LGTM

**Pull request merged**
