### PR TITLE
auPRC metric and doc strings for graph models

### PR DESCRIPTION
**Pull request by miaecle**
This PR adds in:

- New metric: area under precision-recall curve for classification tasks

- doc strings, unit tests and minor modifications for graph models(DTNN, DAG, weave)

### CODE REVIEW

**Comment by miaecle** [comment]
@lilleswing Also is there anything going wrong with doctest? Log does not seem normal.

**Comment by lilleswing** [comment]
@miaecle can you send me a travis link?  It looks like you are passing travis on all the completed runs so far.

**Comment by rbharath** [comment]
@miaecle Thanks for fixing all these docstrings! This is really useful for everyone :+1:. Glad to merge this in once the tests pass.

**Comment by rbharath** [comment]
LGTM.

**Pull request merged**
