### PR TITLE
Tensorflow 1.4

### PR DESCRIPTION
**Pull request by lilleswing**
tensorflow-gpu=1.4.0 isn't out yet on anaconda cloud but I wanted to see if we were passing tests.

### CODE REVIEW

**Comment by lilleswing** [comment]
https://github.com/deepchem/deepchem/issues/921

**Comment by lilleswing** [comment]
Blocked by https://github.com/conda-forge/tensorflow-feedstock/pull/45

**Comment by rbharath** [comment]
We should make this PR a priority in the new year. Lots of major upgrades in TF 1.4 like `tf.data` and `tf.keras` that would be useful for us.

**Comment by lilleswing** [comment]
We either have to 

1. Remove MdTraj, XGBoost from the codebase
2. Move MDTraj and XGBoost tests to jenkins and stop supporting linux kernels < 4.2

neither option seems particularly fun to me.

See full discussion here
https://github.com/deepchem/deepchem/issues/960

**Comment by lilleswing** [comment]
This should be safe to go -- it builds on top of the rdkit PR so merge this in after

**Comment by lilleswing** [comment]
Closing in favor of https://github.com/deepchem/deepchem/pull/927

**Pull request closed without merging**
