### PR TITLE
Corrected Test Case for Smiles Tokenizer (for fix #2566)

### PR DESCRIPTION
**Pull request by niklashoelter**
Corrected test case for fix #2566 

Since the tokenizer has not encoded triple bonds before fix #2566 , the test case was also wrong because the token was not included. Added token 38 (´#´) for correct comparison of encoded and given sequence. @rbharath @seyonechithrananda

### CODE REVIEW

**Comment by NiklasHoelter** [comment]
Okay, seems like there's one more problem with the Roberta. Since im not familiar with that, maybe @seyonechithrananda knows that better.

**Comment by rbharath** [comment]
@niklashoelter I think the issue you're seeing is a formatting error from `yapf`. Can you do 
```
pip install yapf==0.22
yapf --version # To check the right version is being used
```
Then run
```
yapf -i /path/to/modified_files
```
To fix the formatting issue?

**Comment by seyonechithrananda** [comment]
Hey @niklashoelter, I recently added yapf formatting but don't think I can commit to this PR. Is there any chance you could allow edits from maintainers (in the PR settings)?

**Comment by seyonechithrananda** [comment]
Added @niklashoelter' changes to #2578 - with yapf formatting as @rbharath suggested. It still preserves your commit history though and referenced this PR! Thanks for this fix :)

**Comment by niklashoelter** [comment]
Thank you very much, @seyonechithrananda ! Yapf was just new to me so i just did not found the time for running it earlier, now you have been faster ;-) Nice that this works now, thanks also to @rbharath !

**Pull request closed without merging**
