### PR TITLE
Add new datasets to 3P benchmark.

### LINKED ISSUE #499: [BUG] HopV dataset wrong featurizer variable name.
In https://github.com/deepchem/deepchem/blob/master/deepchem/molnet/load_function/hopv_datasets.py

L35 should be:
```
featurizer = deepchem.feat.CircularFingerprint(size=1024)
```
This will allow customized featurizer input.

Will send a PR to fix it.

### PR DESCRIPTION
**Pull request by XericZephyr**
- Add new dataset loading functions to the `run_benchmark` function for third-party benchmark.
- Fix #499.

### CODE REVIEW

**Comment by rbharath** [comment]
@XericZephyr Thanks for the PR

@miaecle Could you review the PR and LGTM once it looks good?

**Comment by XericZephyr** [comment]
Another suggestion to @miaecle, we can write a general `check_featurizer` function to avoid `duplicate code` problem.

**Comment by miaecle** [comment]
@XericZephyr LGTM
That's a good point, basically I am trying to make things straightforward, but as new models and datasets keep coming in, using a dict as `check_featurizer` could get redundant.

**Comment by rbharath** [comment]
@XericZephyr Thanks for the fix!

@miaecle Thanks for the review!

LGTM.

**Pull request merged**
