### PR TITLE
Attempted Debugging of automatic pushes of docs to deepchem.io

### PR DESCRIPTION
**Pull request by rbharath**
The deepchem.io docs haven't been automatically updated in a long while. I vaguely recall that there's some bug preventing the automatic doc pushes. This PR attempts to debug this issue.

### CODE REVIEW

**Comment by rbharath** [comment]
I think the issue might be due to the fact that travis doesn't provide value of encrypted environment variables to untrusted builds (from other repos). The question is then how to trigger a trusted build? We could make a pull request from deepchem to itself perhaps...

**Comment by mpharrigan** [comment]
You have to merge the pull request or commit to master. [Remove the echo aws secret lines first!]

**Comment by rbharath** [comment]
Good call. Will give it a try now, with debugging echo statements removed :).

Going to go ahead and merge this branch in to trigger a trusted build. Will continue debugging in another branch if necessary.

**Comment by rbharath** [comment]
It looks like the automatic website updates now work! Yay, should be much easier to update the website docs moving forward.

**Pull request merged**
