### PR TITLE
Fix some Failing tests for windows support

### PR DESCRIPTION
**Pull request by abster12**
I have added the fixes for the failure of Log layer as well as the tests for molnet.

### CODE REVIEW

**Comment by abster12** [comment]
@peastman Could you take a look if the fixes are appropriate.

**Comment by peastman** [comment]
I don't understand your changes.  The code

```python
for lastrow in reader:
  pass
```

is supposed to read through all lines in the file, so when it finishes `lastrow` is left holding the last row of the file.  By changing that to a `break`, you make it exit immediately and you get the first row, not the last one.

**Comment by abster12** [comment]
Yeah what was happening was it was taking in all the elements in the 1st pass so when it was going for the 2nd pass lastrow was turned into an empty variable thus giving the errors such as list index out of range

**Comment by abster12** [comment]
There is only one row in results.csv which gets copied to ``` lastrow ``` in the first pass which is why the break needs to be there.

**Comment by peastman** [comment]
Clearly it doesn't think so, or it would break at that point anyway.  It thinks there's more than one line.  Why?

**Comment by abster12** [comment]
So I ran the same commands on both the anaconda prompt on windows and bash shell the output comes out different in both the cases. It seems the line endings differences in unix and windows is causing this.

**Comment by peastman** [comment]
According to the documentation at https://docs.python.org/3/library/csv.html, whenever we open a file to pass to a csv reader, we should include the option `newline=' '`.  This enables universal newline support.  A search through the codebase for "import csv" turns up 12 files in which we're using the csv module.  So we need to check all of them and make sure we include that option everywhere appropriate, so it will work consistently on Windows and Unix.

One issue with this: that option only exists in Python 3, not Python 2.  How do we want to handle this?  Possibly it's time for us to start dropping Python 2 support.

**Comment by abster12** [comment]
I will try and add this to all those files and modify the pull request.

**Comment by abster12** [comment]
So I tried this and we have to set ``` newline = '\n' ``` for it to work in windows as well as unix environments.

**Comment by peastman** [comment]
> So I tried this and we have to set newline = '\n' for it to work in windows as well as unix environments.

Sounds like we need to be careful about this.  We need to make sure we only do that for files we created and we know exactly what newlines it has.  We shouldn't do that anywhere that we could be reading a user supplied file.

We still have the question about Python 2 support.  @rbharath what are your thoughts?

**Comment by abster12** [comment]
I read a bit about it , the file endings in windows are like ``` '\r\n' ``` and in unix environments they are ``` '\n' ```. So if we added ``` newline = '\n' ``` we shouldn't encounter any major problems. Am I wrong to think about it like this?

**Comment by rbharath** [comment]
I think we should leave Python 2 support for DeepChem 2.2, but I'm pretty open to dropping Python 2 support in the subsequent release. The community is heading that way in general

**Comment by peastman** [comment]
> the file endings in windows are like '\r\n' and in unix environments they are '\n'.

It's a little more complicated than that.  Every file has whatever line endings it has.  What you really mean is that different platforms have standardized on different line endings.  File editors on different platforms tend to create files with different line endings.  But if you copy that file to a different computer running a different OS, its line endings don't change.

That's why we need to be careful here.  A Windows user might create files with Windows line endings, and a Linux user might create files with Unix line endings.  And then DeepChem could be asked to read both those files, and it needs to read both of them correctly.

Specifying `newline=' '` is *supposed* to accomplish that.  It enables "universal newline support", which tries to be intelligent about analyzing your file and interpreting all styles of newlines correctly.  So I don't understand why that wouldn't work in this case.

> I think we should leave Python 2 support for DeepChem 2.2, but I'm pretty open to dropping Python 2 support in the subsequent release.

Agreed.  The Python pledge calls on all projects to drop Python 2 support no later than 2020.

**Comment by abster12** [comment]
I added ``` newline = '' ``` and it seems to work and there is some other unrelated failure I think.

**Comment by rbharath** [comment]
I think this PR has been superseded by the recent changes adding Windows support in. I'm going to go ahead and close.

**Pull request closed without merging**
