### PR TITLE
Molnet v2 changes

### PR DESCRIPTION
**Pull request by miaecle**
This PR adds in:

- Support SMILES based regular models(multitask, graphconv) on pdbbind, qm7, qm8 and qm9

- Changes on DAG model: add in parameter `default_max_atoms` as the upper limit of number of graphs evaluated for each molecule

- `seed`  argument in benchmark script

All these changes are applied in MoleculeNet v2, may be helpful to those who would like to rerun the experiments.

### CODE REVIEW

**Comment by rbharath** [comment]
Looks like yapf is complaining. Should be good to merge in fixed.

**Comment by miaecle** [comment]
@rbharath Sounds good, already yapfed on all changes. Waiting for tests.

**Comment by miaecle** [comment]
@rbharath Also there is a python2/python3 fault here(`multitask_regressor.py` and `multitask_classifier.py`) failing benchmark runs on graph models. Should we modify it?

**Comment by rbharath** [comment]
Looks like Travis is passing, so going to go ahead and merge in. We can take care of any remaining issues in future PRs. LGTM.

**Pull request merged**
