### PR TITLE
Neural Fingerprint Easy Access

### PR DESCRIPTION
**Pull request by lilleswing**
Easy Access to Neural Fingerprints.

With this you can use a pre-trained GraphConv model as a featurizer/dimensionality reducer for molecules.

### CODE REVIEW

**Comment by rbharath** [comment]
@lilleswing This is nice! It would be really cool to add a section to one of our tutorials explaining how to generate neural fingerprints

**Comment by lilleswing** [comment]
What is the use case people think of when they want to use neural fingerprints?

**Comment by rbharath** [comment]
@lilleswing Usually, people want to inspect the learned fingerprints to gain intuition. For example, they might want to cluster with t-SNE or they might want to do something like similarity search with the learned fingerpritns

**Comment by rbharath** [comment]
Going to go ahead and merge this in.

LGTM

**Pull request merged**
