### PR TITLE
Master Atom In Graph Featurizer

### PR DESCRIPTION
**Pull request by lilleswing**
Add constructor arg to create a "master atom" in ConvMolFeaturizer which creates an atom with a bond to all atoms.  This can help with long-range interactions.

### CODE REVIEW

**Comment by rbharath** [comment]
Could you add a unit test for the new `master_atom` flag?

**Comment by patrickhop** [comment]
@lilleswing Did this help performance? I've been meaning to try this for awhile.

**Comment by lilleswing** [comment]
@patrickhop incrementally better result on many datasets using it as a drop in replacement.  I haven't done full HyperParameter scans -- but comes to the top in many random scans.

**Comment by patrickhop** [comment]
@lilleswing nice work. what features did you use to init the master node? is it just a random init?

**Comment by lilleswing** [comment]
I tried a couple of things but ended up with the mean of the molecule’s
atom features.

**Comment by rbharath** [comment]
@lilleswing Going to go ahead and just merge this one in since it's been open for a while and people might want to experiment with it. More tests in a future PR would be welcome though :)

LGTM

**Pull request merged**
