### PR TITLE
#1185: SDF loader should load tasks from SDF File

### PR DESCRIPTION
**Pull request by christabella**
This PR addresses #1185:
- Checks if file *.sdf.csv exists
- If *.sdf.csv exists, maintain old path for backwards compatibility
- If it does not exist, look up the "tasks" in the SDF file itself, with `mol.getProp()`

### CODE REVIEW

**Comment by rbharath** [comment]
@christabella Thanks for the PR! It looks like one of the SDF unit tests are failing. Could you take a look and fix?

**Comment by christabella** [comment]
> @christabella Thanks for the PR! It looks like one of the SDF unit tests are failing. Could you take a look and fix?

@rbharath Thanks for your comment! I've fixed that but now there's something else: the python2.7 tests all pass but 3.5 fails, because some of the scores are above 0.2:
```assert scores[metric.name] < .2```

I will take a look at this again soon.

**Comment by rbharath** [comment]
This one looks like a flaky test, so we should be good to merge. Congrats on your first merged DeepChem PR!

LGTM

**Comment by christabella** [comment]
@rbharath thank you for the review!

**Pull request merged**
