### PR TITLE
Dft 8 final

### PR DESCRIPTION
**Pull request by GreatRSingh**
## Description

Fix #(issue)

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by shreyasvinaya** [comment]
@GreatRSingh there seems to be a couple of linting failures, could you please fix them

**Comment by shreyasvinaya** [comment]
@GreatRSingh on initial review, the code looks fine

@rbharath do we add the large number of text files to deepchem package or can we add it to the s3 bucket?

**Comment by GreatRSingh** [comment]
> @GreatRSingh there seems to be a couple of linting failures, could you please fix them

Those mypy failure are unrelated to this PR.

**Review by rbharath — COMMENTED** [review]
There are CI errors (possibly not related to this PR). @GreatRSingh will take a look at debugging

**Review by rbharath — APPROVED** [review]
LGTM

**Pull request merged**
