### PR TITLE
Tests for rdkit_grid_featurizer module

### PR DESCRIPTION
**Pull request by marta-sd**
I'm playing around with `rdkit_grid_featurizer` and I added some tests for this module. I also found a tiny bug in `get_ligand_filetype` and fixed it (see 1567da2).

I plan to add more tests (especially for the `RdkitGridFeaturizer` class), but I think it will be too much code to revise at once, so I'm going to push them in chunks.

Please, take a look at my code and let me know if you find such tests useful. Also, please check whether my assumptions about the parameters and results are reasonable.

### CODE REVIEW

**Comment by marta-sd** [comment]
OK, so I forgot you support Python 2.7. Sorry for the mess, I hope it'll be fine now.

**Comment by rbharath** [comment]
@marta-sd These tests look great! The grid featurizer has been a weak spot in our testing coverage for quite some time some it's great to see the better coverage in this PR.

The Py2.7 tests are still failing. I've restarted the build to see if they pass. The PR should be good to merge once tests are passing.

**Comment by marta-sd** [comment]
Good to hear that!

The tests have passed, so I guess this part is ready. I'm going to add more tests next week in another PR. Should I use the same name for the follow-up PR, or maybe you use some other naming convention?

**Comment by rbharath** [comment]
@marta-sd Awesome, will go ahead and merge this in then. (Will remove [WIP] from the name first). Feel free to use any name for the follow-up PR. The project is small enough we don't have formal naming schemes :)

LGTM

**Pull request merged**
