### PR TITLE
Remove Jupyter From Install To Make Install Work

### PR DESCRIPTION
**Pull request by lilleswing**
Over the weekend the install started breaking with 
```quote
Traceback (most recent call last):
  File "/media/store/jenkins/workspace/ligand_ml/anaconda/envs/qsar_smash/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/media/store/jenkins/workspace/ligand_ml/anaconda/envs/qsar_smash/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/media/store/jenkins/workspace/ligand_ml/anaconda/envs/qsar_smash/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/media/store/jenkins/workspace/ligand_ml/anaconda/envs/qsar_smash/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/media/store/jenkins/workspace/ligand_ml/anaconda/envs/qsar_smash/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/media/store/jenkins/workspace/ligand_ml/anaconda/envs/qsar_smash/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/media/store/jenkins/workspace/ligand_ml/anaconda/envs/qsar_smash/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 33), (line:1, col:34)
```

The fast AI forums over the weekend blame jupyter.
http://forums.fast.ai/t/salamander-aws-spot-instances-made-easy/21634/39

And indeed removing jupyter from our install fixes the problem.
We can re-add when jupyter fixes their install to work with conda (their official install method :( http://jupyter.org/install).

### CODE REVIEW

**Comment by lilleswing** [comment]
Until this is pushed through no builds will work.

**Comment by lilleswing** [comment]
Looks like the vina website is also down.

**Comment by vsag96** [comment]
Also how do you run tests locally before you open a PR, from the travis logs I have tried the following command,

 `nosetests --with-flaky -a '!slow' --with-timer --with-coverage --cover-package=deepchem -v deepchem --nologcapture`

The tests run but it gets stuck at this testcase 

`Test that VinaPoseGenerator can be initialized. ... ok (0.0001s)`

`Test that VinaPoseGenerator can be initialized. ... failed: Connection timed out.`

`failed: Connection timed out.`

`failed: Connection timed out.`

`failed: Connection timed out.`

I ask this so I won't suffocate the travis build. How important is that the code style follow yapf ==0.20? Can we use a different version say 0.24? sorry if this is out of topic.

**Comment by lilleswing** [comment]
@souravsingh you are doing it correctly.  The reason it is timing out is the vina website is down (which we download autodock vina from).

I added a timeout [here](https://github.com/deepchem/deepchem/pull/1418/commits/e35e9fd3961f8a0ef7b7181db35815be983c92f5) which should cause the test to simply fail instead of breaking all future tests.

**Comment by lilleswing** [comment]
@souravsingh we are currently on yapf==0.22.0

If there are issues we are pretty lenient on upgrading it.
If you wish to upgrade yapf please put in a PR updating .travis.yml and CONTRIBUTING.md with the newest version.

**Comment by vsag96** [comment]
You're tagging some other guy haha I am @vsag96 , Yes I have two PR'S that require review in this repo and once they are done I'll think of submitting this PR if you guys deem it to be necessary. I hope Barath pulls this into master so we can get on with travis builds.

**Comment by lilleswing** [comment]
whoops sorry.  As soon as this gets a green build I'm going to merge this in quickly as it is effective the build system.

**Pull request merged**
