### PR TITLE
Update version of tensorflow

### LINKED ISSUE #1126: TensorFlow 1.6.0 Version Bump
https://github.com/tensorflow/tensorflow/releases/tag/v1.6.0

TensorFlow 1.6 has just been released. We should upgrade the DeepChem HEAD dependency.

### PR DESCRIPTION
**Pull request by souravsingh**
Fixes #1126

### CODE REVIEW

**Comment by souravsingh** [comment]
@rbharath Tests are failing for Python 2.7

**Comment by souravsingh** [comment]
Here is the traceback of the failed test-

```
======================================================================
FAIL: Test tf progressive multitask overfits tiny data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/deepchem/deepchem/deepchem/models/tests/test_overfit.py", line 905, in test_tf_progressive_regression_overfit
    assert scores[metric.name] < .2
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
computed_metrics: [0.16807015205078918, 0.29686734872820497, 0.054055627719767074, 0.31097102912796026, 0.3117397838304099]
```

**Comment by lilleswing** [comment]
Please also update the Readme.md file

**Comment by souravsingh** [comment]
Done

**Comment by lilleswing** [comment]
LGTM

**Pull request merged**
