### PR TITLE
Add Trident Chemwidgets tutorial to `examples/tutorials

### PR DESCRIPTION
**Pull request by TShimko126**
# Add Trident Chemwidgets tutorial to `examples/tutorials`

## Description

This PR adds a Jupyter notebook tutorial describing an example workflow combining DeepChem and [Trident Chemwidgets (TCW)](https://github.com/tridentbio/trident-chemwidgets). TCW is an interactive widget set for generating, plotting, and subsetting molecular datasets that I believe nicely complements the existing functionality of DeepChem. In this tutorial, the user is guided through an example of the molecular ML build and test process using TCW utilities to examine their dataset, test their model, and interpret the predictions. This tutorial builds upon the tutorials [*Introduction to Graph Convolutions*](https://github.com/deepchem/deepchem/blob/master/examples/tutorials/Introduction_to_Graph_Convolutions.ipynb) and [*Calculating Atomic Contributions for Molecules Based on a Graph Convolutional QSAR Model*](https://github.com/deepchem/deepchem/blob/master/examples/tutorials/Atomic_Contributions_for_Molecules.ipynb).

**NOTE:** I have not updated the tutorial `README.md` file, since I am not sure where the new tutorial would best fit. I am happy to make the change based on the opinion of the maintainers.

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [x] Documentations (modification for documents)

## Checklist

**NOTE:** Since this is a notebook tutorial, I believe many of the items below do not apply, but please correct me if I am wrong. 

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by rbharath — COMMENTED** [review]
This is great! Only a couple minor suggested changes

- No need for `pip install tensorflow ~=2.4`. (The website is a little outdated). You can just do `pip install tensorflow`.
- I think this could come in the tutorial series after the atomic contributions tutorial possibly

Will leave this open a few days for further feedback

**Comment by TShimko126** [comment]
Great, thanks for the feedback! I've updated the installation command in `master` and have updated the tutorial README in a separate branch locally: https://github.com/TShimko126/deepchem/blob/tutorial/trident-chemwidgets/examples/tutorials/README.md#molecular-machine-learning

I'll await community feedback, but if the consensus is to keep it in the Molecular Machine Learning section under the [Atomic Contributions for Molecules](https://github.com/TShimko126/deepchem/blob/tutorial/trident-chemwidgets/examples/tutorials/Atomic_Contributions_for_Molecules.ipynb) tutorial, ping me and I can add that commit to this PR.

Thanks again and I look forward to seeing this alongside the other great tutorials here!

**Comment by TShimko126** [comment]
@rbharath: Just wanted to follow up on this PR. I've now included the updated README for the tutorials page, reflecting your suggested numeric ordering. Let me know if you need anything else from my end. Thanks for all your help/work!

**Comment by rbharath** [comment]
Looks good to me! Could you rebase this PR? I think some unrelated changes have crept in the merge. Once rebased it's good to merge I think

**Comment by TShimko126** [comment]
I think the rebase should be all set now, let me know if you need anything else! Thanks for reviewing.

**Review by rbharath — APPROVED** [review]
LGTM!

**Pull request merged**
