### PR TITLE
Adding CI tests for python 3.10

### PR DESCRIPTION
**Pull request by arunppsg**
A summary of changes:

- Added support for python 3.10, removed support for 3.7
- Made 3.8 as main version

### CODE REVIEW

**Comment by Seanny123** [comment]
Is there a reason this is still a draft? Do you need help resolving the failing `doctest`?

**Comment by arunppsg** [comment]
> Is there a reason this is still a draft? Do you need help resolving the failing `doctest`?

When we we made the PR, some of our required dependencies did not support python 3.10 and there were CI failures due to that. I have pushed the changes once again. If the CI passes now, we will merge it in.

**Comment by arunppsg** [comment]
We are having some package conflicts for 3.10 (conflicts [here](https://github.com/deepchem/deepchem/runs/6613218209?check_suite_focus=true#step:10:787)) @Seanny123 . I will try to take a look over the weekend or some time next week and find the root package conflicts from the logs.

**Comment by Seanny123** [comment]
@arunppsg looking at the logs it looks like the problems exist with `rdkit` and `mdtraj` which were both causing me trouble in another project.

`rdkit` specifically looks like it hasn't uploaded Python 3.10 packages to conda despite the being available via [`rdkit-pypi`](https://github.com/kuelumbus/rdkit-pypi). Could you just use the PyPi packages instead of the Conda ones?

**Comment by arunppsg** [comment]
@Seanny123 we were able to fix the conflicts for rdkit and mdtraj by using pip for installation but we have a similar issue of conda conflicts with hhsuite, openmm, pdbfixer packages. I tried installing openmm with python 3.10 in a new conda env but it failed with this error: `  - openmm -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']`. I think pdbfixer should be fixed if we are able to fix openmm (pdbfixer requires openmm as a dependency). For hhsuite, when tried locally, I had the following error during installation.
```
  - hhsuite -> python[version='2.7.*|3.7.*|3.6.*|3.9.*|3.8.*']
  - hhsuite -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']
 ```

**Comment by Seanny123** [comment]
For `hhsuite` you may need to add the `bioconda` channel to `conda`? I looked at the recipe and there doesn't seem to be any version restrictions.

For `openmm`, [this issue](https://github.com/openmm/openmm/issues/3456) seems to imply the Python 3.10 packages are up for all platforms except for Windows, so I'm not sure what's happening there.

**Comment by peastman** [comment]
The conflict descriptions don't make much sense to me.  For example,

```
  pip -> wheelThe following specifications were found to be incompatible with your system:
  
    - feature:/linux-64::__glibc==2.31=0
    - feature:|@/linux-64::__glibc==2.31=0
    - hhsuite -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
    - openmm -> __glibc[version='>=2.17']
    - openmm -> cudatoolkit[version='>=11.2,<12'] -> __glibc[version='>=2.17,<3.0.a0']
    - python=3.10 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  
  Your installed version is: 2.31
```

So you have glibc 2.31, and various packages require it to be >=2.17.  I don't see any conflict there.  And then what's up with this:

```
  Package pypy3.6 conflicts for:
```

It's using Pypy???  I thought this was supposed to be Python 3.10.

Is it possible to run the installation using mamba instead of conda?  It produces much better descriptions of conflicts.

**Comment by arunppsg** [comment]
I updated the deepchem core CI system to use mamba. In [this](https://github.com/deepchem/deepchem/runs/6860385048?check_suite_focus=true#step:11:81) step of ci, it seems that hhsuite is causing a problem in dependency management. On a side note, the test for [a2c.py](https://github.com/deepchem/deepchem/runs/6860384937?check_suite_focus=true#step:12:1330) is failing more often these days.

**Comment by arunppsg** [comment]
> Is this being actively worked on? If not, I'd like to take a look.

Tests in common CI for ubuntu py 3.10 is failing since all dependencies are not supporting python 3.10.

**Comment by chajath** [comment]
I see vina installation is failing because it's trying to build from source, and it can't find boost. Should we install boost-cpp package and try if vina can build it?

**Review by rbharath — APPROVED** [review]
LGTM to merge in once yapf/mypy errors have been fixed

**Pull request merged**
