### PR TITLE
Do not force dtypes to be 'object'

### LINKED ISSUE #2355: dtype of `y` array in `DiskDataset` depends on whether `X` is accessed beforehand
## 🐛 Bug

```
_, datasets, _ = dc.molnet.load_hiv(
    featurizer=dc.feat.RawFeaturizer(smiles=False),
    splitter=None,   # no splitting
    transformers=[]  # no transformation
)
print(datasets[0].y.dtype)
```
outputs
```
object
```

but
```
_, datasets, _ = dc.molnet.load_hiv(
    featurizer=dc.feat.RawFeaturizer(smiles=False),
    splitter=None,   # no splitting
    transformers=[]  # no transformation
)
print(datasets[0].X.dtype)
print(datasets[0].y.dtype)
```
outputs
```
object
float64
```

In the first case `y` has a `dtype` of `object`, but in the second case it has a `dtype` of `float64`

## To Reproduce

See above.

This is for DeepChem version 2.4.0-rc1.dev, installed via pip.

## Expected behavior

The `dtype` to consistently be `float64`

## Environment

* OS: Ubuntu 18.04. LTS
* Python version: 3.8.6
* DeepChem version: 2.4.0-rc1.dev
* RDKit version (optional): 2020.09.3

### PR DESCRIPTION
**Pull request by peastman**
Fixes #2355.

### CODE REVIEW

**Comment by peastman** [comment]
It's getting random failures in flaky tests (`test_mpnn_regression()`, `test_roulette()`).  Is there any way to tell it to rerun just one build instead of rerunning all of them?

We need to do something to make these random failures less frequent.

**Comment by rbharath** [comment]
I'm not sure here.

@nd-02110114 Would you happen to know if there's any way to get github actions to just rerun one build instead of them all?

+1 for figuring out how to make random failures less frequent

**Comment by nd-02110114** [comment]
> Would you happen to know if there's any way to get github actions to just rerun one build instead of them all?

You mean you want to run specific jobs like failed jobs in a previous commit when pushing a new commit...? I don't know whether it is possible to do it.

If you just rerun one of the failed jobs, you go to the page of failed jobs and push the [Re-run jobs] bottom. (The button is in the upper right corner.)

**Comment by nd-02110114** [comment]
You mean you want to rerun only failed steps like [Pytest] or [Doctest]? I think it is impossible.

**Comment by peastman** [comment]
I've rerun the full suite three times now.  I've never gotten a clean run, but it keeps changing what fails.  This time the only failure is `test_mpnn_classification()` in the Ubuntu Python 3.7 build.

> You mean you want to rerun only failed steps like [Pytest] or [Doctest]...? I think it is impossible.

I mean only rerun the Ubuntu Python 3.7 build without also rerunning all the other builds (Ubuntu Python 3.6, Windows Python 3.7, etc.)

**Comment by nd-02110114** [comment]
> I mean only rerun the Ubuntu Python 3.7 build without also rerunning all the other builds (Ubuntu Python 3.6, Windows Python 3.7, etc.)

It is impossible... Many people needs it...
https://github.community/t/ability-to-rerun-just-a-single-job-in-a-workflow/17234

**Comment by rbharath** [comment]
Should we go ahead and merge in? We're seeing one test failure on ubuntu, python 3.7 but I think that's a flaky test

**Comment by peastman** [comment]
Let's do that.  I'll see if I can make some of the flaky tests a little less flaky in a separate PR.

**Pull request merged**
