### PR TITLE
Support Python 3

### PR DESCRIPTION
**Pull request by peastman**
I also fixed some bugs in the process.

I discussed this with @rbharath and we agreed to do the conversion in the way that would produce the cleanest, simplest Python 3 code, even if that means it's now less efficient under Python 2 than it used to be.  For example, I just replaced `xrange` (which returns an iterator, but only exists in Python 2) with `range` (which returns a list in Python 2 but an iterator in Python 3).  Consider this an incentive to switch to Python 3. :)

### CODE REVIEW

**Comment by rbharath** [comment]
@peastman Thanks for doing this! Looked through the changes and everything looks good so far (thanks for the bugfixes in a few of the tests along the way).

**Comment by peastman** [comment]
It looks like the travis builds stalled and then timed out.  Could you try restarting them?  Or add me to the project so it will let me do it.

**Comment by rbharath** [comment]
@peastman Just added you as a member to `deepchem` organization. I believe that should let you restart the travis build once you accept invite

**Comment by peastman** [comment]
I accepted the invitation, but it still isn't giving me the option to restart builds.  Possibly it just takes time for the information to propagate to travis?

**Comment by rbharath** [comment]
@peastman Just restarted build. Hopefully will solve whatever issue we ran into previously with the stalled build.

**Comment by peastman** [comment]
It stalled again at the same place.  Here's the end of the log.  It's the same for both Python 2 and 3.

```
$ nosetests -v deepchem --nologcapture

Using TensorFlow backend.

Test that ordering of labels is consistent over time. ... /home/travis/build/deepchem/deepchem/deepchem/datasets/__init__.py:959: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

  if y[ind, task] == "":

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

So the very first test produces no output for ten minutes and gets killed.  Any idea what could be causing that?

**Comment by rbharath** [comment]
@peastman Hmm, no, that test is usually innocuous. As a debugging aid, could you try deactivating the python 3.5 in the travis.yml file. Let's see if the stall is happening because of parallel running of both python versions (Tensorflow has the unfortunate property of setting up global variables. My first guess is that both versions launched in parallel and tensorflow choked somehow).

**Comment by peastman** [comment]
That isn't how travis works.  Every build is done in its own VM, so there's no interaction between them.

**Comment by rbharath** [comment]
Ah I see, that's good to know :-). Quite honestly, this type of stall is new to me.

The failing test lives in `datasets/tests/test_datasets.py`. Maybe we can try commenting out all the tests in that file, pushing again to the PR, seeing if the tests run successfully? Then we'd know if it's something particular about that test as opposed to the others.

**Comment by peastman** [comment]
Done.  It's rerunning them now.

**Comment by peastman** [comment]
Well, it's producing output now.  More specifically, it printing out an error message thousands of times:

```
$ nosetests -v deepchem --nologcapture

Using TensorFlow backend.

Test on dataset where RDKit fails on some strings. ... [00:14:51] Can't kekulize mol 

[00:14:51] Can't kekulize mol 

[00:14:51] Can't kekulize mol 

[00:14:51] Can't kekulize mol 

[00:14:51] Can't kekulize mol 

[00:14:51] Can't kekulize mol 
...
```

**Comment by rbharath** [comment]
@peastman That's an interesting clue! That test purposefully invokes itself on a few molecules where rdkit fails (so there should be something like 5 messages). The fact that we're seeing thousands of print statements suggests that the test in question is somehow being invoked repeatedly (in some type of infinite loop perhaps). Has anything changed which could possibly cause this?

**Comment by peastman** [comment]
Not that I know of...  And when I run the tests locally it doesn't do that.  It's only on travis.

**Comment by rbharath** [comment]
@peastman Could it have something to do with the change in the iterators? That's the only change I spot that looks like it could trigger an infinite loop. I'll check out a copy locally later today or tomorrow and see if I get errors similar to travis...

**Comment by peastman** [comment]
I don't see any way that would do that.

**Comment by rbharath** [comment]
@peastman In a bit of good news, I'm able to duplicate the travis failure on my local setup. I will poke at this tomorrow and see if I can debug the issue. I should also be in the office tomorrow from lunch onwards, so we can debug together if the issue proves too thorny.

**Comment by rbharath** [comment]
@peastman I think I might have unraveled the issue. It has to do with a subtle difference between `itertools.izip` in python 2 and `zip` in python 3. I used `izip` on an infinite generator and a finite one, and it defaulted to stopping once the finite generator ran out. `zip` doesn't seem to do this correctly. Not sure I understand the whole issue tbh. In any case, replacing the lines

```
data_iterator = it.izip(
    it.repeat((self, shard_size, input_type, data_dir)),
    enumerate(load_data(input_files, shard_size, self.verbosity)))
```
in `deepchem/featurizers/featurize.py` (roughly line 170 IIRC) with
```
def wrap_with_shard_metadata(iterator):
  for item in iterator:
    yield ((self, shard_size, input_type, data_dir), item)
data_iterator = wrap_with_shard_metadata(
    enumerate(load_data(input_files, shard_size, self.verbosity)))
```
makes the tests pass for me locally. Could you replace this and see if the tests pass for you now?

**Comment by peastman** [comment]
Done.  Let's see what happens...

**Comment by peastman** [comment]
Everything passed!  Now we just need to figure out the earlier hang.  Shall I try reenabling the tests in test_datasets.py and see if that works too now?  Or do you want to see if you can reproduce that one locally?

**Comment by rbharath** [comment]
@peastman Yay! I re-enabled the tests in `test_datasets.py` locally, and everything passes for me with the fix. Can you go ahead and re-enable the tests? I think everything should pass on travis after that.

**Comment by peastman** [comment]
Cross your fingers.

**Comment by rbharath** [comment]
Looks like all tests pass! Are we good to go ahead and merge in?

**Comment by peastman** [comment]
I think so.  Let's go for it!

**Comment by rbharath** [comment]
@peastman Just realized that the `.travis.yml` file explicitly downloads Anaconda for python2 and adds it to the path, so I think this PR actually still runs both tests with python 2.... Some edits need to be done to the `.travis.yml` file to figure out the right way to enable python 3 tests...

**Comment by rbharath** [comment]
Started debugging in #241

**Comment by rbharath** [comment]
Merged in #241, so I think the issue is fixed. Verified that travis is running python 3 tests with latest fix.

**Pull request merged**
