### PR TITLE
refactor importing soft dependent package

### PR DESCRIPTION
**Pull request by nd-02110114**
## Problem

Currently, the soft dependent packages are imported in methods.
This may lead to poor performance because methods import packages whenever they call (importing packages is slow).

## What I did

The soft dependent packages are imported just once by using try/catch.
This implementation is used by DGL and PyTorch Geometric.

https://github.com/rusty1s/pytorch_geometric/blob/5eb3ebd1a91746808d06544b56208f7d2a035449/torch_geometric/datasets/qm9.py#L10-L20

https://github.com/dmlc/dgl/blob/828a5e5bc6ffaa5716b02283874ec830e1b786fc/python/dgl/data/chem/utils/featurizers.py#L9-L13

### CODE REVIEW

**Comment by peastman** [comment]
>  This may lead to poor performance because methods import packages whenever they call (importing packages is slow).

I don't think that's correct.  If a module has already been loaded, importing it again does nothing more than add its name to the local namespace.  See https://stackoverflow.com/questions/296036/does-python-optimize-modules-when-they-are-imported-multiple-times.

**Comment by nd-02110114** [comment]
Thanks! I learned a lot from your comment. I knew that module importing is optimized like singleton for the first time. But, I find the following statement. 
https://wiki.python.org/moin/PythonSpeed/PerformanceTips#Import_Statement_Overhead

> import statements can be executed just about anywhere. It's often useful to place them inside functions to restrict their visibility and/or reduce initial startup time. Although Python's interpreter is optimized to not import the same module multiple times, repeatedly executing an import statement can seriously affect performance in some circumstances.

So, I check some cases by writing codes.

```
import time

print('import rdkit 100000 times')
start = time.time()
for i in range(100000):
    import rdkit
elapsed_time = time.time() - start
print("elapsed_time:{0}".format(elapsed_time) + "[sec]")

print('import rdkit 1 times')
start = time.time()
import rdkit
elapsed_time = time.time() - start
print("elapsed_time:{0}".format(elapsed_time) + "[sec]")

print('import tf 100000 times')
for i in range(100000):
    import tensorflow
elapsed_time = time.time() - start
print("elapsed_time:{0}".format(elapsed_time) + "[sec]")

print('import tf 1 times')
start = time.time()
import tensorflow
elapsed_time = time.time() - start
print("elapsed_time:{0}".format(elapsed_time) + "[sec]")
```

The result

```
import rdkit 100000 times
elapsed_time:0.04829001426696777[sec]
import rdkit 1 times
elapsed_time:9.5367431640625e-07[sec]
import tf 100000 times
elapsed_time:5.043965101242065[sec]
import tf 1 times
elapsed_time:2.1457672119140625e-06[sec]
```
I seem rdkit case is basically no problem but tensorflow case is a little problem.
So, I think my codes are better compared with current codes.

**Comment by peastman** [comment]
A disadvantage is that users get less helpful error messages.  For example, if RDKit isn't installed but the user calls a function that requires it, they'll currently get the message

```
ModuleNotFoundError: No module named 'rdkit'
```

It's pretty clear what that means and what you need to do to fix it (install RDKit).  With this change, they would instead get the message

```
NameError: name 'Chem' is not defined
```

That's a lot less clear.

**Comment by rbharath** [comment]
One possibility is we could wrap all function definitions which depend on rdkit within a try/catch block. That way if rdkit isn't imported then the functions themselves won't be exposed. This might be a lot of work, but could perhaps clean up the API for users who have installations without rdkit

**Comment by peastman** [comment]
That would just produce a different unintuitive error: it would say a method didn't exist even though the API documentation claims it should.

I don't think it solves any real problem.  The time to re-import a package is negligible.  There's a mistake in the benchmark above: it doesn't import tensorflow and rdkit once before starting.  When it says it takes 5 seconds to import tensorflow 100,000 times, that really means it takes about 5 seconds to import it once, then a fraction of a second to import it another 99,999 times.

**Comment by nd-02110114** [comment]
> One possibility is we could wrap all function definitions which depend on rdkit within a try/catch block
> That would just produce a different unintuitive error: it would say a method didn't exist even though the API documentation claims it should.

I agree with peastman's opinion. I think wrapping all function definitions is not good solution.

> The time to re-import a package is negligible. There's a mistake in the benchmark above: it doesn't import tensorflow and rdkit once before starting. When it says it takes 5 seconds to import tensorflow 100,000 times, that really means it takes about 5 seconds to import it once, then a fraction of a second to import it another 99,999 times.

I'm so sorry for the trouble. This is a my mistake 🙇  I totally agree with your opinion.

So, I close this PR.

**Pull request closed without merging**
