### PR TITLE
[WIP] Porting One-shot models to TensorGraph

### PR DESCRIPTION
**Pull request by rbharath**
This PR works on porting one-shot models into `TensorGraph`. More details as these models mature.

### CODE REVIEW

**Comment by rbharath** [comment]
@maclandrol Unfortunately not at present. I'd be glad to provide feedback to anyone interested in taking it on though

**Comment by zas97** [comment]
Any update on the pull request? Can the code in this pull request be used with the current version of deepchem?

**Comment by rbharath** [comment]
Unfortunately no progress. We do have a new API for low data learning (see https://github.com/deepchem/deepchem/pull/1636) that I'd recommend if you're looking to get started.

**Comment by zas97** [comment]
Okey, no problem, I'm gonna use an old version of deepchem. Could you tell me which was the latest version of deepchem where the one shot learning worked?

PS: Thank you for all the work in deepchem, its amazing!

**Comment by rbharath** [comment]
I think DeepChem 1.3 should work with it, but you might have to go back to DeepChem 1.0.

Part of the challenge in porting has been that the original implementation used a lot of custom code to create batches for training. I don't think it would be that hard to port over to the new Keras style, but I just haven't had the bandwidth to take it on recently.

**Comment by rbharath** [comment]
Closing this old PR since we don't currently have plans to port the old one-shot models into Keras.

**Comment by danielvlla** [comment]
@rbharath I am trying to replicate results from Low Data Drug Discovery with One-shot Learning. However the Python scripts in examples/low-data are not working for me. Can you propose a recommended way forward please?

**Comment by rbharath** [comment]
@danielvlla Unfortunately those models are quite out of date! It's on my TODO-list to port them into Keras, but I haven't had the bandwidth to do so yet. If you're interested, I'm glad to work with you to port them into Keras and contribute them back into DeepChem!

**Comment by lol88** [comment]
I went through the codes in "Low Data Drug Discovery with One-Shot Learning". Here I have some specific questions. You might help me figure them out.

`ValueError: in converted code:
    relative to /home/lvqj/Meta-Learning/deepchem-master/deepchem/models:

    keras_model.py:487 apply_gradient_for_batch  *
        batch_loss = loss(outputs, labels, weights)
    keras_model.py:1235 __call__  *
        raise ValueError(

    ValueError: Loss functions expects exactly one each of outputs, labels, and weights`

**Pull request closed without merging**
