### PR TITLE
Fix docs errors and Update type annotation

### PR DESCRIPTION
**Pull request by nd-02110114**

### CODE REVIEW

**Comment by peastman** [comment]
Looks good.  I guess there's no way to tell mypy that the return type of `compute_model_performance()` depends on the value of `per_task_metrics`?

**Comment by nd-02110114** [comment]
> I guess there's no way to tell mypy that the return type of compute_model_performance() depends on the value of per_task_metrics?

If we add type annotation of `Metrics` methods (This is because `compute_model_performance` depends on `Metrics` methods), mypy might infer different type based on the value of per_task_metrics. But, basically, I couldn't resolve this problem. Type cast is workaround, and I think this is not good...

**Comment by rbharath** [comment]
Thanks for the cleanup! This looks good. Going to go ahead and merge in

**Comment by peastman** [comment]
I think this is exactly what we want:

https://mypy.readthedocs.io/en/stable/literal_types.html

**Pull request merged**
