### PR TITLE
OSX Travis

### PR DESCRIPTION
**Pull request by lilleswing**

### CODE REVIEW

**Comment by lilleswing** [comment]
https://github.com/travis-ci/travis-ci/issues/6825

It supposedly can be done but hackily until this issue is fixed.

**Comment by peastman** [comment]
We've been using travis to test OpenMM on OS X for ages.  As far as I can tell, we aren't having to do anything to work around lack of python support.

https://github.com/pandegroup/openmm/blob/master/.travis.yml

**Comment by lilleswing** [comment]
@peastman you switch the "language" for the osx builds.  
Its OK because you install python manually.

I followed the example and I *think* my matrix build should work.

**Comment by lilleswing** [comment]
So now it runs -- but it takes 30 minutes on the OSX VM to just install deepchem.  Apparently the OSX vms only have 1 VCPU and 3GB of ram...

**Comment by lilleswing** [comment]
Yeah I don't know if we are going to be able to do this.  I tried installing deepchem-deps as a single package to make it faster and it was still a no-go.

We would have to have a separate smaller test set for OSX.  

Or we could randomize which tests we run on each travis build.

**Comment by rbharath** [comment]
Would running a random subset for OSX only work?

**Comment by peastman** [comment]
Are you sure that's the problem?  From the travis logs, it looks like almost everything worked on Python 3.5.  There were just a couple of tests that failed.  On Python 2.7 it successfully installed, but then hung while running tests.  The job eventually got killed when no output had been produced for ten minutes.

**Pull request closed without merging**
