### PR TITLE
Updated tutorial on reinforcement learning

### PR DESCRIPTION
**Pull request by peastman**
This PR gets the code working with the latest DeepChem, expands the text a bit, and moves it to the proper place in the sequence.

### CODE REVIEW

**Comment by peastman** [comment]
The test failures are unrelated to this PR.  It looks like something got merged that created failures in `test_graph_data()` and `test_tokenize()`?

**Comment by StashOfCode** [comment]
@peastman , looks like their CI is broken. I also got failing tests, despite changing only one function name

**Comment by peastman** [comment]
I tried to reproduce the failures locally.   test_graph_data.py is passing for me.  test_smiles_tokenizer.py fails with this error:

> OSError: Model name 'seyonec/SMILES_tokenized_PubChem_shard00_50k' was not found in model name list (roberta-base, roberta-large, roberta-large-mnli). We assumed 'seyonec/SMILES_tokenized_PubChem_shard00_50k' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

cc @seyonechithrananda

**Comment by seyonechithrananda** [comment]
@peastman I may know whats going on, I'll make some revisions to the script tomorrow which should resolve this issue. #2302 will address the change, sorry about that!

**Comment by rbharath** [comment]
I really like the PR @peastman! Feel free to merge this in when ready (since the test failures are unrelated in any case)

**Pull request merged**
