### PR TITLE
Deep Tensor Neural Networks for QM series

### PR DESCRIPTION
**Pull request by miaecle**
This PR adds in a new model:  [Deep Tensor Neural Net](https://arxiv.org/abs/1609.08259 )
The model is based on the structure of sequential graph, still under refinement(mae reported for qm7&qm9 less than 1kcal/mol). Be aware this model use a new function from tensorflow 1.0, may not be able to merge in until dependency is satisfied

preliminary result:
QM7, R2, mae(kcal/mol)
train, 0.9988394, 5.64
valid, 0.9983496, 6.09

### CODE REVIEW

**Comment by rbharath** [comment]
@miaecle This is very cool! Would you mind adding some docs about the basic structure of the model and an overfit test?

**Comment by rbharath** [comment]
@miaecle Now that DeepChem has been upgraded to Tensorflow 1.0, we should be able to merge this PR in once ready.

**Comment by miaecle** [comment]
@rbharath Sweet! Should be done by the middle of this week.

**Comment by miaecle** [comment]
@rbharath model and example codes are ready now, planning to add in benchmark performances in a separate PR(still on hyperparameter search)

**Comment by rbharath** [comment]
@miaecle Awesome thanks for getting this done quickly :+1:. Will go ahead and merge this PR in.

**Pull request merged**
