### PR TITLE
Adding to_csv method to DiskDataset

### PR DESCRIPTION
**Pull request by arunppsg**
Fix for #3006 

In this PR, I have added a `to_csv` method which creates a dataframe from a `Dataset` object via the following steps:
1. Iterate through the shards
2. Create dataframe for each shard
3. Append the dataframe to the csv file.

The method accepts path to the csv file as an argument and it returns None.

### CODE REVIEW

**Comment by arunppsg** [comment]
@rbharath I considered having `to_csv` as a staticmethod but it did not make much sense to me. The reason for not having is staticmethod is because `to_csv` operates on the instance's data and not on any static properties of the class.

**Comment by peastman** [comment]
It looks like this assumes the `x` and `y` values for each sample are either scalars or 1D arrays.  What happens if they're higher dimensional?  For example, what if `x` is a 2D image for each sample?  And more important, what *should* happen in that case?

Similarly, what if they're objects such as GraphData?  Should we try to write them out in some format that can be reconstructed again?  Or throw an exception saying they can't be written to csv?

**Comment by arunppsg** [comment]
I think to begin with, we can fail loudly - check whether the input data is writable, if not raise an assertion error that `to_csv` method is only valid for cases were X is a scalar or a 1-D array.

**Comment by peastman** [comment]
That sounds good.

**Review by rbharath — APPROVED** [review]
LGTM! Will leave open in case @peastman wants to review

**Comment by peastman** [comment]
Looks good to me.

**Pull request merged**
