### PR TITLE
mpnn

### PR DESCRIPTION
**Pull request by patrickhop**
baseline for message passing nn in pytorch

### CODE REVIEW

**Comment by rbharath** [comment]
@patrickhop This looks awesome! I think it'll be a nice resource for others interested in digging into mpnns.

Will merge in once Travis finishes running (will ignore `yapf` errors per `Contrib/` policy).

**Comment by patrickhop** [comment]
Thanks! I'll try my best to keep pushing this forward.

**Comment by patrickhop** [comment]
travis failed. @rbharath is this my fault?

**Comment by rbharath** [comment]
@patrickhop Looks like just `yapf` errors. (We need to figure out how to turn off `yapf` for `Contrib/`...).

LGTM.

**Pull request merged**
