### PR TITLE
Explaining Tox21 with LIME

### PR DESCRIPTION
**Pull request by lilleswing**
https://github.com/lilleswing/deepchem/blob/lime/examples/notebooks/Explaining_Tox21.ipynb

This tutorial goes through and uses LIME to explain why a molecule is considered toxic for NR-AR.

So I don't think this is ready to go into examples yet, I think it needs a domain expert to go through the fragments suggested in the example and give comments about them.  Does the domain expert agree with the fragments?  Does the domain expert believe that there is a collision of toxic and non toxic fragments in the same fingerprint bucket?

I'm hoping a domain expert sees this tutorial PR and wants to run it over a Dataset they have intimate knowledge about.

### CODE REVIEW

**Comment by lilleswing** [comment]
A Schrodinger Scientist
"""
it is a cell-based high throughput assay. 
looks like most of the fragment are hydrophobic,  some are reactive 
which make sense for toxicity
I believe medicine chemists will agree with the fragment 
that discovered by the model
"""

**Comment by rbharath** [comment]
@lilleswing Wow!! This is probably the coolest DeepChem tutorial I've seen added so far. Having a feature like this will help us a ton trying to win adoption and mindshare from drug discovery scientists.

Everything looks good on my end. Feel free to merge in once you feel confident with domain expert feedback.

**Comment by miaecle** [comment]
@lilleswing Thanks for putting this out! This is fantastic, interpretability is one of the hardest problem we have on the graphconv models, so glad to see we have some tools to step further.

**Comment by lilleswing** [comment]
Yeah it doesn't work on GraphConv yet :smile: , only on fixed length feature vector models.  I believe we can also get it to work on TextCNN (although I haven't tried) as there is support for natural language and we can model characters as works.  

The math works I believe to run the algorithms over our Graph Models but it would be a non-trivial implementation.  This is because LIME calculates probability distribution of each feature by it's index, and that doesn't work out of the box with a variable number of atoms where atom ordering is not important.  Also getting meaning out of an adjacency matrix would be difficult.

**Comment by lilleswing** [comment]
Ugh I accidently deleted the branch

**Pull request closed without merging**
