### PR TITLE
Pypi upload

### PR DESCRIPTION
**Pull request by lilleswing**
Upload to pypi on successful travis builds

### CODE REVIEW

**Comment by rbharath** [comment]
@lilleswing Awesome! Does this get us pip installs?

LGTM

**Comment by lilleswing** [comment]
Pip installs without dependencies

**Comment by rbharath** [comment]
Cool. So `pip install deepchem` now works?

**Comment by lilleswing** [comment]
I believe that command will install the latest successful master build
without any of the dependencies.  (I have to double check though what the
default no arg version of pip install is)

**Comment by lilleswing** [comment]
You could check via —

‘’’ bash
pip install deepchem
pip freeze | grep deepchem
‘’’

**Pull request merged**
