### PR TITLE
Fix L1 and L2Loss

### PR DESCRIPTION
**Pull request by proteneer**
Adresses #936

### CODE REVIEW

**Comment by peastman** [comment]
I'm a bit uneasy about this change.  Technically speaking, you're right: l1 and l2 norm are defined by the sum, not the mean.  On the other hand, for most situations it doesn't really matter which one you use, but changing it will break existing code.  For example, multiplying the loss by a constant often requires changing the learning rate.  And if you're adding multiple loss terms together, you can't just change one of them while leaving the others alone.

So I'd prefer to leave the code as is, and just clearly document the behavior.  We could also add a constructor argument that tells it whether to use the mean or the sum (defaulting to mean for backward compatibility).

**Comment by rbharath** [comment]
Agree with @peastman here. This would be a major breaking change. Adding in docs or flags would be a good backwards compatible step.

**Comment by proteneer** [comment]
As an additional note, this actually doesn't reduce over the batch. It reduces over all the other dimensions. I presume the other dimensions are typically for multi-tasking?

**Comment by rbharath** [comment]
I'm going to close this old PR since we're not planning on merging it in.

**Pull request closed without merging**
