### PR TITLE
Added option for checkpoint interval

### PR DESCRIPTION
**Pull request by peastman**
See #458.

### CODE REVIEW

**Comment by peastman** [comment]
`test_format_code` is complaining about formatting in one file, even though I ran `yapf` on that file and it changed lots of things in it.  Any idea what's up with that?

**Comment by lilleswing** [comment]
```
diff --git a/deepchem/models/tensorflow_models/__init__.py b/deepchem/models/tensorflow_models/__init__.py
index 62650e8..a66b899 100644
--- a/deepchem/models/tensorflow_models/__init__.py
+++ b/deepchem/models/tensorflow_models/__init__.py
@@ -360,8 +360,8 @@ class TensorflowGraphModel(Model):
           if epoch % checkpoint_interval == checkpoint_interval - 1:
             saver.save(sess, self._save_path, global_step=epoch)
           avg_loss = float(avg_loss) / n_batches
-          log('Ending epoch %d: Average loss %g' %
-              (epoch, avg_loss), self.verbose)
+          log('Ending epoch %d: Average loss %g' % (epoch, avg_loss),
+              self.verbose)
         # Always save a final checkpoint when complete.
         saver.save(sess, self._save_path, global_step=epoch + 1)
     ############################################################## TIMING
```

Did you run yapf from git root?  This is what I am getting (the same that travis is getting).

**Comment by peastman** [comment]
Yes.  Take a look at the diff.  You'll see it made lots of other changes in that same file.

**Comment by rbharath** [comment]
@peastman Yapf sometimes messes up on challenging syntax. Try rejiggering the string a bit (maybe breaking it up onto a separate line). Worst case, I'd recommend just manually making the change locally...

**Comment by rbharath** [comment]
@peastman LGTM!

**Pull request merged**
