### PR TITLE
RNN in Deepchem

### PR DESCRIPTION
**Pull request by alat-rights**
# RNN in Deepchem (Not Ready for Review Yet)

## Description

Part of #2230 

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by alat-rights** [comment]
As a quick note, this is still entirely a draft. I will update this PR when I make some progress.

**Comment by peastman** [comment]
I'm confused.  This looks like a CNN, not a RNN?

**Comment by alat-rights** [comment]
Hi Peter! This is not ready for review just yet. I'm basing the code on CNN.py so I'm going through and changing things.

**Comment by nd-02110114** [comment]
> This is not ready for review just yet.

I recommend you avoid making really early stage PRs. (Especially, the case that PR is not ready for review)
There are two reasons. First, maintainers are sometimes confused. Second, your CI tasks may block CI jobs of other important PRs because the test time is so long.

**Comment by alat-rights** [comment]
Hi @nd-02110114 ! I see, sorry about that. I will close this PR for now and reopen it when I’ve made more progress!

**Pull request closed without merging**
