### PR TITLE
DiskDataset caches shards in memory

### LINKED ISSUE #1855: Optimizing loading datasets
As part of my efforts to improve the speed of GraphConvModel, I've been profiling some of our example scripts.  I discovered that nearly half the time is actually spent loading shards, not in anything to do with the model.  I'd like to see if we can improve this.

One obvious solution is to cache shards in memory rather than reloading them every time.  DiskDataset is designed to let you work with datasets that are too big to fit in memory.  But in practice a lot of datasets are quite small and could easily fit in memory.  The challenge, though, is figuring out how much we can safely cache.  It's too bad Python doesn't support soft references, since they'd be perfect for this.  Any thoughts about this?

Digging a little deeper, I see that almost all the loading time is actually spent in numpy_pickle.py.  We store shards in `.joblib` files, which store data in pickled format.  Pickling is really slow.  Would it be possible to switch to `.npy` files instead?  I haven't tested yet, but I suspect that would be a lot faster.  What was the reason for choosing this format?

### PR DESCRIPTION
**Pull request by peastman**
Fixes #1855.

Python doesn't seem to provide any good mechanism for dynamically adjusting the size of the cache without creating a risk that some other part of the program will run out of memory.  So instead I just have each DiskDataset use a fixed amount of memory for its cache.  I made it default to 20 MB, which is large enough to be useful but small enough that it's unlikely to cause problems, even if you have several datasets in memory at once.  You can change it by setting the `memory_cache_size` property.  For large datasets, increasing the size could improve performance a lot.

One idea I've been thinking about is to have all the splitters and molnet loaders increase the cache size for the training set, maybe to 50 MB?  Since you normally make more passes through the training set than the validation or test set, it makes sense to let it use a bit more memory than the others.

### CODE REVIEW

**Comment by peastman** [comment]
I'm not sure how to handle the test failures.  The error happens inside `save_dataset_to_disk()` which, contrary to the name, doesn't actually save the datasets to disk.  It assumes they already exist as DiskDatasets, and all it does is move their files to a new location.  But it also does one other thing: it saves a pickled copy of all the transformers to a file called transformers.pkl.  But what if one of them is a BalancingTransformer?  That includes its own reference to a dataset that it uses for balancing.  Which means the pkl file includes a complete pickled copy of that dataset, including all its internal fields.

I'm pretty sure this behavior is wrong, and my change is just revealing the existing wrong behavior.  It means that when you reload the datasets, you get the standard train, validate, and test datasets loaded correctly.  But then you *also* get another copy of the training dataset stored inside the BalancingTransformer.  Only that other copy probably can't actually be loaded, because it references the wrong directory on disk.

My belief is that transformers shouldn't actually be storing a reference to a dataset.  All transformers actually have that ability, since it's defined by the base Transformer class.  But as far as I can tell, BalancingTransformer is the only one that ever uses that dataset.  And the only place it uses it outside the constructor is for a single call to `get_task_names()`.  And even there it doesn't actually care what the task names are, just how many tasks there are.  And it could learn that just as easily by looking at the shape of `y`.

**Comment by rbharath** [comment]
Good points here. I agree that transformers shouldn't reference a dataset. I think we should remove the reference to the training dataset from `BalancingTransformer`. This original behavior was broken and we should fix it.

Should we also rename `save_dataset_to_disk()` while we're at it? I'm going to write up utilities docs that publicly expose utilities so seems a good time to fix naming before the docs go up.

**Comment by peastman** [comment]
Renaming it might be a good idea, though I'm not sure of what name would make sense.  It does more than just moving files, but less than saving datasets.  Anyway, I think that's outside the scope of this PR.  Let's see if the tests pass with this change.

**Comment by peastman** [comment]
I think everything passed?  Two of the three builds report success.  The third one reports failure, but looking through the log I don't see any tests listed as having failed.

**Comment by rbharath** [comment]
It looks to have coredumped on `nosetests` with Python 3.7:
```
(core dumped) nosetests -q --with-flaky -a '!slow' --with-coverage --cover-package=deepchem -v deepchem --nologcapture
```
Could you try restarting the build (I don't see the button for this anymore, so this might require pushing a dummy commit) to check this is a transient failure?

**Comment by peastman** [comment]
Restarted.  I'm not sure what's going on with the permissions.  A while ago travis stopped being able to push results back to github.  I did something that I didn't entirely understand and it started working again, but it seems to have left you without full administration access for the travis builds.

**Comment by peastman** [comment]
All tests passed.

**Comment by peastman** [comment]
This should be ready to merge, if it looks ok to you.

**Comment by rbharath** [comment]
This change looks really good! I'm hoping the in-memory caching will give deepchem a nice performance boost.

**Pull request merged**
