### PR TITLE
Corrected Test Case for Smiles Tokenizer (adding to #2572)

### PR DESCRIPTION
**Pull request by seyonechithrananda**
#2572 corrects the smiles-tokenizer test-case (given the change in the regex pattern) which @niklashoelter found. This PR is just a brief follow-up to add yapf formatting so the CI will pass.

@rbharath @niklashoelter

### CODE REVIEW

**Comment by seyonechithrananda** [comment]
It seems like the only failed test now is relating to a regression overfit test (not the tokenizer), so perhaps we can merge this in? @rbharath 

Summary:
```
FAILED deepchem/models/tests/test_overfit.py::test_fittransform_regression_overfit
= 1 failed, 654 passed, 7 skipped, 104 deselected, 714 warnings in 1495.41s (0:24:55) =
Error: Process completed with exit code 1.

```

Specific error:
```
deepchem\models\tests\test_overfit.py:232: AssertionError
============================== warnings summary ===============================
c:\miniconda3\envs\deepchem\lib\site-packages\tensorflow\python\autograph\impl\api.py:22
  c:\miniconda3\envs\deepchem\lib\site-packages\tensorflow\python\autograph\impl\api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

```

**Comment by VIGNESHinZONE** [comment]
Could you also add a `@pytest.mark.torch ` around the test similar to this [here](https://github.com/VIGNESHinZONE/deepchem/blob/0dbc240a0c330b2b0980325ffe68a82a57befb8a/deepchem/feat/tests/test_smiles_tokenizer.py#L19)
and `transformers` requirement in `requirements/torch/env_torch.yml` [here](https://github.com/VIGNESHinZONE/deepchem/blob/0dbc240a0c330b2b0980325ffe68a82a57befb8a/requirements/torch/env_torch.yml#L11)

**Comment by rbharath** [comment]
@seyonechithrananda Thank you for the fix! Can you make the modifications @VIGNESHinZONE is suggesting and we can go ahead and merge this in?

**Comment by seyonechithrananda** [comment]
> @seyonechithrananda Thank you for the fix! Can you make the modifications @VIGNESHinZONE is suggesting and we can go ahead and merge this in?

Done!

**Comment by seyonechithrananda** [comment]
> Could you also add a `@pytest.mark.torch ` around the test similar to this [here](https://github.com/VIGNESHinZONE/deepchem/blob/0dbc240a0c330b2b0980325ffe68a82a57befb8a/deepchem/feat/tests/test_smiles_tokenizer.py#L19)
> and `transformers` requirement in `requirements/torch/env_torch.yml` [here](https://github.com/VIGNESHinZONE/deepchem/blob/0dbc240a0c330b2b0980325ffe68a82a57befb8a/requirements/torch/env_torch.yml#L11)

Good catch - will do! thanks :)

**Comment by VIGNESHinZONE** [comment]
Could you also add `import pytest`

**Comment by rbharath** [comment]
Failures look to be unrelated to this fix so going to merge in. Thanks for the fix!

**Pull request merged**
