### PR TITLE
Fix directed acyclic graph network bug

### PR DESCRIPTION
**Pull request by hsjang001205**
fix bug in save/load.
fix DAG, DAGGather layer variable are treated as constants.

https://github.com/deepchem/deepchem/issues/2226#issue-722956730

### CODE REVIEW

**Comment by hsjang001205** [comment]
caution about **The command "bash devtools/run_yapf.sh" exited with 1.**

test_DAG_regression_reload passed.

**Comment by rbharath** [comment]
@hsjang001205 This is awesome debugging! I want to review this more carefully, but I'm excited :). I was beating my head against this failure and not making headway. I'll do a more careful review pass tomorrow to make sure I understand your fix

**Comment by hsjang001205** [comment]
@rbharath After defining layer and building it, you can get a variable with layers.get_weights().

layer = layers.DAGLayer()   #define
output = layer(inputs)        #build
print(layer.get_weights())    #get variable list

Original version return []. because of it was treated as just constant. 
Original model may have only trained the last dense layer.

+Same bug occurs in weaver.

**Comment by hsjang001205** [comment]
The Travis CI build failed with the probability factor of TestSplitter class method.

**Review by rbharath — APPROVED** [review]
This is a great fix! If I understand it, the Ws/bs were not being added as weights so the reload failed. Thanks for figuring this one out :)

**Pull request merged**
