### PR TITLE
Add core and pocket options to PDBBind Molnet loader

### PR DESCRIPTION
**Pull request by ncfrey**
## Description

While testing some complex featurizers, I found it useful to add two new options to the PDBBind loader:
* Added the "core" subset of 195 highest quality protein-ligand complexes that are used for benchmarking docking methods. This dataset is much better suited for experimentation, compared to the other two sets that contain thousands of complexes.
* Added the option to featurize only the binding pocket rather than the entire protein, which significantly speeds up featurization and lowers memory requirements.

## Type of change

Please check the option that is related to your PR.

- [X] New feature (non-breaking change which adds functionality)

CCing @rbharath and @peastman

### CODE REVIEW

**Review by rbharath — APPROVED** [review]
This is great! Will make benchmarking much easier :). Looks good to merge on my end

**Comment by ncfrey** [comment]
Looks better now!

**Comment by ncfrey** [comment]
Tests are passing so I'm going to merge this in to use in the AtomicConv tutorial.

**Comment by LivC182** [comment]
@ncfrey how do you define the binding pocket and how do you find it ? I cannot find the function that does that.

**Pull request merged**
