### PR TITLE
Atomic convolutional networks and scripts

### PR DESCRIPTION
**Pull request by joegomes**
This PR adds:

- A top-level `contrib/` folder
- Atomic convolutional networks for protein-ligand binding.  https://arxiv.org/abs/1703.10603
- Scripts used for featurization, dataset splitting, and model fitting.

These models currently work with older `TensorflowGraphModel` base classes.  I've included legacy classes so users should still be able to run example scripts.

### CODE REVIEW

**Comment by rbharath** [comment]
@joegomes Awesome, thanks for getting this in.

**Comment by proteneer** [comment]
great stuff - reading the paper now :)

**Comment by rbharath** [comment]
This is failing `yapf`, but I'm OK with merging in as-is. (I think we shouldn't enforce `yapf` on `Contrib/` since we want to lower the barrier to contribution for new users).

**Comment by rbharath** [comment]
LGTM.

**Pull request merged**
