### PR TITLE
add logger instead of print statements

### PR DESCRIPTION
**Pull request by nitinprakash96**
This patch is a work in progress. I just wanted to see the travis behavior after making changes that will follow throughout the source code.

### CODE REVIEW

**Comment by nitinprakash96** [comment]
Looks like the Patch does it's job except for the files I modified the changes and stupidly forgot to make some minors. The travis log looks good to me though.

**Comment by nitinprakash96** [comment]
https://travis-ci.org/deepchem/deepchem/jobs/345593118#L3994

can you take a look at and tell me what is actually causing this test to fail?

**Comment by leeyjjoel** [comment]
Hey @nitinprakash96,

Based on your travis log as shown below, one error could be that your code doesn't adhere to the style guidelines. Perhaps you could install yapf (the code formatter) and run it on the relevant directories that you edited to ensure that they adhere to the style guide. This can be done by running yapf -ir <directory>. Hope this helps!

```
Failing Formatting Test
Please run yapf over the files changed
pip install yapf
yapf -i
```

Joel

**Comment by nitinprakash96** [comment]
Hi @leeyjjoel I'm not really sure. Because when I test the formatting locally, it passes without any error.

**Comment by rbharath** [comment]
@nitinprakash96 Try checking that your version of `yapf` matches DeepChem's version (iirc, we're at 20.0). There are often mismatches between various versions of the tool.

**Comment by nitinprakash96** [comment]
I had to run `yapf` manually to fix all the formatting errors. That did it. Thanks @leeyjjoel 
But apparently, the error is occurring at https://travis-ci.org/deepchem/deepchem/jobs/345736555#L3955 imo. Could you please guide me into that problem? @rbharath

**Comment by rbharath** [comment]
It looks like the docstring test is failing. The test suite runs example code in docstrings to make sure examples run. Was anything modified in that docstring?

**Comment by nitinprakash96** [comment]
No really, I tried running the docstring locally on jupyter, turns out that it runs just fine. I get the number of features just as expected. :(

**Comment by rbharath** [comment]
I'm a little puzzled especially since the changes to `fcnet` (https://github.com/deepchem/deepchem/pull/1113/files#diff-dfe21b68affbe3e4edc7ecec83986574) appear to be innocuous.

@lilleswing, @peastman Do either of you have thoughts into what might be going on here?

**Comment by lilleswing** [comment]
Since we are no longer printing to stdout the doc test is now failing.  

The doctest is checking that stdout=='n_features after fit_transform: 12", which is no longer the case.

We should add another line
```python
model.n_features
```
Which should return 12 to stdout.

**Comment by lilleswing** [comment]
@nitinprakash96 I attempted to fix the test on the branch.

**Comment by nitinprakash96** [comment]
@lilleswing thanks a lot for helping me out on that point. Doctests had me stuck.

**Comment by lilleswing** [comment]
somehow the numpy format for __repr__ is different between 2.7 and 3.5.  Will fix.

**Comment by lilleswing** [comment]
Green and merging.  Congradulations @nitinprakash96 on your first PR! :100:

**Comment by nitinprakash96** [comment]
Is this supposed to be a temporary fix @lilleswing ? I don't understand why we should stop checking for python 2. Can you please guide me here. :)

**Comment by lilleswing** [comment]
It is just the docstring tests  -- we are still running the rest of the tests.  The docstring tests can't be stable because of small differences in the default representation of lists of floats.  

Python 2.7 only has 9 more months of full support so we will also be stopping support for it soon.
https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst

I made the call that running doctests on python 2 is no longer needed.  If other people disagree with me please voice your objections.
@peastman @rbharath @miaecle

**Comment by rbharath** [comment]
@nitinprakash96 Congrats on your first merged PR!

**Pull request merged**
