### PR TITLE
Port of NeighborList from Keras to Torch

### PR DESCRIPTION
**Pull request by subzjee**
# Pull Request Template

## Description

#2930 
Ported NeighborList to Torch.

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [X] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [X] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [X] Run `mypy -p deepchem` and check no errors
  - [X] Run `flake8 <modified file> --count` and check no errors
  - [X] Run `python -m doctest <modified file>` and check no errors
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New unit tests pass locally with my changes
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rbharath** [comment]
Thanks for the contribution! I took a quick look and it seems reasonable. I've turned on the CI run (github disables for first time contributors), so we can see if there are any test failures we need to look at.

**Comment by subzjee** [comment]
Some checks are failing but those seem to be unrelated.

**Comment by subzjee** [comment]
Per the feedback by @shivance on the other PRs, I imported the layer in the module.

**Review by arunppsg — APPROVED** [review]

**Comment by arunppsg** [comment]
LGTM! Thanks for the contribution.1

**Pull request merged**
