### PR TITLE
Lazy Import xgboost

### PR DESCRIPTION
**Pull request by lilleswing**
Create a file for lazy importing non critical dependencies.

If attempted to use one of these dependencies when not installed the system will throw a runtime error instead of a startup error.

### CODE REVIEW

**Comment by lilleswing** [comment]
@rbharath I'm not sure how to test failing an import other than not installing it.  I don't think its something easily mocked.

**Comment by rbharath** [comment]
@lilleswing Awesome! We might want to move Tensorflow in here as well in a future PR. @XericZephyr has reported that Tensorflow is hard to install on many older academic clusters (issues we've faced ourselves honestly), so it would be nice to let users of older systems use the tensorflow-free parts.

**Comment by XericZephyr** [comment]
Awsome! Nice work!

**Comment by jstaker7** [comment]
Just pulled from master. Looks like this has recently been broken:

>>> import deepchem

Warning: No XGBOOST installed on your system
Attempting to run models with XGBOOST dependencies will throw runtime errors
/Users/staker/anaconda/envs/my-rdkit-env/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/staker/anaconda/envs/my-rdkit-env/lib/python3.5/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/staker/Projects/external/deepchem/deepchem/__init__.py", line 18, in <module>
    import deepchem.molnet
  File "/Users/staker/Projects/external/deepchem/deepchem/molnet/__init__.py", line 28, in <module>
    from deepchem.molnet.run_benchmark import run_benchmark
  File "/Users/staker/Projects/external/deepchem/deepchem/molnet/run_benchmark.py", line 17, in <module>
    from deepchem.molnet.run_benchmark_models import benchmark_classification, benchmark_regression
  File "/Users/staker/Projects/external/deepchem/deepchem/molnet/run_benchmark_models.py", line 15, in <module>
    import xgboost
ImportError: No module named 'xgboost'

**Comment by lilleswing** [comment]
https://github.com/deepchem/deepchem/pull/533

**Pull request merged**
