### PR TITLE
Fix weave featurizer for chirality

### LINKED ISSUE #1716: use_chirality in WeaveFeaturizer
System:

- DeepChem Version: 2.3.0 (built from source with GPU support)
- Platform: Linux Fedora 30 

WeaveFeaturizer does not seem to work when setting ```use_chirality=True```:

```
...
~/anaconda3/envs/deepchem_gpu/lib/python3.5/site-packages/deepchem/feat/graph_features.py in _featurize(self, mol)
    436         canon_adj_list,
    437         bt_len=6,
--> 438         graph_distance=self.graph_distance)
    439 
    440     return WeaveMol(nodes, pairs)

~/anaconda3/envs/deepchem_gpu/lib/python3.5/site-packages/deepchem/feat/graph_features.py in pair_features(mol, edge_list, canon_adj_list, bt_len, graph_distance)
    230       # first `bt_len` features are bond features(if applicable)
    231       features[a1, a2, :bt_len] = np.asarray(
--> 232           edge_list[tuple(sorted((a1, a2)))], dtype=float)
    233     for ring in rings:
    234       if a1 in ring:

ValueError: could not broadcast input array from shape (10) into shape (6)
```

The ```bt_len``` variable in line 437 in graph_features.py appears to be hard-coded as 6. A small work-around that worked for me was adding the following code to ```def _featurize(self, mol)``` of the ```WeaveFeaturizer``` class in graph_features.py:
```
    if self.use_chirality:
        bt_len_var = 10
    else:
        bt_len_var = 6
```
line 437: ``` bt_len=bt_len_var```

Best regards,
J.

### PR DESCRIPTION
**Pull request by VIGS25**
Fixes #1716 

Didn't hardcode it, so that this part doesnt get affected by addition of more bond features.

### CODE REVIEW

**Comment by rbharath** [comment]
Since the tests are in a bad state right now, it's a little hard to unpack, but I think we have a relevant test failure in `test_weave_regression_model`. Could you try running `nosetests` locally and verifying tests are passing for you until we get travis back online?

**Comment by VIGS25** [comment]
Sorry, this ones on me. On a related note, should we be featurizing molecules that have no bonds? - The test failure seems to correspond to that.

**Comment by rbharath** [comment]
Hmm, good question. In theory, I guess we could featurize something like a noble gas that would be a single atom without bonds. This might be useful for people doing ML on inorganic chemistry perhaps. If it's hard to do correctly though, I'm pretty open to just adding an error that fails loudly on molecules without bonds.

**Comment by VIGS25** [comment]
It might be harder to do if one didnt want to hardcode the number of features, but if we ever change the number of bond features, then the value would need to be updated. I have also fixed the issue with the `DataLoader` tests.

**Comment by rbharath** [comment]
Wow, Python 3.7 is green! Yay, that's the first green travis build I've seen for a bit. I think the dataloader fixes did the trick.

Thanks for the PR :). Going to merge in!

**Pull request merged**
