### PR TITLE
Changed return type to np.ndarray in a few files

### PR DESCRIPTION
**Pull request by atreyamaj**
# Pull Request Template

## Description

Fix #(issue)

## Type of change

Please check the option that is related to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by vsomnath** [comment]
Looks good to me!

**Review by rbharath — COMMENTED** [review]
Sorry might have missed this discussion. Are we seeing errors in mypy elsewhere that mean we need this fix?

**Comment by vsomnath** [comment]
I am not sure about the errors, but `np.array` is a function and `np.ndarray` is the actual type of the numpy array.

**Review by rbharath — APPROVED** [review]
Ah that makes sense! Ok marking this one ready to merge in

**Comment by vsomnath** [comment]
There are some formatting issues here.

**Comment by atreyamaj** [comment]
> There are some formatting issues here.

I've run yapf on the file again. The change seems unrelated to the code but hopefully it'll pass the CI now.

**Comment by vsomnath** [comment]
It's passing now but on GitHub Actions, yapf is only run on the files that were changed
```
Run CHANGED_FILES=`git diff --name-only $COMMIT_RANGE | grep .py$ | grep -v contrib/ || true`
```

**Comment by rbharath** [comment]
Test failures look unrelated to so going to go ahead and merge in

**Pull request merged**
