### PR TITLE
Use queue to improve efficiency during training

### LINKED ISSUE #429: Use Tensorflow queues?
This blog post claims that using feed-dicts instead of tensorflow queues can signficantly hurt GPU utilization:

https://blog.metaflow.fr/tensorflow-how-to-optimise-your-input-pipeline-with-queues-and-multi-threading-e7c3874157e0#.1ovwdpqjl

It would be great to investigate whether switching to using queues can increase our GPU utilization. @proteneer noted previously that the one-shot models had mediocre utilization numbers for example.

### PR DESCRIPTION
**Pull request by peastman**
Fixes #429.  So far I've implemented this in TensorflowGraphModel and its subclasses.  Anyone who wants to try it on your own datasets, I'd like to hear how it works.  First, though, make sure you're using a sufficiently large batch size (see #468).  This optimization assumes the GPU is spending a lot of time waiting for the CPU.  If it isn't you won't see much benefit.

### CODE REVIEW

**Comment by evanfeinberg** [comment]
Very cool, thank you @peastman. I've been reading quite a bit about how
transition from feed_dict to queue offers significant speedups so I'm
looking forward to trying this out.

**Comment by rbharath** [comment]
Based on offline discussion, this PR should be ready to merge in once tests pass.

**Comment by peastman** [comment]
Travis reports `test_reload.py` is failing on Python 2 but passing on Python 3.  When I run it locally, it passes on both Python 2 and 3.  Any idea what's going on?

**Comment by rbharath** [comment]
Hmm, I've noticed some weirdness like this before. I've restarted the build in hopes it will go away naturally :)

**Comment by peastman** [comment]
Looks like it passed this time.  Is there something non-deterministic in that test?

**Comment by rbharath** [comment]
I believe it's one of the overfit tests. Checks that trivial datasets (~10 datapoints) can be learned with a little bit of training. I think it might be some weirdness with lapack/blas or something. I've noticed that the overfit tests fail at random on some machines at times...

**Pull request merged**
