### PR TITLE
#1142: make_estimator TextCNN - Minor additions

### PR DESCRIPTION
**Pull request by VIGS25**
A couple of additions to the previously merged PR:
1. Removed `tf.cast` from  DTNNEmbedding and moved it to `create_estimator_inputs`
2. Added `smiles_to_seq` inside `input_fn` definition
3. Added a fix for failing tests in `Python 2.7`

### CODE REVIEW

**Comment by VIGS25** [comment]
Test failure was an unrelated stochastic one.

**Comment by rbharath** [comment]
LGTM

**Comment by peastman** [comment]
I just noticed that this PR imports `six` at the top level, which turns it into a hard dependency.  We just went to a lot of work to get rid of hard dependencies, including six.    It should be imported only inside the function where it's used.  But in this case, there's no reason to use it at all.  You're just using it to check for Python 2, which can be done just as easily by checking `sys.version_info[0]`.

**Comment by VIGS25** [comment]
Okay! I'll be mindful of this in future code changes. Will raise a new PR in a while with this fixed.

**Pull request merged**
