### PR TITLE
In response to #1442 (Data Augmentation Support)

### PR DESCRIPTION
**Pull request by Dyex719**
Added augmentation techniques like cropping, convert image to grayscale and salt and pepper noise.

### CODE REVIEW

**Comment by rbharath** [comment]
@Dyex719 This looks great! I have a couple requests and this code should be good to merge in afterwards:

-) Could you add some unit tests for the new transforms?
-) Can you run yapf on the code to fix formatting? You can install yapf with `pip install yapf` and format with `yapf -i filename.py` where `filename.py` is the modified file.

**Comment by ac-optimus** [comment]
hi, @rbharath @Dyex719 can I continue from here if no one is working on this currently?
Thanks!

**Comment by Dyex719** [comment]
Please go ahead.

**Comment by rbharath** [comment]
@ac-optimus I'm going to close this old PR since there are some merge conflicts here. Please do send in a fresh PR once you're done :)

**Comment by ac-optimus** [comment]
> @ac-optimus I'm going to close this old PR since there are some merge conflicts here. Please do send in a fresh PR once you're done :)

@rbharath  ya sure, in middle of my mid semesters, will do it once my exams get over!

**Comment by TaranSinghania** [comment]
Hi,
@ac-optimus @Dyex719 @rbharath Can I work on this if no one is currently doing so?

**Comment by rbharath** [comment]
Sounds good on my end! I'd recommend opening a new issue discussing the new data augmentation methods you're thinking of adding.

**Pull request closed without merging**
