### PR TITLE
Added SMILES tokenization section to tutorial

### PR DESCRIPTION
**Pull request by frenio**
## Description

Not a fix! I added a new section "SMILES Tokenization and Numericalization" to the "Going Deeper on Molecular Featurizations" tutorial. 

The new section contains a step-by-step guide on the pre-processing of SMILES data for sequence models. It also demonstrates how these steps can be combined in a custom `Featurizer` class that can be used with `dc.molnet`'s load functions to load tokenized and numericalized SMILES data.

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [x] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project (https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [ ] Run `mypy -p deepchem` and check no errors n/a
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by rbharath — APPROVED** [review]
LGTM

**Comment by zhouhong369** [comment]
Every time I run to this step：tasks, datasets, transformers = dc.molnet.load_tox21(featurizer=smiles_featurizer)
print(datasets[0].X)This error will occur：OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect. : 'C:\\Users\\hp\\AppData\\Local\\Temp\\tox21-featurized\\SmilesFeaturizer_feat_func_<function tokenize_smiles at 0x00000195972599D0>_max_len_240'，I'm confused and don't know how to modify it

**Comment by frenio** [comment]
Hi @zhouhong369,

Thank you for reading the tutorials and for pointing out this problem! I authored this section on a Unix machine where "<" and ">" in system paths are allowed characters. You seem to be running the notebook on a Windows machine where this doesn't seem to be the case. Here are two possible fixes:

1. Run the notebook in Google Colab. Colab runs on Linux and therefore should not have this problem.
2. Add a `__str__` method to the SmilesFeaturizer to change how the featurizer is represented in the file path. When the dataset is created, the `dc.molnet._MolnetLoader` uses `str(featurizer)` on the featurizer that is passed to it. By default that outputs `SmilesFeaturizer_feat_func_<function tokenize_smiles at 0x00000195972599D0>` and seems to cause your problem. The following code makes it output `SmilesFeaturizer` which hopefully solves your problem.

```python
class SmilesFeaturizer(dc.feat.Featurizer):
    def __init__(self, feat_func, vocab, max_len):
        self.feat_func = feat_func
        self.vocab = vocab
        self.max_len = max_len
        
    def _featurize(self, x):
        return self.feat_func(x, self.vocab, self.max_len)

    def __str__(self):
        return "SmilesFeaturizer"
```

If you try the 2nd fix and it works for you, please let me know so I can update the tutorial to include that method.

Hope this helps and let me know if you have any other questions.

Best,
Frenio

**Comment by zhouhong369** [comment]
Dear Frenio,
I apologize for the delay in my response. I followed your guidance and I am using Windows 10. After implementing the suggested changes, I replaced the original code as follows:class SmilesFeaturizer(dc.feat.Featurizer):    def __init__(self, feat_func, vocab, max_len):        self.feat_func = feat_func        self.vocab = vocab        self.max_len = max_len        def _featurize(self, x):        return self.feat_func(x, self.vocab, self.max_len)
    def __str__(self):        return "SmilesFeaturizer"
smiles_featurizer = SmilesFeaturizer(tokenize_smiles, vocab, max_len)After making this change, the previous error no longer occurred. I sincerely appreciate your help with this issue!
Wishing you all the best.
Kind regards,Zhou Hong----- 原始邮件 -----
发件人：Frenio Redeker ***@***.***>
收件人：deepchem/deepchem ***@***.***>
抄送人：zhouhong369 ***@***.***>,  Mention ***@***.***>
主题：Re: [deepchem/deepchem] Added SMILES tokenization section to tutorial (PR #4056)
日期：2024年10月01日 03点17分


Hi @zhouhong369,
Thank you for reading the tutorials and for pointing out this problem! I authored this section on a Unix machine where "<" and ">" in system paths are allowed characters. You seem to be running the notebook on a Windows machine where this doesn't seem to be the case. Here are two possible fixes:

Run the notebook in Google Colab. Colab runs on Linux and therefore should not have this problem.
Add a __str__ method to the SmilesFeaturizer to change how the featurizer is represented in the file path. When the dataset is created, the dc.molnet._MolnetLoader uses str(featurizer) on the featurizer that is passed to it. By default that outputs SmilesFeaturizer_feat_func_<function tokenize_smiles at 0x00000195972599D0> and seems to cause your problem. The following code makes it output SmilesFeaturizer which hopefully solves your problem.

class SmilesFeaturizer(dc.feat.Featurizer):
    def __init__(self, feat_func, vocab, max_len):
        self.feat_func = feat_func
        self.vocab = vocab
        self.max_len = max_len
        
    def _featurize(self, x):
        return self.feat_func(x, self.vocab, self.max_len)

    def __str__(self):
        return "SmilesFeaturizer"
If you try the 2nd fix and it works for you, please let me know so I can update the tutorial to include that method.
Hope this helps and let me know if you have any other questions.
Best,

Frenio

**Pull request merged**
