### PR TITLE
Created new MAML API 

### LINKED ISSUE #1572: MAML and architecture changes
I'm trying to figure out how to keep MAML (model agnostic metalearning) working with all the architectural changes we're making.  My changes in #1567 have broken it.  I've verified that this is caused by the change to keras layers.  Simply changing one line to replace `tf.layers.Dense` with `tf.keras.layers.Dense` causes it to stop working.

 MAML is an unusual algorithm.  Most models are defined by a series of layers, with each layer defining both a set of variables and a calculation to do.  You might call the layer several times with different inputs, but it always applies the came calculation with the same variables to them.

MAML is different.  You need to apply the model several times using the *same* inputs but *different* variables.  Except sometimes they aren't really variables.  They're the output of a calculation, which you need the layer to use in its calculation where it would normally use variables.  Standard layer classes just aren't written to work that way.

I solved this problem by using the `tf.contrib.graph_editor` module.  You define a model using layers, and it builds a graph from them in the normal way.  Then it clones pieces of the graph, replacing the variables with the outputs of calculations.  This works nicely but has several problems.

First, it apparently doesn't work with keras layers.  I don't know why.  I could try to figure out what they're doing differently that interferes with the graph editor.  Possibly I could get it working again.  But there are other serious problems that will also need to be dealt with very soon.

The second problem is that this approach can never work in eager mode.  It's inherently graph based.  Given that TensorFlow is moving to eager mode as the default approach for everything, that's not very satisfactory.

But a much bigger problem is that `tf.contrib.graph_editor` is going away in TensorFlow 2.  As far as I can tell, it isn't being migrated to its own project or anything like that.  It's just being abandoned and there will no longer be any supported way of doing this sort of graph manipulation.

I've tried to think of an alternate API that could be supported with TensorFlow 2, but I haven't found anything satisfactory.  This algorithm requires you to separate the definition of the variables from the definition of the computation.  You need to define the model using functions of the form `f(inputs, variables)`, where the algorithm can pass in arbitrary tensors to use as the variables.  That isn't how keras layers work, which means you wouldn't be able to use layers in defining your model.

I'm kind of stuck on this.  Any suggestions about what to do?

### PR DESCRIPTION
**Pull request by peastman**
Fixes #1572

### CODE REVIEW

**Comment by peastman** [comment]
I'm kind of puzzled by the test failure.  On travis, it consistently passes on Python 3.5 and consistently fails on Python 2.7.  But on my computer it consistently passes on Python 2.7.  Anyone have any ideas?

**Comment by zas97** [comment]
No, sorry. I said that it was failing in python 2.7 because I can see it in travis-ci from github. Otherwise I just downloaded the code of your pull request and it works fine in python 3.

**Comment by rbharath** [comment]
I checked out the branch on my machine (which has python 3.6) and I'm seeing tests pass. I'd be fine if we went ahead and merged in. Python 2.7 support is on the way out in any case...

**Comment by peastman** [comment]
Ok, I'll go ahead and merge this.  If we're really dropping Python 2.7 support, we should consider updating the versions tested on travis.

**Pull request merged**
