### PR TITLE
Update TensorflowModel classes to TF 0.12

### PR DESCRIPTION
**Pull request by joegomes**
This PR contains:
- A fix for model restoring from checkpoint file.  TF 0.12 introduces a new checkpoint file system which reduces latency and memory usage.  The new checkpoint file naming convention broke the existing checkpoint loader.  This PR contains a fix to `_find_last_checkpoint()` for correctly locating the checkpoint file.
- A fix for deprecated TF functions used in deepchem.  TF 0.12 has deprecated the use of `tf.initialize_all_variables()` and `tf.op_scope()`.  This PR replaces these functions with `tf.global_variables_initializer()` and `tf.name_scope()`.

Note that this PR will break backwards compatibility with TF 0.11 and lower.

### CODE REVIEW

**Comment by rbharath** [comment]
@joegomes To summarize our offline conversation, we can't merge in this PR since our main GPU clusters all don't yet support TF 0.12. Will keep this PR open so TF 0.12 users have a fix, and once we figure out how to upgrade our GPU clusters, will merge this in.

**Comment by proteneer** [comment]
Ha - I literally ran into this bug 20 minutes ago. thanks for the PR! I'll be cherry picking this...

**Comment by proteneer** [comment]
It's a slight but not major pain in the ass to rebase this off of master periodically - but is there a timeline for the switch to 0.12?

**Comment by rbharath** [comment]
@proteneer I'm hoping I can figure this out within a week or so. #293, and #314, #315 are probably higher on my debugging docket, but this one should come right after.

**Comment by rbharath** [comment]
@joegomes  Good find that our clusters have now upgraded to TF 0.12 :+1:. 

Could you take a quick look at this PR to get tests passing? I think the fix is to update `.travis.yml` to install the most recent Tensorflow version from Conda. The lines for this are already in HEAD `.travis.yml`. You should be able to just uncomment those lines and comment the current conda install command for Tensorflow.

**Comment by proteneer** [comment]
+1000

**Comment by joegomes** [comment]
Closing this to open a clean PR.

**Pull request closed without merging**
