### PR TITLE
Port of CombineMeanStd from Keras to Torch

### PR DESCRIPTION
**Pull request by subzjee**
# Pull Request Template

## Description

#2930
Ported CombineMeanStd to Torch.

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [X] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [X] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.32.0**)
  - [X] Run `mypy -p deepchem` and check no errors
  - [X] Run `flake8 <modified file> --count` and check no errors
  - [X] Run `python -m doctest <modified file>` and check no errors
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New unit tests pass locally with my changes
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by subzjee** [comment]
Some checks are failing but seem to be unrelated to this.

**Comment by shivance** [comment]
It's a great start ! Couple of comments left..

**Comment by shivance** [comment]
Please add imports in [this](https://github.com/deepchem/deepchem/blob/master/deepchem/models/torch_models/__init__.py) file

**Comment by shivance** [comment]
Why is Torch build in CI breaking because of a Tensorflow import? Are we using any piece of deepchem imports in the code, which depends on Tensorflow?

**Comment by subzjee** [comment]
I added the import.

It doesn't seem to be failing because of TensorFlow.
Importing `SklearnModel` eventually imports `pinv2`, which has been [deprecated](https://docs.scipy.org/doc/scipy/release.1.7.0.html?highlight=pinv2#scipy-linalg-deprecations) since 1.7.0 and [removed](https://docs.scipy.org/doc/scipy/release.1.9.0.html?highlight=pinv2#expired-deprecations) since 1.9.0

**Comment by arunppsg** [comment]
> It doesn't seem to be failing because of TensorFlow. Importing `SklearnModel` eventually imports `pinv2`, which has been [deprecated](https://docs.scipy.org/doc/scipy/release.1.7.0.html?highlight=pinv2#scipy-linalg-deprecations) since 1.7.0 and [removed](https://docs.scipy.org/doc/scipy/release.1.9.0.html?highlight=pinv2#expired-deprecations) since 1.9.0 This seems to be in `sklearn` itself.

This failure in CI can also be ignored for now.
> The other failure is due to an `AssertionError` in `dc.models.tests.test_cnn.TestCNN::test_residual_cnn_classification`.

This is a flaky failure. So we can ignore it.

LGTM!

**Review by arunppsg — APPROVED** [review]

**Pull request merged**
