### PR TITLE
Introduce datasetify utility

### PR DESCRIPTION
**Pull request by rbharath**
This is a utility that attempts to convert its input into a dataset. With `datasetify`, it becomes possible for classes such as Splitters and Transformers which operate on datasets to attempt to operate on more general input.

@peastman I've found this really convenient when coding, but downside might be that the type gets gnarly

### CODE REVIEW

**Comment by peastman** [comment]
Could you give some examples of what this is used for?  I think I'm missing something.  When is it easier to write `datasetify((X, y))` than `NumpyDataset(X, y)`?

**Comment by rbharath** [comment]
Ah yes, will do. One request that popped up on the gitter was whether it would be possible to use deepchem Splitters/Transformers without having to use Dataset objects. For example to make something like the following work
```
splitter = ScaffoldSplitter()
train, val, test splitter.train_valid_test_split(["C", "CC", "CO", ...])
```
The `datasetify` utility facilitates these types of conveniences. The idea is that at the top of the splitter methods, you'd have a call
```
dataset = datasetify(input)
```
where `input` is currently required to be a `Dataset` but can now be a dataset-like object as recognized by `datasetify`.

**Comment by peastman** [comment]
I'm not sure it's really worth it to avoid having to write

```python
mols = ["C", "CC", "CO", ...]
dataset = NumpyDataset(mols)
```
The user will still have to work with Dataset objects, since that's how the result will come back.  Also there are many ambiguous cases that could lead to misinterpretation.  For example, what if someone writes

```python
datasetify(((1, 2, 3), (4, 5, 6), (7, 8, 9)))
```

Is that a 3x3 matrix being passed for X?  Or is it three vectors being passed for X, y, and w?  As written, it would assume the latter.  If you wanted the former you would have to instead write

```python
datasetify(np.array(((1, 2, 3), (4, 5, 6), (7, 8, 9))))
```

And then again if you wrote

```python
datasetify([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

it would throw an exception and say it couldn't convert it.  This seems likely to create confusion.

**Comment by rbharath** [comment]
Hmmm, good points there. Perhaps this is more trouble than it's worth for the minor ergonomic improvement. I'll close this PR

**Pull request closed without merging**
