### PR TITLE
Trying to transmit deepchem dataset type to tensorflow data type

### PR DESCRIPTION
**Pull request by lqiqiqi**
Hi, Sir. I am QI LUO, a senior student interested in participating in Google Summer of Code 2019. I have seen you have a project to transmit deepchem dataset type to tensorflow data type, mentored by Mr. Karl Leswing, so I just make a try to build a new method to do this work, a little start. Maybe my idea is something wrong or not the best, but I am willing to make changes and learn something new. Thank you very much!!

### CODE REVIEW

**Comment by peastman** [comment]
`Dataset` already has a `make_iterator()` method, which I think does basically the same thing as this?  See https://github.com/deepchem/deepchem/blob/master/deepchem/data/datasets.py#L268-L309.  Does this class do anything different?

**Comment by lqiqiqi** [comment]
yes, it seems they serve the same function. I am confused about the project **Data Interface** (attached below) and do you have any advice on it? 

[GSoC project 2019](http://wiki.openchemistry.org/GSoC_Ideas_2019#DeepChem_Project_Ideas)

**Comment by rbharath** [comment]
@lqiqiqi The project descriptions are a little out of date. I recommend taking a look through the open DeepChem issues to see if any of them look interesting to you. There are some good research projects suggested in there. Also, feel free to ping me on gitter once you have an idea for a potential project

**Comment by rbharath** [comment]
@lqiqiqi I'm cleaning up old pull requests so I'm going to close this PR. If you're still interested in contributing, let me know and I'll re-open the PR!

**Pull request closed without merging**
