### PR TITLE
DeepChem 2.5.0 Release PR

### PR DESCRIPTION
**Pull request by rbharath**
# Pull Request Template

Release PR for DeepChem 2.4.0

## Description

Follows release notes and bumps version for release. Once this PR is merged in, I'll tag 2.5.0 as a release.

@nissy-dev Could you take a look?

CC @ncfrey @peastman @seyonechithrananda 

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rbharath** [comment]
I'm going to freeze merging in other PRs till we get the release code, so my apologies to any folks who are waiting on merges! We should hopefully have the release finished within the next day or two

**Review by nissy-dev — CHANGES_REQUESTED** [review]
Basically, looks good to me!
Although the note doesn't mention, we should change Dockerfile.

This line shpuld be changed to 

```
pip install tensorflow~=2.4 deepchem && \
```

https://github.com/deepchem/deepchem/blob/7ed0125d9ad26cc4cbf31fbe8f67c195448c71db/docker/tag/Dockerfile#L21

**Comment by rbharath** [comment]
@nissy-dev Thanks for the review! Could you take another look? I think I've addressed the issues you raised

**Review by nissy-dev — APPROVED** [review]

**Comment by nissy-dev** [comment]
@rbharath this pr looks good. Free to merge!

**Comment by rbharath** [comment]
Great thanks! Went ahead and merged and made the tag for 2.5.0. A few more steps left until release is done...

**Pull request merged**
