### PR TITLE
Cell Membrane Permeability Dataset

### PR DESCRIPTION
**Pull request by lilleswing**
RRCK permeability dataset. This set contains permeability data and structures for 201 compounds curated from 8 sources using the RRCK (aka MDCK-LE) permeability assay. The dataset has been used to train a 3D physics-based permeability model as referenced in http://doi.org/10.1021/acs.jcim.6b00005. 

P.S.
Looks like we're using the 3d coordinates here. Just like ESOL, permeability should be based on the compound not conformer, but the conformational ensemble highly affects the permeability (solubility as well). Existing predictors of permeability and solubility both require sampling of the 3d structures.

### CODE REVIEW

**Comment by lilleswing** [comment]
[results.txt](https://github.com/deepchem/deepchem/files/987744/results.txt)

**Comment by rbharath** [comment]
Looks good. Glad to merge in once tests pass. (One of the finicky tests is failing, but just restarted that job in hopes it will start working. We should try to make the tests more robust though).

It's interesting the graph-convolution does poorly here though. Would be curious to see what's going on here in more depth.

**Comment by lilleswing** [comment]
@rbharath this also pins the pandas version.  All travis tests will fail until that is done.

Dataset Size is much smaller (only 201 points).  10 epochs might not be enough, we would have to graph validation r^2 as a function of epochs, and I would run it all the way to 50.

**Comment by rbharath** [comment]
LGTM.

**Pull request merged**
