### PR TITLE
[WIP] Chemberta tutorial updates 

### PR DESCRIPTION
**Pull request by seyonechithrananda**
Adding in the ChemBERTa-PubChem 10M model with the MolNet dataloder from bert-loves-chemistry, as well as the Smiles Tokenizer model which uses the DeepChem tokenizers API. 

@rbharath @gabegrand

### CODE REVIEW

**Review by rbharath — APPROVED** [review]
The new tutorial is looking really nice! I love the fine-tuning section :)

I'll mark this as approved. Feel free to merge once ready

**Comment by seyonechithrananda** [comment]
Thanks, I'll add in the secondary tutorial for Smiles Tokenizer and then merge (its a two part tutorial, only difference is we use a diff model + tokenizer).

**Comment by peastman** [comment]
I have a few general suggestions.  This reads more like a paper than a tutorial.  The introduction lists off past work and says what new things you're proposing.  And it assumes the reader is already familiar with transfer learning, attention, BERT, etc.  For a tutorial, we should assume the reader is new to DeepChem, and may be new to deep learning in general.  We can't assume they know anything except what has been specifically introduced by earlier tutorials in the sequence.  The goal of each tutorial is to introduce a handful of new concepts and demonstrate how to do something useful.

Along the same lines, you have big blocks of code without explanation.  For example, you import the apex and transformers libraries without ever having introduced them or said what they do.  You call some functions from them without explaining what those functions do or why you're calling them.  It produces some output that you don't explain.  You just declare, "Here, we get some interesting results," and immediately dive into another big block of code that isn't explained.  Have mercy on your poor readers! :)

One other change that would help readability: you have hundreds of lines of output from git and pip that account for roughly half the length of the tutorial.  It would be better to remove that.  You can include the cells with the commands to install everything, but don't actually execute them.  Have everything installed in advance so the user won't have to scroll through long stretches of uninformative output.

**Comment by seyonechithrananda** [comment]
@peastman thanks for the really great, detailed feedback! I added a lot more on apex + mixed-precision, smiles-tokenizer vs bpe, and cleared the cell output for the tedious install code. Let me know what you think of the changes! 😀

**Comment by peastman** [comment]
That's a big improvement!  It does a much better job of explaining the code.  Except for the discussion of tokenizers, though, it still doesn't explain any of the concepts.  You need to assume the reader doesn't know what any of the following mean:

- Transfer learning.  This is *really* important to explain thoroughly, since it's the main subject of the tutorial!
- NLP.  The first time this appears, just change it to "natural language processing (NLP)" so they know what it stands for.
- Attention.  This is also important to explain, given that you spend a lot of time on visualizing attention in the model.
- Transformer.  You don't need to explain the whole architecture, but at least give a few sentences explaining what it's used for and the basic principles behind it.
- BERT.  A single sentence would be fine for this, such as, "BERT is a very powerful model for natural language processing, which is based on the Transformer architecture."
- RoBERTa.  I don't know what this one is!
- ChemBERTa.  Again a single sentence would be fine.  "ChemBERTa adapts the BERT model to chemistry by processing SMILES strings the same way BERT processes English text."

Why are there two different, largely identical, notebooks?

**Comment by seyonechithrananda** [comment]
Thanks for the feedback, I will add these changes over the weekend! @peastman 

With regards to the two tutorials, they utilize different tokenizers and such the attention visualization + predictions will be different. I would usually try to collate them into one, a large notebook, but the only issue is with Bertviz we've run into some issues with Colab where running two attention-head visualizations means the second one will not load properly. Therefore, I decided to separate them to overcome this bottleneck, and also so I could explain the Smiles Tokenizer's functionality in further detail in the 2nd tutorial.

**Comment by peastman** [comment]
Are they different enough to justify two separate tutorials?  That is, does the reader learn significant new things from the second one they didn't get from reading the first one?

If so, the second tutorial can be simplified a lot, since it doesn't need to repeat things they just read in the previous tutorial.

**Comment by seyonechithrananda** [comment]
I think the best approach may be to cut the masked inference portion and just keep the attention on visualization and fine-tuning sections, to simplify it as you said. The main goal is to provide a clear use-case for the Smiles Tokenizers API as well as how to use it, alongside how it performs on the various tasks ChemBERTa can do.

**Comment by seyonechithrananda** [comment]
Hey @rbharath @peastman made some new changes (long delay haha) to the tutorials.

Main summary:

1. Added all the explanations with LaTeX on transformers, attention, BERT, CheMBERTa, transfer learning, etc.
2. Polished the Smiles-Tokenizer tutorial (part 23) and trimmed repetitive parts!

Feel free to add any comments or questions, thanks for reviewing this long-delayed PR! :)

**Comment by peastman** [comment]
This is coming along really nicely!  Here are some thoughts on the latest version.

The introduction is still pretty intimidating.  It throws around a lot of terms the reader may not be familiar with, and then embeds your entire conference poster as an image.  It might help to add, "Don't worry if you aren't familiar with some of these terms.  We'll explain them later."  And I'd remove the poster.  You can provide a link to it for people who want more detail.  As it is, the reader is confronted with a whole lot of dense, very technical material before they've even reached the real start of the tutorial.

There's a section titled, "What is attention," but it never says what attention is.  It just dives right into a discussion of dot products of key vectors and query vectors.  That isn't what attention is.  That's just how it's implemented in one particular model.  I'd replace it with a high level explanation of the concept of attention.  The discussion of keys and queries can be moved down into the next section that describes how transformers work.

There's a lot of code scattered through the tutorial that seems unrelated to the text surrounding it.  A few examples:

- At the end of the "what is a tokenizer" section, there's a cell that imports apex.
- At the end of the "what is attention" section, there's a cell that creates a model and tokenizer.
- Near the start of the "fine tuning ChemBERTa" section, there are a couple of cells to execute `cd` and `pwd` commands, even though you don't do anything related to those directories until a while later.

Most of the content of the SMILES-tokenizer tutorial is still word for word identical to the first tutorial.  There isn't that much different content in it.  I think it would be best to combine them into a single tutorial.  It can just be one additional section, showing how the results change when you use a different tokenizer.

**Comment by seyonechithrananda** [comment]
Thanks @peastman! I do agree, the only issue is with the attention visualization package, which has this weird issue in Colab that causes it to only run one query per run-time. Hence in other to run attention visualization on the Smiles-Tokenizer the user would have to restart the runtime and run the next cell. Because of this, I decided to separate them, but otherwise, I'd totally agree that having them contrast results for benchmarking in the same notebook is much better!

Let me know what you think. I can try to re-run both in one notebook or just remove the attention visualization section for Smiles-Tokenizer. 

Regarding the other changes, those sound like awesome suggestions! Will add them in :)

**Comment by peastman** [comment]
> or just remove the attention visualization section for Smiles-Tokenizer.

I think it would be fine to remove them.  You don't discuss any details of the visualization.  It's just to show that those visualizations exist.  Readers don't learn anything new by seeing them a second time.

**Comment by seyonechithrananda** [comment]
> > or just remove the attention visualization section for Smiles-Tokenizer.
> 
> I think it would be fine to remove them. You don't discuss any details of the visualization. It's just to show that those visualizations exist. Readers don't learn anything new by seeing them a second time.

Fair point! That makes it easier, will merge them and push updates here.

**Comment by rbharath** [comment]
Took a quick pass as well. Looking pretty good!

+1 to @peastman's suggestion to combine the two tutorials into one tutorial with a new section for the Smiles tokenizer

**Comment by seyonechithrananda** [comment]
Hey @peastman @rbharath,

Added in feedback. Both tutorials are merged into one, and I re-ordered some of the explanations to flow better (alongside a more intuitive definition of attention).

Let me know what you think. Thanks!

**Comment by rbharath** [comment]
I like the new version :). The new explanations make it clearer and easier to understand

**Comment by seyonechithrananda** [comment]
> I like the new version :). The new explanations make it clearer and easier to understand

Awesome, glad you liked it :), hopefully, users enjoy the updates!

**Comment by peastman** [comment]
I think we can call this ready to merge!  There's still room for further cleanup, but I think it's good enough to get it posted.

**Comment by rbharath** [comment]
Ok, going to go ahead and merge!

**Pull request merged**
