### PR TITLE
Pubchem Bioassay Dataset generation focused on a particular gene, or using larger dataset options

### PR DESCRIPTION
**Pull request by LRParser**
Please note that for this pull request superceeds #977. Here I left the orginal pcba.csv.gz dataset untouched, since I felt I could add the most incremental at lowest risk (and also maintain backwards compatibility) just by adding two new ones. They reflect all the assays that currently meet the criteria met by the 128 originally (pcba_146) and another much larger grouping of essentially all small molecule dose-response assays available on pubchem bioassay.

Datasets available at:
https://s3.us-east-2.amazonaws.com/deepchem-pcba-datasets/pcba_146.csv.gz
and
https://s3.us-east-2.amazonaws.com/deepchem-pcba-datasets/pcba_2475.csv.gz

### CODE REVIEW

**Comment by rbharath** [comment]
Looks like a yapf error. Should be good to merge in once fixed!

**Comment by LRParser** [comment]
What is strange is that the test script passes locally but not on Travis...and I see this also for everyone else's builds, which is why I didn't notice it at first. Any ideas of what else to do?

(deepchem-fork) joe@powerspec:~/deepchem-fork$ bash devtools/travis-ci/test_format_code.sh
No Python Files Changed
Passed Formatting Test

And also:
(deepchem-fork) joe@powerspec:~/deepchem-fork$ yapf -d deepchem/molnet/__init__.py deepchem/molnet/check_availability.py deepchem/molnet/load_function/pcba_datasets.py deepchem/molnet/run_benchmark.py examples/benchmark.py

I also ran them thru yapf -i just to double-check, but no changes were made here either (I already had setup a pre-commit hook for yapf to be on the safe side)

**Comment by rbharath** [comment]
Could you check that you have the latest version of `yapf`? I think `deepchem` is now on yapf 20.0.

Sometimes there are strange system problems and you might have to make a manual fix locally to get `yapf` to work right.

**Comment by LRParser** [comment]
Just as noted in #1000 I am also at the latest yapf version (0.20.0). Will try a few older versions to see if there is possibly an older version running on Travis that flags issues that 0.20.0 ignores.

**Comment by rbharath** [comment]
@LRParser Awesome, thanks for sticking with it and making the tests go through!

LGTM

**Pull request merged**
