### PR TITLE
Added Sparse/Lazy Adam optimizer

### PR DESCRIPTION
**Pull request by atreyamaj**
## Description
Added the Sparse Adam optimizer, also known as the Lazy Adam optimizer.

Referencing #2478 

This change requires the `Tensorflow Addons` dependency, which is an official extension of the Tensorflow library. This PR is intended to be merged after #2488 

## Type of change

Please check the option that is related to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [x] Documentations (modification for documents)

All tests for `test_optimizers.py` are passing.

Screenshot from 2021-04-20 19-37-31

The warnings seem to be unrelated to the added code.

## Checklist

- [x] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [x] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [x] Run `mypy -p deepchem` and check no errors
  - [x] Run `flake8 <modified file> --count` and check no errors
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

@rbharath @alat-rights @peastman  @ncfrey 

P.S. I have made this PR a draft PR at the moment. If the addition of TF_Addons is alright, I will change it to an Open PR.

### CODE REVIEW

**Review by rbharath — APPROVED** [review]
Code looks good on my end! Might be good to have @peastman take a quick look as well since he's been reviewing the other optimizer PRs

**Comment by rbharath** [comment]
Ah my bad, sorry just noticed this is a WIP. Let me know when this is ready to review!

**Comment by atreyamaj** [comment]
> Ah my bad, sorry just noticed this is a WIP. Let me know when this is ready to review!

@rbharath  It should be ready to review :sweat_smile: 

I marked it as a draft due to the additional dependency temporarily.

**Comment by peastman** [comment]
Looks good!

**Comment by peastman** [comment]
Except yapf is complaining.  Can you run it on test_optimizers.py?

**Comment by atreyamaj** [comment]
> Except yapf is complaining. Can you run it on test_optimizers.py?

Sorry about that, I've committed the YAPF reformatting. @peastman

**Comment by rbharath** [comment]
Going to go ahead and merge in!

**Pull request merged**
