### PR TITLE
Created AtomicConformationFeaturizer

### PR DESCRIPTION
**Pull request by peastman**
This is the first piece of #2214.  Comments on the design and API would be great.

I have a few unresolved problems with file loading.  When starting from a SDF file or SMILES string, everything works correctly.  But when loading a PDB file, all the partial charges come out as 0.  Any idea why?

I don't currently have a test for loading a mol2 file.  I tried using both Chimera and OpenBabel to convert one of the SDF files to mol2, but RDKit gives an error when loading it:

```
[14:08:10] Can't kekulize mol.  Unkekulized atoms: 3 4 7 9 10 11 15 23 25
```

If I specify `sanitize=False` I can get it to load, but then all the partial charges are 0.  If I load the SDF file it was converted from, everything works correctly.

### CODE REVIEW

**Comment by rbharath** [comment]
I did a first pass through and design appears pretty reasonable! 

One PDB files, I was under the impression that base PDB files didn't have partial charges and that's why PDBQT was used. Is that incorrect?

Also good question on the mol2 files. I think that we currently don't have much support/test-cases for mol2 files so it's probably unsurprising we have strange errors there we haven't run into before

**Comment by peastman** [comment]
I don't think any of these formats have partial charges.  We call `ComputeGasteigerCharges()` to compute them.

**Comment by peastman** [comment]
It was failing to compute the partial charges because the PDB file contained an osmium(!) atom, which RDKit didn't know what to do with.  I switched to a different PDB file and now it works.

**Comment by peastman** [comment]
I still don't know what's happening with the mol2 file.  Unfortunately, RDKit doesn't do any kind of error reporting while loading mol2 files.  If anything goes wrong, it just returns None and doesn't give you any more information.  I suggest we go ahead and merge this once the tests finish, and make it a separate project to improve our mol2 support here and elsewhere.

**Comment by peastman** [comment]
The test failures are in unrelated code.

**Review by rbharath — APPROVED** [review]
Did a pass and this is looking good! Feel free to merge once ready :)

**Pull request merged**
