### PR TITLE
PAGTN featurisation support for Molecular Graph Conv

### PR DESCRIPTION
**Pull request by VIGNESHinZONE**
Building the wrapper function for PAGTN model https://github.com/deepchem/deepchem/issues/2389
The model and featurisers are already built in DGL-Lifesci [#138](https://github.com/awslabs/dgl-lifesci/pull/138) [#139](https://github.com/awslabs/dgl-lifesci/pull/139) and now needs a wrapping function.

In this PR I'm adding - 
1) PAGTN featurisation (constructs a complete MolGraph)
2) A useful utility for building MolGraphs -> One hot encoding of formal charge of an Rdkit.Atom

### CODE REVIEW

**Review by rbharath — APPROVED** [review]
This looks good on my end!

@mufeili Would you mind doing a quick review pass here as well since we're wrapping a DGL model?

**Comment by mufeili** [comment]
Sure.

**Comment by mufeili** [comment]
Sorry for the late reply, should "tom pairs" at L233 in `mol_graph_conv_featurizer.py` be `atom pairs` instead?

**Comment by VIGNESHinZONE** [comment]
> L235-236: what do you mean by "calculating the shortest path between them"? Do you mean "and the function needs to calculate the shortest path between them"?

Yup, I meant that only.  

@mufeili Thanks for the review and I will add these changes in the new ongoing PR https://github.com/deepchem/deepchem/pull/2508

**Pull request merged**
