### PR TITLE
Benchmark script with tf changes

### PR DESCRIPTION
**Pull request by miaecle**
bypass the tensorflowmodel class and some trivial modifications(sorry for the messy style before...)

### CODE REVIEW

**Comment by rbharath** [comment]
@miaecle It looks like this PR has some overlap with #289 (which actually removes the `TensorflowModel` class). I'm currently running a complete benchmark run with that PR (will take ~1 day to finish). We can merge in this PR after that PR is in.

**Comment by miaecle** [comment]
Oh sure! Hope the data will be better!

**Comment by miaecle** [comment]
@rbharath Oh sure! Hope the data will be better!

**Comment by rbharath** [comment]
@miaecle Thanks for waiting! I want to set up a new commit process of running a full benchmark suite for any major changes. Unfortunately, this looks like it will add about 1 day's extra time to any PR, but I think it will save us significant debugging effort moving forward.

**Comment by miaecle** [comment]
@rbharath I hold the very same idea, it is for now the best way to keep the whole module stable

**Comment by rbharath** [comment]
@miaecle Could you update this PR now that #289 has been merged in?

**Pull request closed without merging**
