### PR TITLE
Stratified splitters, and minor changes for MolNet

### PR DESCRIPTION
**Pull request by VIGS25**
1. Added some options for train-test-split, scaffold and stratified splitters since they follow that split in the paper for MolNet datasets. 
2. Fixed a split and transform issue with Tox21
3. Fixed a bug introduced in previous PR in the ChemCeption model.

### CODE REVIEW

**Comment by VIGS25** [comment]
Yes this can be merged. 
On a different note, we should have a test-suite for MolNet too.

**Comment by rbharath** [comment]
+1 to the idea of having a MolNet test suite. What types of tests are you thinking?

**Comment by VIGS25** [comment]
One would be to check if the datasets and transformers were saved in the directory that they were intended to. 
I'd want to test for properties of the dataset but I am not sure how to test for those in a dataset-agnostic manner.

**Comment by VIGS25** [comment]
Can you tell me which ones these are and I'll start fixing them on my end?
I found one too when I was running Transfer Learning experiments

**Pull request merged**
