### PR TITLE
Various improvements to layers

### PR DESCRIPTION
**Pull request by peastman**
This is a collection of a few different minor changes.  I removed the extra dense layer from GRU, as discussed in #570.  I also fixed a couple of bugs in the Dense layer.  And I made it so `in_layers` can be a single layer instead of a list.  That means when a layer has only a single parent, you can write `in_layers=parent` instead of `in_layers=[parent]`.  It only saves a couple of characters, but I think it makes the code a bit more readable.

### CODE REVIEW

**Comment by peastman** [comment]
The test failures are caused by a bug that already existed, but because of a second bug that I fixed, it wasn't being caught by the tests.  The problem is that Layer stores a list of variables defined by each layer.  But like all Tensorflow objects, those variables can't be pickled.  How do we want to deal with this?

**Comment by rbharath** [comment]
Layer needs to store a list of variables defined in order for us to train GANs or other models where only a subset of the layers should be trained at a given time.

I think we don't need to store the variables since they are created when `build()` is called for the layer. Perhaps we can pickle without storing the variables somehow? This is a tricky issue...

**Comment by peastman** [comment]
@lilleswing any thoughts on this?

**Comment by peastman** [comment]
I see a couple of possible solutions.  TensorGraph already has a mechanism for clearing all references to tensors before pickling, then restoring them once it's done.  We could extend that mechanism to work with variables as well as tensors.  Alternatively, if we make sure every layer defines a unique variable scope, we don't need to store the variables themselves.  We can just store the scope name, then turn `variables` into a property that looks them up when needed.

**Comment by rbharath** [comment]
I like the idea of making each layer have a unique variable scope. Leverages Tensorflow primitives and will improve our Tensorboard integration.

**Comment by peastman** [comment]
I'm trying to implement that but running into a problem: to query the variables, you need a reference to the graph.  The layer doesn't, so you can't just call `get_variables()` on it.  And it would be kind of ugly to have to write

```Python
with tensorgraph._get_tf("Graph").as_default():
  variables = layer.get_variables()
```

Perhaps we could move that method to the TensorGraph so you would call

```Python
variables = tensorgraph.get_variables(layer)
```

**Comment by rbharath** [comment]
Moving the method to TensorGraph seems like a good solution.

**Comment by peastman** [comment]
I tested it out by asking for all the variables in a `WeightedLinearCombo` layer.  It has two parents, so there should be two of them.  But here's the return value:

```
[<tf.Variable 'WeightedLinearCombo_3/Variable:0' shape=(1,) dtype=float32_ref>,
<tf.Variable 'WeightedLinearCombo_3/Variable_1:0' shape=(1,) dtype=float32_ref>,
<tf.Variable 'WeightedLinearCombo_3/Variable/Adam:0' shape=(1,) dtype=float32_ref>,
<tf.Variable 'WeightedLinearCombo_3/Variable/Adam_1:0' shape=(1,) dtype=float32_ref>,
<tf.Variable 'WeightedLinearCombo_3/Variable_1/Adam:0' shape=(1,) dtype=float32_ref>,
<tf.Variable 'WeightedLinearCombo_3/Variable_1/Adam_1:0' shape=(1,) dtype=float32_ref>]
```

In addition to the two variables created by the layer, it looks like the optimizer has created another four variables in the same scope.

**Comment by rbharath** [comment]
Interesting, not sure if this is a bug or a feature...

**Comment by peastman** [comment]
I don't think it's a bug as far as TensorFlow is concerned.  But it does mean we can't assume the variables we create are the only ones in that scope.

**Comment by rbharath** [comment]
I think that should be ok. The underlying tensorflow graph is kind of like "assembly". Not unreasonable that autogenerated extra variables will pop up.

**Comment by peastman** [comment]
All tests are now passing.

**Comment by rbharath** [comment]
LGTM.

**Comment by lilleswing** [comment]
Sorry for not responding earlier.  This PR also fixed 

https://github.com/deepchem/deepchem/issues/555

I agree that querying tensorgraph for the variables was the best call, both from an API perspective and the Tensorboard repercussions.

**Pull request merged**
