### PR TITLE
AtomicCoordinates featurizer with variadic molecule size

### PR DESCRIPTION
**Pull request by joegomes**
This PR adds:
- Small change to `AtomicCoordinates` featurizer to return objects

@rbharath With this change added, I'm still unable to load the GDB7 dataset (neatly).  Here's the error I receive after calling `DataLoader.featurize()`:
[ERROR/PoolWorker-14] Traceback (most recent call last):
  File "/home/joegomes/deepchem/deepchem/featurizers/featurize.py", line 56, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/joegomes/deepchem/deepchem/featurizers/featurize.py", line 93, in featurize_map_function
    raw_df_shard, write_fn, shard_num, input_type)
  File "/home/joegomes/deepchem/deepchem/featurizers/featurize.py", line 240, in _featurize_shard
    metadata_row = write_fn((basename, df_shard))
  File "/home/joegomes/deepchem/deepchem/datasets/__init__.py", line 154, in write_dataframe
    dtype, verbosity)
  File "/home/joegomes/deepchem/deepchem/datasets/__init__.py", line 890, in convert_df_to_numpy
    x = np.squeeze(np.array(x_list))
ValueError: could not broadcast input array from shape (5,3) into shape (1,1)

The problem pops up when trying to cast a list of numpy arrays (from AtomicCoordinates, after data validation in `convert_df_to_numpy`) into a numpy array.  I've played around with removing this np.array call in `Dataset` and I run into problems doing the `select` call during dataset splitting (trying to index a multi-dim list).  I've also tried making `AtomicCoordinates` return a list rather than a np.array, but run into a similar broadcasting issue (5,3 -> 1).  I was able to bypass all np.array calls and ended up with a data_shape of (1,1,5,3).  I suspect there is a better way to handle this, but for now I'm modifying my local atomicnet code to expect a data shape like this.  Thoughts?

Here is code for reproducing this error:
```
from __future__ import print_function
from __future__ import division
from __future__ import unicode_literals
import os
import tempfile

import numpy as np
import numpy.random

from deepchem.featurizers.featurize import DataLoader
from deepchem.hyperparameters import HyperparamOpt
from deepchem import metrics
from deepchem.metrics import Metric
from deepchem.models.tensorflow_models import TensorflowModel
from deepchem.transformers import NormalizationTransformer
from deepchem.utils.evaluate import Evaluator
from deepchem.splits import RandomSplitter
from deepchem.featurizers.atomic_coordinates import AtomicCoordinates

feature_dir = tempfile.mkdtemp()
train_dir = tempfile.mkdtemp()
valid_dir = tempfile.mkdtemp()
test_dir = tempfile.mkdtemp()
model_dir = tempfile.mkdtemp()
init_dir = tempfile.mkdtemp()

featurizers = AtomicCoordinates()
input_file = "/home/joegomes/deepchem/datasets/gdb1k.sdf"
task_file = input_file+".csv"
with open(task_file, 'rb') as f:
    tasks = [x.strip() for x in f.readline().split(',')]
task_type = "regression"
task_types = {task: task_type for task in tasks}
smiles_field = "smiles"
mol_field = "mol"

featurizer = DataLoader(tasks=tasks,
                            smiles_field=smiles_field,
                            mol_field=mol_field,
                            featurizer=featurizers,
                            verbosity="high")

featurized_dataset = featurizer.featurize(input_file, feature_dir, shard_size=1000)

from deepchem.splits import RandomSplitter
random_splitter = RandomSplitter()
train_dataset, valid_dataset, test_dataset = random_splitter.train_valid_test_split(featurized_dataset,
    train_dir, valid_dir, test_dir, compute_feature_statistics=False)

input_transformers = []
output_transformers = [NormalizationTransformer(transform_y=True, dataset=train_dataset)]
transformers = input_transformers + output_transformers

for transformer in transformers:
    transformer.transform(train_dataset)
for transformer in transformers:
    transformer.transform(valid_dataset)
for transformer in transformers:
    transformer.transform(test_dataset)
```
Before merging, hopefully we can use this PR to fix any outstanding variadic molecule issues.

### CODE REVIEW

**Comment by rbharath** [comment]
@joegomes Thanks for reporting this! Support for variadic data is still new for `deepchem`, so we will likely have to iron out some issues. I'll try running this on my end to see if I can come up with some thoughts on a systematic design fix.

For now, I'd recommend just moving forward with the current ad-hoc fix. I don't think this will change the behavior of the learning models any. We can always fix the model once we have a systematic `deepchem` fix in place.

**Comment by joegomes** [comment]
@rbharath More errors, this time during model.fit.  Here's what I get:

IndexError                                Traceback (most recent call last)
<ipython-input-73-5137958e0a2f> in <module>()
     33 best_model, best_hyperparams, all_results = optimizer.hyperparam_search(              
     34     params_dict, train_dataset, valid_dataset, output_transformers,
---> 35     metric, use_max=False, logdir=None)

/home/joegomes/deepchem/deepchem/hyperparameters/__init__.pyc in hyperparam_search(self, params_dict, train_dataset, valid_dataset, output_transformers, metric, use_max, logdir)
     82             self.tasks, self.task_types, model_params, model_dir,
     83             verbosity=self.verbosity)
---> 84       model.fit(train_dataset)
     85       model.save()
     86 

/home/joegomes/deepchem/deepchem/models/tensorflow_models/__init__.pyc in fit(self, dataset, shuffle, pad_batches)
    580     Fits TensorflowGraph to data.
    581     """
--> 582     self.train_model.fit(dataset, shuffle=shuffle, pad_batches=pad_batches)
    583 
    584   def predict_on_batch(self, X):

/home/joegomes/deepchem/deepchem/models/tensorflow_models/__init__.pyc in fit(self, dataset, shuffle, max_checkpoints_to_keep, log_every_N_batches, pad_batches)
    214             dataset.shuffle()
    215           for ind, (X_b, y_b, w_b, ids_b) in enumerate(
--> 216               dataset.iterbatches(batch_size, pad_batches=pad_batches)):
    217             if ind % log_every_N_batches == 0:
    218               log("On batch %d" % ind, self.verbosity)

/home/joegomes/deepchem/deepchem/datasets/__init__.py in iterbatches(self, batch_size, epoch, deterministic, pad_batches)
    321         indices = range(interval_points[j], interval_points[j+1])
    322         perm_indices = sample_perm[indices]
--> 323         X_batch = X[perm_indices, :]
    324         y_batch = y[perm_indices]
    325         w_batch = w[perm_indices]

IndexError: too many indices for array

Code for reproducing error (add this to the end of the previous code):

rp = [[12.0, 0.0, 0.01]]

train_dataset.get_data_shape()

from atomicnet import TensorflowAtomicRegressor
def tf_model_builder(tasks, task_types, params_dict, model_dir, verbosity=None):
    """Builds tensorflow models given hyperparameters.

    """
    return TensorflowModel(tasks, task_types, params_dict, model_dir,
                        tf_class=TensorflowAtomicRegressor,
                        verbosity="low")

params_dict = { 
    "layer_sizes": [[100,100]],
    "dropouts": [[0.01,0.01]],
    "learning_rate": [0.001],
    "momentum": [.8],
    "batch_size": [1],
    "num_regression_tasks": [len(tasks)],
    #"num_regression_tasks": [1],
    "weight_init_stddevs": [[np.sqrt(6)/np.sqrt(1000), np.sqrt(6)/np.sqrt(1000)]],
    "bias_init_consts": [[1., 1.]],
    "nb_epoch": [5],
    "penalty": [0.0],
    "optimizer": ["momentum"],
    "data_shape": [train_dataset.get_data_shape()],
    "radial_params": [rp],
    "angular_params": [ap],
    "conv_layers": [1],
    "boxsize": [200.0]
}   

verbosity="high"
metric = Metric(metrics.mean_absolute_error, task_averager=np.mean, mode="regression")
optimizer = HyperparamOpt(tf_model_builder, tasks, task_types, verbosity=verbosity)       
best_model, best_hyperparams, all_results = optimizer.hyperparam_search(              
    params_dict, train_dataset, valid_dataset, output_transformers,                     
    metric, use_max=False, logdir=None)

**Comment by joegomes** [comment]
@rbharath I'm working on a different branch for re-implementing this featurizer, so going to close this PR for now and re-open a new one once tests are passing.

**Comment by rbharath** [comment]
@joegomes Sgtm! Sorry there's been a lot of churn in the codebase recently!

**Comment by joegomes** [comment]
@rbharath not a problem.  I think for running gdb-7 dataset I will be doing featurization out of the box.  There is an issue with reproducing Qmachine work due to openbabel failing to properly convert some of the .xyz's to .sdf (bond order issues), as a result there are a few hundred molecules that get dropped from the dataset when reading the .sdf with rdkit.  There currently isn't a great way to read in .xyz's in deepchem and I already have a script for doing CM featurization from these .xyz files, until we have good gdb-7 models optimizing I won't try adding this code in deepchem.  The script featurizes by loading the atomic number and xyz coordinates into a fixed size array, and adds a 0 or 1 for masking out ghost atoms when running atomicnet featurization in TF.  

I am currently working on the scan -> map_fn conversion, masking, and incorporating atomic number into symmetry functions over in deepchem-models.

**Comment by rbharath** [comment]
@joegomes Very cool! My progress on pdbbind has been halted temporarily (I've got quals scheduled next Friday), but I hope to pick up pdbbind and get it working once gdb-7 is running. I think many of the extra atomic-number features will be required for pdbbind (since it too has diverse ligands).

**Pull request closed without merging**
