### PR TITLE
[WIP] Tutorial 14 - Modeling Protein-Ligand Interactions with Atomic Convolutions

### PR DESCRIPTION
**Pull request by ncfrey**
## Description

Addresses #1179

This PR includes a tutorial on using Atomic Convolutional Neural Nets (ACNNs) to predict protein-ligand binding affinities from PDBbind. It closely follows the [original paper](https://arxiv.org/pdf/1703.10603.pdf) and describes the architecture of ACNNs. Happy to incorporate any feedback! In particular, wondering if some extra context should be added discussing e.g. [other efforts](https://www.frontiersin.org/articles/10.3389/fphar.2020.00069/full) to predict binding affinities from only ligands or proteins.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by rbharath — COMMENTED** [review]
Sorry for the slow review! This looks really good overall :). Have a few comments below

- Can we remove the "####" in "#### Distance Matrix" and other entries?
- Oh wow, the core set featurizes pockets in just a minute? That's great!
- The model actually looks to be learning something sensible! That's awesome :). It's been quite a while since the atomic convs have behaved well enough to learn nontrivial signals.
- We should definitely add a discussion of other methods and papers like https://www.frontiersin.org/articles/10.3389/fphar.2020.00069/full. Great suggestion! We might want to compare to things like `gnina` or the Atomwise atomic convolutions for example

**Comment by ncfrey** [comment]
No problem, thanks for the review! I modified the titles and added some "extra reading" for interested users.
The core set with pockets is really ideal for rapid experimentation! I've emphasized how quick the featurization is.

**Review by rbharath — APPROVED** [review]
Tutorial looks great! Feel free to merge when ready :)

**Comment by SaharRohaniZ** [comment]
Hi @ncfrey I ran Tutorial 14 and getting an error with load_pdbbind().
Code:
tasks, datasets, transformers = load_pdbbind(featurizer=acf,
                                             save_dir='.',
                                             data_dir='.',
                                             pocket=True,
                                             reload=False,
                                             set_name='core')

Error:
featurizer error

**Pull request merged**
