### PR TITLE
[WIP] Return entire dataset when split==None

### PR DESCRIPTION
**Pull request by nitinprakash96**

### CODE REVIEW

**Comment by nitinprakash96** [comment]
@lilleswing I tried to fix #1115 but apparently the build is stopping midway. Perhaps because last version tag. Could you please take a look into it?

**Comment by lilleswing** [comment]
https://github.com/deepchem/deepchem/pull/1132

Yeah it isn't your fault, we have to do the version bumps after the cut.

**Comment by lilleswing** [comment]
Please merge master to try again.

**Comment by lilleswing** [comment]
LGTM for the dataset.

Please move the ipython notebook to a separate branch/PR.

**Comment by nitinprakash96** [comment]
Apparently the python2 build is failing now.

**Comment by lilleswing** [comment]
Congratulations on the PR!  Merging this now!.

This brings up how we have lots of repeated code in all of our "x_datasets.py" modules as this contribution isn't automatically applied to all the rest of our load functions :(.

**Pull request merged**
