### PR TITLE
get_config for deepchem.models.layers

### PR DESCRIPTION
**Pull request by VIGS25**
Added `get_config()` for all layers in `deepchem.models.layers`. This allows using the `load_model` from tf.keras for custom layers in DeepChem.

WIP as tests are still missing.

### CODE REVIEW

**Comment by peastman** [comment]
Very nice!

**Comment by peastman** [comment]
yapf is complaining, probably because you have a different version on your computer.  Travis is using 0.22.0.

**Comment by VIGS25** [comment]
@rbharath: Added the tests for GraphY Y={Pool, Gather, Conv} layers. I will add the rest by the weekend.

**Comment by VIGS25** [comment]
When trying to run the example referenced in #1705 , `get_config` and `tf.keras.Model` turn a callable activation function argument into an `str` somehow through its internal mechanics (not checked why this is the case). 

As a result, the previous commit makes all initializations and activation arguments an `str` and gets the corresponding activation/ initialization callable. Some of the initialization names were changed to match `tf.keras` and a couple of tests changed to fix that. The example runs locally now, and hopefully the save problem is sorted.

**Comment by rbharath** [comment]
@VIGS25 Awesome! Let me know once this is ready to merge in and I'll get it in right away :)

**Comment by VIGS25** [comment]
Travis failure is unrelated. The tests have been added for all layers now. Ready to merge!

**Pull request merged**
