### PR TITLE
Issue 1138: Fix DTNNTensorGraph, DAGTensorGraph, PetroskiSuchTensorGraph, MPNNTensorGraph, and TextCNNTensorGraph

### PR DESCRIPTION
**Pull request by mlgill**
This pull request is to fix the remaining TensorGraph model names, as described [here](https://github.com/deepchem/deepchem/issues/1138).

### CODE REVIEW

**Comment by mlgill** [comment]
Looks like there's one issue and it's only Python 2.7. I suspect this was caused by something other than renaming of classes.

```
======================================================================
FAIL: Test tf progressive multitask overfits tiny data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/deepchem/deepchem/deepchem/models/tests/test_overfit.py", line 941, in test_tf_progressive_regression_overfit
    assert scores[metric.name] < .2
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
computed_metrics: [0.16453259010611634, 0.04753728627126391, 0.32708800196503224, 0.7498724269564536, 0.2535319830292596]
```

**Comment by lilleswing** [comment]
LGTM Thanks again for this work @mlgill !

**Comment by peastman** [comment]
It appears the deprecation warnings were implemented incorrectly.  You should only get each warning if you use the old name.  Instead, you get the whole list of warnings every time you import deepchem.

```
>>> import deepchem
/Users/peastman/workspace/deepchem/deepchem/models/tensorgraph/models/graph_models.py:1159: FutureWarning: GraphConvTensorGraph is deprecated and has been renamed to GraphConvModel and will be removed in DeepChem 3.0.
  FutureWarning)
/Users/peastman/workspace/deepchem/deepchem/models/tensorgraph/models/graph_models.py:1170: FutureWarning: WeaveTensorGraph is deprecated and has been renamed to WeaveModel and will be removed in DeepChem 3.0.
  FutureWarning)
/Users/peastman/workspace/deepchem/deepchem/models/tensorgraph/models/graph_models.py:1181: FutureWarning: DTNNTensorGraph is deprecated and has been renamed to DTNNModel and will be removed in DeepChem 3.0.
  FutureWarning)
/Users/peastman/workspace/deepchem/deepchem/models/tensorgraph/models/graph_models.py:1192: FutureWarning: DAGTensorGraph is deprecated and has been renamed to DAGModel and will be removed in DeepChem 3.0.
  FutureWarning)
/Users/peastman/workspace/deepchem/deepchem/models/tensorgraph/models/graph_models.py:1203: FutureWarning: PetroskiSuchTensorGraph is deprecated and has been renamed to PetroskiSuchModel and will be removed in DeepChem 3.0.
  "PetroskiSuchModel"), FutureWarning)
/Users/peastman/workspace/deepchem/deepchem/models/tensorgraph/models/graph_models.py:1214: FutureWarning: MPNNTensorGraph is deprecated and has been renamed to MPNNModel and will be removed in DeepChem 3.0.
  FutureWarning)
/Users/peastman/workspace/deepchem/deepchem/models/tensorgraph/models/text_cnn.py:296: FutureWarning: TextCNNTensorGraph is deprecated and has been renamed to TextCNNModel and will be removed in DeepChem 3.0.
  FutureWarning)
```

The calls to `warnings.warn()` should go inside the constructors.

**Comment by mlgill** [comment]
@peastman Good catch. I originally had them inside the init and will move them back. I had moved them above the init so that the call happens on import, but I didn't think about the fact that deepchem imports all of them at the models layer for easy access. I'll address later today.

**Comment by mlgill** [comment]
@peastman I have addressed the issue [here](https://github.com/deepchem/deepchem/pull/1196).

**Pull request merged**
