### PR TITLE
Changes to fix failing test cases

### PR DESCRIPTION
**Pull request by peastman**
I'm going through the full test suite, fixing the ones that are failing.  There are still a few more failures I haven't debugged yet.

### CODE REVIEW

**Comment by peastman** [comment]
I think this is ready to merge.

**Comment by rbharath** [comment]
LGTM

**Comment by peastman** [comment]
With this merged, are we ready for the release?

**Comment by rbharath** [comment]
Yes, I think so. Let's confirm on the weekly sync-call and pull the trigger.

**Pull request merged**
