### PR TITLE
Fixing broken CI on windows - Jax and Vina

### PR DESCRIPTION
**Pull request by arunppsg**
Summary of changes:

- Skipping pytest test in windows for vina since autodock vina is supported only in linux and macos
- Ignoring doctest for `deepchem/models/jax_models/*` in windows since jax is not supported in windows currently.

### CODE REVIEW

**Comment by rbharath** [comment]
Changes look good I think! We still have a few more CI failures but I think those are unrelated to this PR. Could you confirm CI failures are unrelated and if so go ahead and merge in?

**Comment by arunppsg** [comment]
New failures due to torch-sparse release!

**Comment by arunppsg** [comment]
Fixed the torch issue but for some reason, macOS build is failing. It is getting successfully built but raises a segmentation fault in import check ([ref](https://github.com/deepchem/deepchem/runs/5521296417?check_suite_focus=true#step:8:1))

**Comment by arunppsg** [comment]
The CI is passing on build scripts, the recurring failures in windows in core CI and common CI are passing. The other failures are unrelated and will merge this in.

**Pull request merged**
