### PR TITLE
conda install -c deepchem deepchem

### PR DESCRIPTION
**Pull request by lilleswing**
Created DeepChem organazation on Anaconda cloud
https://anaconda.org/deepchem/repo
Ask if you want ownership perms.

It now has two packages
- [deepchem]
- [deepchem-gpu]

each one is built with python 2.7, 3.5 and 3.6.

```bash
# this is a bit sloppy because we have to install pdbfixer from omnia and rdkit from rdkit
# without gpu
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=1.2.0
# with gpu
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem-gpu=1.2.0
```

Added instructions for building the conda recipes in the release developer TODO.  We will run into issues with scripts/install_deepchem_conda.sh and devtools/conda-recipe/deepchem/meta.yml drifting, so we have to manually sync them on cuts.  The only way to solve this would be to force users to build locally with conda instead of using the easy install script.

### CODE REVIEW

**Comment by rbharath** [comment]
@lilleswing This is awesome! Could you add me as an owner?

https://anaconda.org/deepchem/repo/installers lists the install direction as `conda install --channel deepchem package` so we might run into some confused users later. We should see if there's a way to simplify the install (perhaps by having rdkit/pdbfixer builds in the deepchem org)

**Comment by rbharath** [comment]
@lilleswing The Travis CI build seems to be erroring https://travis-ci.org/deepchem/deepchem/builds/262025126. Do you think it's related to this PR?

**Comment by lilleswing** [comment]
```bash
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```
Seems like we are just barely hitting the log length limit in the 2.7 build now.  It passed the tests but killed the job in the after_success.sh script.

We should kill some of the logs from the build.

**Comment by lilleswing** [comment]
Also if we want to move to conda-forge we can as soon as pdbfixer and rdkit move over.

**Comment by rbharath** [comment]
I'd be in favor of moving to conda-forge once possible!

**Pull request merged**
