### PR TITLE
Update Training_a_Normalizing_Flow_on_QM9.ipynb

### LINKED ISSUE #2884: Training_a_Normalizing_Flow_on_QM9 tutorial doesn't work on Google Colab
## 🐛 Bug

When running the 11th code cell of the tutorial an error occurs with the file.

## To Reproduce

1. Click the "Open in Google Colab" button of the Training_a_Normalizing_Flow_on_QM9.ipynb on examples/tutorials.
2. Run each line until you reach the 11th code line, including it.

## The following message appears:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-11-927d58de0434>](https://localhost:8080/#) in <module>()
----> 1 onehots = sf.multiple_selfies_to_hot(selfies_list, largest_selfie_len, selfies_alphabet)

AttributeError: module 'selfies' has no attribute 'multiple_selfies_to_hot'

## Expected behavior

Transform successfully from selfies to one-hot encoding based on the dataset.

## Environment

* OS: Microsoft Windows, MacOS
* Python version: 3.6.9
* DeepChem version: 2.6.1

## Additional context

When importing the rdkit.Chem dependencies the session crashes.

### PR DESCRIPTION
**Pull request by JoseAntonioSiguenza**
# Pull Request Template

## Description

Fix #2884 

The version of the selfies library was deprecated and doesn't support some methods. Specifically, the transformations from selfies to one hot and vice-versa. Also, the conda installation for rdkit included at deepchem code crashes the session. A mamba installation was considered for this purpose. Finally, it was considered an condacollab installation for this tutorial.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [x] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by rbharath — COMMENTED** [review]
I believe this looks good to me now!

@ncfrey Would you mind taking a quick review pass to confirm that changes look good to you?

**Comment by ncfrey** [comment]
2 more quick additions that would be helpful:
* Update the (??) in the title to say "Molecular Machine Learning Tutorial 7"
* Add the FastFlows reference at the beginning and end of the tutorial: https://arxiv.org/abs/2201.12419
Otherwise LGTM!

**Comment by JoseAntonioSiguenza** [comment]
Thanks for the feedback!
I'm working on this and will commit after making the corrections.

**Comment by rbharath** [comment]
@JoseAntonioSiguenza Sounds good! Let me know once you're done making fixes

**Comment by JoseAntonioSiguenza** [comment]
> @JoseAntonioSiguenza Sounds good! Let me know once you're done making fixes

@rbharath I've added the recommended comentaries. I think it shlould be good now.

**Pull request merged**
