### PR TITLE
Dynamic in-memory dataset transformation

### PR DESCRIPTION
**Pull request by joegomes**
This PR adds:
- An improvement to the existing `Model.fit` transformers method where, instead of creating a minibatch dataset for transformation before model fitting, we perform the transform in memory.  This was accomplished by adding a `transform_on_array` function to specific `Transformer` classes.

Currently, the `transform_on_array` functions are only implemented for Coulomb matrix related transformers.  Fit transformers are applied to the train dataset during fitting, and then applied to the test/valid datasets during prediction.  After some testing, I'll add the option to do n-fold averaging of predictions on n-times transformed datasets.

### CODE REVIEW

**Comment by rbharath** [comment]
@joegomes It looks like github is having issues so the Travis tests aren't running. I'll let this set a bit until the travis tests come back online.

**Comment by joegomes** [comment]
@rbharath I noticed travis wasn't starting.  The commits to the MWsplit branch finally showed up so hopefully tests will be back soon.

**Comment by rbharath** [comment]
@joegomes Travis tests seem to be back online. Could you push a dummy commit to this and the other PR to trigger a travis test?

**Comment by rbharath** [comment]
LGTM.

**Pull request merged**
