### PR TITLE
[WIP] Update 13_Modeling_Protein_Ligand_Interactions.ipynb

### PR DESCRIPTION
**Pull request by ncfrey**
## Description
This is an update for tutorial 13. The updated tutorial shows how to use DeepChem's molecular docking API to generate docking scores for protein-ligand complexes. It then shows how to featurize complexes with the new interaction fingerprints, work with the new PDBbind loader, and train a model to predict binding affinities. 

## TODO
Because of compute and memory constraints, it's not feasible to featurize the entire PDBbind dataset in the tutorial. Instead, the code to do so is given and commented out and the tutorial works with a small subset of PDBbind. This can be cleaned up after #2348 is addressed. 

Any feedback is welcome!

### CODE REVIEW

**Review by rbharath — COMMENTED** [review]
This is great! Fills a big hole in our tutorial series. Here's a couple of detailed comments:

- Do we need GPU for docking/pose-generation? I think autodock vina runs on CPU under the hood but I could be mistaken.
- It's interesting to see we get scores so low for the protein-ligand fingerprints! A couple of thoughts here: 
  - We might possibly want to increase the size of the contact circular fingerprint to 1024/2048 to match the default circular fingerprint. 
  - It might also be good to run contact circular fingerprint on the full refined set of PDBBind to do a sanity check. It's possible I might have messed up the implementation somewhere so the features are nonsensical!

**Comment by ncfrey** [comment]
> This is great! Fills a big hole in our tutorial series. Here's a couple of detailed comments:
> 
> * Do we need GPU for docking/pose-generation? I think autodock vina runs on CPU under the hood but I could be mistaken.

I think you're right here, but for some reason when I was testing this out the docking jobs failed without the GPU. That might be a memory issue on Colab? I'm not sure.
> * It's interesting to see we get scores so low for the protein-ligand fingerprints! A couple of thoughts here:
>   
>   * We might possibly want to increase the size of the contact circular fingerprint to 1024/2048 to match the default circular fingerprint.

Sounds good, will do.
>   * It might also be good to run contact circular fingerprint on the full refined set of PDBBind to do a sanity check. It's possible I might have messed up the implementation somewhere so the features are nonsensical!

I will plan to do this either when featurization checkpointing is available, or on a larger memory machine.

I'll wait to see if there are any other comments and then put up a new version of the tutorial.

**Comment by peastman** [comment]
I'm kind of confused about the dataset file you're loading.  It seems to contain the full body of the PDB files embedded in each line.  You use the `convert_lines_to_mdtraj()` function to write each one out to a file and load it with MDTraj.  But then a little ways down, you use PDBFixer to download the (same?) PDB files.  This seems overly complex.  What about including *only* the IDs in the data file?  That would make the tutorial simpler and easier to understand.

I suggest running this tutorial locally rather than on Colab.  You can keep in all the cells for Colab; just don't execute them.  That way the version people view online can include the images that you had to skip, and also won't include all the output from installing.  See the other tutorials for how that looks.

I think most of your R^2 values are just random noise.  They're close enough to 0 that the difference is probably not statistically significant.  Predicting a binding free energy is *hard*.  Getting anything meaningful probably takes a more complicated model than this, and a featurization that more explicitly considers the 3D arrangement of atoms.

You repeat the process of downloading and cleaning up the PDB files twice.  I don't think that's needed?

The line

```python
  fixer = PDBFixer(url='https://files.rcsb.org/download/%s.pdb' % (pdbid))
```

can be simplified to

```python
  fixer = PDBFixer(pdbid=pdbid)
```

**Comment by ncfrey** [comment]
> I'm kind of confused about the dataset file you're loading. It seems to contain the full body of the PDB files embedded in each line. You use the `convert_lines_to_mdtraj()` function to write each one out to a file and load it with MDTraj. But then a little ways down, you use PDBFixer to download the (same?) PDB files. This seems overly complex. What about including _only_ the IDs in the data file? That would make the tutorial simpler and easier to understand.
> 

The dataset file is something in DeepChem's S3 bucket from the old tutorial for the "core" PDBbind dataset. That sounds good, I'll simplify this bit.

> I suggest running this tutorial locally rather than on Colab. You can keep in all the cells for Colab; just don't execute them. That way the version people view online can include the images that you had to skip, and also won't include all the output from installing. See the other tutorials for how that looks.
> 

+1 

> I think most of your R^2 values are just random noise. They're close enough to 0 that the difference is probably not statistically significant. Predicting a binding free energy is _hard_. Getting anything meaningful probably takes a more complicated model than this, and a featurization that more explicitly considers the 3D arrangement of atoms.
> 

Right, I'll add more emphasis that the tutorial is meant to show the steps for this kind of problem, but that the model predictions are not meaningful.
> You repeat the process of downloading and cleaning up the PDB files twice. I don't think that's needed?
> 
> The line
> 
> ```python
>   fixer = PDBFixer(url='https://files.rcsb.org/download/%s.pdb' % (pdbid))
> ```
> 
> can be simplified to
> 
> ```python
>   fixer = PDBFixer(pdbid=pdbid)
> ```

+1

**Review by rbharath — COMMENTED** [review]
This is looking quite good! A couple of minor comments here:

- I found the line
  ```
  failures = set([f[:-4] for f in proteins]) - set([f[7:-4] for f in ligands])
  ```
  tricky to understand on a first reading. It might be useful to explain the `[:-4]` is removing the `.pdb` and the `[7:-4]` is removing the "ligand" at front and ".pdb" at end
- Instead of `r2_score`, we might want to change this to `pearson_r2_score`. The advantage of the pearson r2 is that it's guaranteed nonnegative. I remember as a newcomer, I was very confused by negative r^2 and how to think about it. Pearson is nice since we can just explain that it's basically very low correlation.

**Comment by ncfrey** [comment]
> This is looking quite good! A couple of minor comments here:
> 
> * I found the line
>   ```
>   failures = set([f[:-4] for f in proteins]) - set([f[7:-4] for f in ligands])
>   ```

Thanks for this catch! I whipped this line together while I was debugging and forgot to comment it.
>   
>   
>   tricky to understand on a first reading. It might be useful to explain the `[:-4]` is removing the `.pdb` and the `[7:-4]` is removing the "ligand" at front and ".pdb" at end
> * Instead of `r2_score`, we might want to change this to `pearson_r2_score`. The advantage of the pearson r2 is that it's guaranteed nonnegative. I remember as a newcomer, I was very confused by negative r^2 and how to think about it. Pearson is nice since we can just explain that it's basically very low correlation.

+1

**Comment by peastman** [comment]
This looks really good!

There's one part that I found confusing.  After you call `generate_poses()` you print out the value of `scores`.  It's a list of nine numbers.  What are those numbers?  You only gave it a single protein and ligand, so they obviously don't correspond to different molecules.  It identified 37 binding pockets, so they don't correspond to those either.  What do these nine numbers correspond to, and what kind of values are they?

**Comment by ncfrey** [comment]
> This looks really good!
> 
> There's one part that I found confusing. After you call `generate_poses()` you print out the value of `scores`. It's a list of nine numbers. What are those numbers? You only gave it a single protein and ligand, so they obviously don't correspond to different molecules. It identified 37 binding pockets, so they don't correspond to those either. What do these nine numbers correspond to, and what kind of values are they?

Great! And great question - that is related to the default value `num_modes=9`, which tells Vina to report the 9 lowest energy poses it finds, with scores in units of `kJ/mol`. I will clarify this in the tutorial docs.

**Comment by ncfrey** [comment]
Here's an update with those comments addressed!

**Comment by peastman** [comment]
> We used the default value for num_modes when generating poses, so Vina will return the 9 lowest energy poses it found in units of kcal/mol.

Looks good!

The cell just above it has a huge block of error text in the output, reporting a protein that failed sanitization.  I suggest editing the file to remove that.  It gets in the way of readability.

**Comment by rbharath** [comment]
New version looks good on my end to merge!

**Comment by peastman** [comment]
Agreed!

**Pull request merged**
