### PR TITLE
Attempting version fix for pytorch spline conv

### PR DESCRIPTION
**Pull request by ncfrey**
## Description

Attempting to fix test errors in #2406 and #2407 by pinning version of pytorch spline conv. I think the [new release](https://github.com/rusty1s/pytorch_spline_conv/releases/tag/1.2.1) from yesterday introduced errors in our test suite.

## Type of change

Please check the option that is related to your PR.

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by ncfrey** [comment]
Looks like this worked to fix the test errors 👍

**Comment by peastman** [comment]
Thanks for fixing this!

**Comment by ncfrey** [comment]
Going to go ahead and merge this to unblock tests for other PRs.

**Comment by rbharath** [comment]
Thanks for the fix!

**Pull request merged**
