### PR TITLE
Use Intel optimized Tensorflow on Travis

### PR DESCRIPTION
**Pull request by peastman**
This is an attempt at using a faster Tensorflow on Travis.  See #586.

### CODE REVIEW

**Comment by peastman** [comment]
I'm not sure it actually used the Intel Tensorflow.  The install script says

```
conda install -y -q -c conda-forge pandas=0.19.2
conda install -y -q -c $tensorflow_channel $tensorflow=1.3.0
conda install -y -q -c conda-forge nose=1.3.7
```

But the output seems to have skipped right from pandas to nose with no mention of Tensorflow in between:

```
Package plan for installation in environment /home/travis/anaconda/envs/deepchem:
The following packages will be SUPERSEDED by a higher-priority channel:
    pandas: 0.20.3-py35h85c2c75_2 --> 0.19.2-np111py35_1 conda-forge
Package plan for installation in environment /home/travis/anaconda/envs/deepchem:
The following NEW packages will be INSTALLED:
    nose: 1.3.7-py35_2 conda-forge
```

Is Tensorflow already installed on travis?  I don't see any mention of it in `.travis.yml'.

**Comment by lilleswing** [comment]
I see the travis logs mention installing tensorflow
```bash
Package plan for installation in environment /home/travis/anaconda/envs/deepchem:
The following NEW packages will be INSTALLED:
    backports:              1.0-py27h63c9359_1        
    backports.weakref:      1.0rc1-py27_0             
    bleach:                 1.5.0-py27_0              
    funcsigs:               1.0.2-py27h83f16ab_0      
    html5lib:               0.9999999-py27_0          
    libprotobuf:            3.4.0-0                   
    markdown:               2.6.9-py27_0              
    mock:                   2.0.0-py27_0              
    pbr:                    3.1.1-py27hf64632f_0      
    protobuf:               3.4.0-py27_0              
    tensorflow:             1.3.0-0                   
    tensorflow-base:        1.3.0-py27_0              
    tensorflow-tensorboard: 0.1.5-py27_0              
    werkzeug:               0.12.2-py27_1        intel
```

lines 743 -> 759 of the python 2.7 build
https://travis-ci.org/deepchem/deepchem/jobs/282458277

**Comment by lilleswing** [comment]
https://anaconda.org/intel/tensorflow

The intel tensorflow seems to only go to 1.2.1 and not 1.3.  I think it misses on lookup for the intel channel and just installs the one from defaults.

**Comment by peastman** [comment]
They do have 1.3 builds (I made sure of that before posting this), but I missed that they're under the `test` label.  That explains it.  Maybe best to just let this PR hang out until they decide the builds are ready to be promoted to `main`, and then we can try rerunning the builds.

**Pull request closed without merging**
