### PR TITLE
Update balance_acuracy score

### LINKED ISSUE #1891: dc.metrics.balanced_accuracy_score is broken
`dc.metrics.balanced_accuracy_score` is broken right now. This line https://github.com/deepchem/deepchem/blob/master/deepchem/metrics/__init__.py#L112
should be replaced with

```
sklearn.metrics.balanced_accuracy_score(y, y_pred, sample_weight=weights)
```

### PR DESCRIPTION
**Pull request by vsag96**
Fixes #1891

yapf -i __init__.py. Which caused a few more changes. Let me know if you want to see any further changes.

### CODE REVIEW

**Comment by rbharath** [comment]
Thanks for the fix! 

Travis is failing here. I think there might be a yapf version mismatch. Can you check that you have `yapf==0.22` installed and run
```
yapf -i deepchem/metrics/__init__.py
```

**Comment by vsag96** [comment]
Sure, I’ll get to this in a couple of hours. I might have installed a latest version rather than 0.22.

**Comment by vsag96** [comment]
@rbharath the build passes, now. Are there any modules where you want to see more tests added,I would be happy to look at those areas. Sorry about the yapf version.

Vineeth

**Comment by rbharath** [comment]
Thanks for the fix @vsag96! Going to merge this PR in.

In general, I think our transformers/splitters/metrics could use more documentation and examples. Ping me on the gitter chat (https://gitter.im/deepchem/Lobby) if you're interested in helping out!

**Pull request merged**
