### PR TITLE
Adding more contributors to README.md

### PR DESCRIPTION
**Pull request by rbharath**
As DeepChem grows as a project, it's important to recognize significant individual contributors. I've added an alphabetically ordered list of notable contributors to the README.md. I hope that we will see many more contributors join this list in the coming weeks and months :)

I will leave this PR up for some time before merging in case anyone has comments or feedback.

### CODE REVIEW

**Comment by lilleswing** [comment]
```bash
FAIL: Test training a policy for the roulette environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/deepchem/deepchem/deepchem/rl/tests/test_a3c.py", line 68, in test_roulette
    assert action_prob.argmax() == 37
```
maybe A3C test became flaky after @peastman 's changes to the reward calculation?

**Comment by peastman** [comment]
I've told it to rerun that test.  It's a stochastic test, but I ran it several times without it failing.  If necessary I can try to make it a bit more robust.

**Comment by rbharath** [comment]
Restarting Travis in hopes it passes with #634 merged.

**Comment by rbharath** [comment]
Merging this PR in. If anyone wants to propose a change in wording, feel free to reach out to me directly.

**Pull request merged**
