### PR TITLE
clintox dataset

### PR DESCRIPTION
**Pull request by calebgeniesse**
This PR includes the following additions:
- clinical trials dataset (**clintox**)
- incorporation of **clintox** into the benchmark framework
- documented benchmark performances on **clintox**
- example scripts for training multitask and graphconv models on **clintox**

Notes on the **clintox** dataset:
- the dataset consists of two classification tasks: `CT_TOX` and `FDA_APPROVED`
  - `CT_TOX` indicates:
    - drug failed a clinical trial for toxicity reasons (y=1)
    - drug has not failed any clinical trial for toxicity reasons (y=0)
  - `FDA_APPROVED` indicates:
    - drug has been approved by the U.S. FDA (y=1)
    - drug has not been approved (y=0)
  - Note: in most cases, the labels are exactly correlated (if `CT_TOX=1`, then `FDA_APPROVED=0`) and it seems like the tasks should be combined into a single classification task; however, in some cases, toxicity side effects will be acceptable for drugs used to treat severe and otherwise untreatable conditions (e.g. cancer); my initial thought was that keeping these as 2 separate tasks might capture the notion of context when considering toxicity events (let me know if you think otherwise!)
- clinical trial toxicity data was downloaded AACT database on ClinicalTrials.gov, and a list of drugs was extracted from clinical trials annotated as ‘‘Terminated,’’ ‘‘Suspended,’’ or ‘‘Withdrawn’’ and described as failing for toxicity reasons (see processing scripts for more details)
- the list of FDA-approved drugs was obtained from the drug annotations within the SWEETLEAD database

Notes on benchmark performance:
- the training/validation scores seem too good to be true.. i'm worried they may be artificially high due to something about the way I processed the dataset; looking for suggestions on how to validate the dataset 

### General features
* Number of tasks and examples in the datasets

|Dataset         |N(tasks)   |N(samples) |
|----------------|-----------|-----------|
|clintox         |2          |1491       |

### Performances
* Classification

Index splitting

|Dataset    |Model               |Train score/ROC-AUC|Valid score/ROC-AUC|
|-----------|--------------------|-------------------|-------------------|
|clintox   |logistic regression |0.967              |0.676              |
|             |Multitask network   |0.934              |0.830              |
|             |robust MT-NN        |0.949              |0.827              |
|             |graph convolution   |0.946              |0.860              |

Random splitting

|Dataset    |Model               |Train score/ROC-AUC|Valid score/ROC-AUC|
|-----------|--------------------|-------------------|-------------------|
|clintox   |logistic regression |0.972              |0.725              |
|             |Multitask network   |0.951              |0.834              |
|             |robust MT-NN        |0.959              |0.830              |
|             |graph convolution   |0.975              |0.876              |

Scaffold splitting

|Dataset    |Model               |Train score/ROC-AUC|Valid score/ROC-AUC|
|-----------|--------------------|-------------------|-------------------|
|clintox   |logistic regression |0.960              |0.803              |
|             |Multitask network   |0.947              |0.862              |
|             |robust MT-NN        |0.953              |0.890              |
|             |graph convolution   |0.957              |0.823              |

@rbharath @miaecle: let me know if you have any questions/thoughts/suggestions!

### CODE REVIEW

**Comment by calebgeniesse** [comment]
also, **clintox** was a last-minute name change.. open to suggestions

**Comment by rbharath** [comment]
@calebgeniesse Thanks for the PR! I think the clintox dataset will be a nice addition to our dataset suite.

@miaecle Could you review this code, especially the changes to the benchmark suite? I want to make sure the code matches with the style for the existing benchmarks.

**Comment by miaecle** [comment]
@calebgeniesse Thanks a lot for the contribution! New dataset looks nice, I will try to check the results too.
@rbharath LGTM, benchmark script modifications are all consistent with the existing style, should be fine to get merged in.

**Comment by rbharath** [comment]
Great, will go ahead and merge this in then.

**Pull request merged**
