### PR TITLE
Fixed error with TensorFlow 2.4

### LINKED ISSUE #2379: Failed to run Deepchem Tutorial Part 15
I can't avoid the error message while I am running Deepchem Tutorial Part 15 on Colab.
Please help me.

TypeError: Keras symbolic inputs/outputs do not implement `__len__`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model. This error will also get raised if you try asserting a symbolic input/output directly.

### PR DESCRIPTION
**Pull request by peastman**
Fixes #2379.

### CODE REVIEW

**Comment by peastman** [comment]
Because of the flake8 error introduced in #2371, CI never even gets as far as running the test cases.  I'm going to fix it here so we can get the tests to run again.

**Comment by peastman** [comment]
Now it's failing on mypy errors that again were pre-existing, but were getting masked by the flake8 error.  This reveals a critical problem in the new Github Actions CI: as soon as it gets any error, it stops running.  With the travis version, an error in one set of tests didn't prevent it from running other tests.

**Review by rbharath — COMMENTED** [review]
Thank you for hitting these fixes! Is this ready for us to merge in?

**Comment by peastman** [comment]
No, it isn't even running the tests yet.  I'm going to fix the CI errors in #2382.

**Comment by peastman** [comment]
This fix is included in #2382.

**Pull request closed without merging**
