### PR TITLE
feat: add logging through W&B

### PR DESCRIPTION
**Pull request by borisdayma**
Add logging of `KerasModel` to Weights & Biases by using arg `wandb=True`.

How to use:

* `pip install wandb` in shell
* `wandb login` in shell
* `wandb.init()` in script to start a W&B run
* `model = KerasModel(…, wandb=True)`

[This MNIST demo notebook](https://gist.github.com/borisdayma/68ea13ec531ed0e5c8b2ee6dc9c759d3) logs the following charts on W&B (see [logged run](https://app.wandb.ai/borisd13/deepchem/runs/12fjcf05?workspace=user-borisd13)):

image

Notes:
* I didn't run yapf because it was creating too many formatting changes which I was not sure you wanted
* After this I can add the same to `SklearnModel` (would probably move wandb import logic to a common file)
* Later we can add more features such as saving trained model, sweeps, etc…

Let me know if you have any comments or want me to change anything!

### CODE REVIEW

**Comment by rbharath** [comment]
@borisdayma This is slick! I'm really looking forward to being able to use wandb to track training runs :). A couple of minor requests for changes

- Could you add `wandb` as an optional dependency to the top level `README.md`? 
- Could you add a `wandb` section to `docs/models.rst` in the `KerasModel` section that explains how to use `wandb` and adds in the directions above?
- Could you go ahead and run `yapf` on the changed files? It's all good if we end up having large formatting changes. This happens time to time with `yapf`. (Although, it might be the `yapf` version, so might be good to check `yapf==0.22`)

@peastman Could you take a quick review pass as well?

**Comment by borisdayma** [comment]
I was using yapf v0.30!

Let me know if I need any more changes.

**Comment by rbharath** [comment]
I think the test failure is a transient issue. I think this PR is good to merge on my end :). It's the long weekend though, so I'm going to wait till Tuesday to merge in case other folks have comments

**Comment by peastman** [comment]
Looks good!

**Comment by rbharath** [comment]
@borisdayma I think we're good! Could you rebase and fix the merge conflict and I'll go ahead and merge in?

**Comment by borisdayma** [comment]
Ok it should be good to go now!

**Comment by rbharath** [comment]
@borisdayma Just merged. Congrats on your first DeepChem PR! Hope to see improved wandb integration coming our way :)

**Comment by borisdayma** [comment]
Definitely! We're going to play a bit with it and then I can work on doing the same with `SklearnModel`.
Then I can add other features based on what is the most useful for your repo!

Please feel free if you have any feedback

**Pull request merged**
