### PR TITLE
Merge datasets preserves shard sizes

### PR DESCRIPTION
**Pull request by EvanKomp**
# Merge datasets preserves shard sizes

## Description
The static method Dataset.merge currently loops over passed datasets to merge, yielding (X, y, w, ids) for each dataset. This is prohibitive when merging DiskDatasets of millions of examples whose raw numpy arrays (eg. dataset.X) are >1E+1 GB. Now, if the dataset to be merged has a shard iterator such as the case for a DiskDataset, the shard iterator will be used to generate sets of (X, y, w, ids) according to the datasets shard size, instead of yielding the entire dataset at once. Finally, the smallest shard size of initial datasets is used for the merged dataset.

yapf seems to have made a number of changes outside of where I made code changes 😅 . Code changes to the module are exclusive to lines 1927 to 1951 in datasets.py. Two lines added to the test function.

## Type of change

Please check the option that is related to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [x] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [x] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [x] Run `mypy -p deepchem` and check no errors
  - [x] Run `flake8 <modified file> --count` and check no errors
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by rbharath — COMMENTED** [review]
This is great thanks!

I think the issue with `yapf` might be due to a version mismatch. Can you check you have `yapf==0.22` locally? You can do this by running
```
yapf --version
```
If you could rerun `yapf` that will make it easier to check this PR :). I think it looks correct but the extra changes mean something could have slipped through

**Comment by EvanKomp** [comment]
> This is great thanks!
> 
> I think the issue with `yapf` might be due to a version mismatch. Can you check you have `yapf==0.22` locally? You can do this by running
> 
> ```
> yapf --version
> ```
> 
> If you could rerun `yapf` that will make it easier to check this PR :). I think it looks correct but the extra changes mean something could have slipped through

Yup! Instructions very clear about verisoning and I still managed to mess it up. Reverted the wonky yapf formatting and executed the correct version. The compare now has just the code changes!

Sorry about that.

**Review by rbharath — APPROVED** [review]
LGTM! 

Sorry, this got lost in my inbox for a bit. The unit tests aren't running strangely. Could you push a small update to the PR (or perhaps rebase)? I want to see if that makes github allow me to run tests on the PR

**Comment by rbharath** [comment]
I'm going to go ahead and merge in to unblock other work; if this causes bugs we will have to fix in a follow-up PR. Thanks for the contribution!

**Pull request merged**
