### PR TITLE
PR for Issue #1384

### PR DESCRIPTION
**Pull request by pvskand**
Addressing #1384 in this PR.

### CODE REVIEW

**Comment by pvskand** [comment]
@rbharath any idea why there are `ERRORS` of this kind : https://travis-ci.org/deepchem/deepchem/jobs/419776707#L2006

**Comment by rbharath** [comment]
This is a weird problem on Python 3.6 that we're seeing across the board... I think it's safe to ignore for now. If that's the only error, we should be good to go ahead and merge in.

**Comment by pvskand** [comment]
@rbharath any updates on this? I guess we can merge it if there is no problem.

**Comment by rbharath** [comment]
Yes let's go ahead and merge since it looks like only Py3.6 errors. Thanks for the fix!

**Pull request merged**
