### PR TITLE
Update dependencies for DeepChem 2.2

### PR DESCRIPTION
**Pull request by peastman**
This is in preparation for building the 2.2 conda build.  Currently we specify exact required versions for all libraries, which is a really bad idea.  It leads to the sort of problem we've encountered with RDKit, as well as conflicts that make it hard to install DeepChem and other packages at the same time.  We should only specify a particular version of a library when there's a good reason we really need that particular version.

I've removed the version specifications for PDBFixer and MDTraj, because I'm pretty sure there's no reason to require particular versions.  The same is probably true for a lot of other libraries, but I don't know which ones.  So for the moment I've just updated RDKit to the latest release and left everything else alone.  But sometime between now and the next release we should go through all the libraries and figure out what versions are actually required.

I also updated the conda recipe to add a Python 3.7 build.

### CODE REVIEW

**Comment by peastman** [comment]
I don't understand what's going on with the build failures.  It reaches the line in install_deepchem_conda.sh that installs RDKit, and the output shows it has successfully installed it.  Then it goes on to the next line that installs a lot of other packages, and the output for that line includes

```
The following packages will be REMOVED:

  rdkit-2019.03.1.0-py36hc20afe1_1
```

Why is it removing RDKit???  I don't see anything in the script telling it to do that.  Then it tries to run the test cases, and of course fails with the error

```
ModuleNotFoundError: No module named 'rdkit'
```

Does anyone have an idea what's going on?

**Comment by peastman** [comment]
This seems to be caused by Pillow.  If I first install RDKit, then run

```
conda install pillow=5.0.0
```

it removes RDKit again.  But if I just say

```
conda install pillow
```

then it installs 6.0.0 and doesn't remove RDKit.  Is there a reason we need to be specifying a particular version for it?  As far as I can tell the only thing we even use it for is loading tif files.

**Comment by rbharath** [comment]
I think we're fine to not specify `pillow` version.

**Comment by peastman** [comment]
And now lots of tests are failing with this error:

```
  File "/home/travis/build/deepchem/deepchem/deepchem/dock/tests/test_binding_pocket.py", line 131, in test_convex_find_pockets
    import mdtraj as md
  File "/home/travis/anaconda/envs/deepchem/lib/python3.6/site-packages/mdtraj/__init__.py", line 53, in <module>
    from ._rmsd import rmsd
ImportError: dlopen: cannot load any more object with static TLS
```
Sigh.

**Comment by peastman** [comment]
Why are we hosting our own version of MDTraj on the deepchem channel rather than using the standard one???

**Comment by peastman** [comment]
Apparently that was done to work around the static TLS problem.  According to the build log, what's happening is that it first installs the deepchem build of MDTraj.  But then when the script gets to the next line which installs RDKit, it for some reason decides to replace that build with the omnia one.

Conda is driving me crazy.  I have no idea what's going on here.  Why is it that every time we tell it to install one library, it simultaneously replaces or uninstalls a bunch of others?  When I run the script locally, I'm also getting a different problem: the command to install MDTraj also causes it to uninstall PDBFixer and OpenMM.

**Comment by Lnaden** [comment]
Could you elaborate on why the various package installs are done over 3 different line with a different channels set for each of them?

I'm concerned also something in the pinning is confusing the dependency resolution as this line shows up in the builds

```
The following packages will be UPDATED:
...
  python                                   3.5.6-hc3d631a_0 --> 3.6.8-h0371630_0
```

```
The following packages will be UPDATED:
...
   python                                  2.7.16-h9bab390_0 --> 3.6.8-h0371630_0
```
see:
https://travis-ci.org/deepchem/deepchem/jobs/526222087#L775
https://travis-ci.org/deepchem/deepchem/jobs/526222086#L756

If you need that level of pinning, I might be able to create a more elegant solution.

**Comment by peastman** [comment]
> Could you elaborate on why the various package installs are done over 3 different line with a different channels set for each of them?

No clue.  I didn't write any of this.  I'm just trying to update it for the new release.  I can try combining them into a single line.  If I do that, how I do make sure it installs each package from the correct channel (e.g. MDTraj has to come from deepchem, not from omnia or conda-forge)?

**Comment by Lnaden** [comment]
>  If I do that, how I do make sure it installs each package from the correct channel 

The short answer is you should not, ideally, you would have your channel dependencies and only pin the packages you absolutely have to. Conda does not really have a recommended mechanism to say "I conditionally only want this package from this channel, and these packages from another" beyond just channel priority. It would be best if you could figure out the hierarchy of channels you want to pull from. Doing a quick look from the packages on each of those channels, I think the sequence you want is:

```python
conda install -c deepchem -c rdkit -c conda-forge -c omnia {packages}
``` 

And if you could move off `rdkit==2017.09.1` to at least `rdkit==2017.09.3`, you could remove the `-c rdkit` channel entirely, simplifying the process.

If that doesn't work though, the other thing you can do is install all of the dependencies first from one channel except for the very channel specific ones, then do `conda install -c {very specific channel} --no-deps {very specific single package}` and it will bypass dependency checks entirely. Very unsafe

The channel priority is what is causing your packages to be downgraded/changed out since saying "I want `mdtraj` from deepchem gets numpy from defaults, but then saying I want `numpy` from c-f afterwords does a follow up check on all of numpy's dependencies as well and it cascades down. 

The reason RDKit was being uninstalled before you removed the `pillow` version is that you installed RDKit, then you told conda "install this other set of packages" which it interpreted as "install this set of packages with this channel priority and do whatever is needed to solve this set including update packages or remove them if there is a unsatisfiable dependency in existing solved packages." Had you also specified that the specific RDKit version needed to be installed as well, even though it was already installed, it would have tried to resolve it without removing it.

**Comment by Lnaden** [comment]
Sorry about taking a bit to get back to you on this before you made the change. The only comment I would make is put `conda-forge` above `omnia` in package dependencies since thats what we resolve the omnia packages against in deploying. It looks like it worked for now, but might cause some issues later.

**Comment by peastman** [comment]
Done, thanks!  I would have had a terrible time figuring this out without you!

**Comment by Lnaden** [comment]
Not a problem. I'm just glad it was as simple as get the channel orders lined up and install it all at once. Conda dependency resolution is complicated on the best of days. It also looks like this solved the issue of Conda updating the environment's python binary version as well. 

I think it would still be good at some point to start relaxing the pinning, especially the old pinned versions as Python 2.7's support ends at the end of the year and 3.7 makes it so 3.5 packages will stop being deployed generally.

**Comment by peastman** [comment]
Agreed!  And we're tentatively planning to drop Python 2.7 support in the next release.

**Comment by jchodera** [comment]
Glad you folks got this sorted!

`conda` channel priority is definitely confusing:

https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html

@Lnaden's solution is optimal for now. Eventually, our goal should be to move everything to [conda-forge](https://conda-forge.org/). Hopefully, I can help once we migrate omnia.

**Pull request merged**
