### PR TITLE
Fix for Dataset Path Problems

### PR DESCRIPTION
**Pull request by miaecle**
Change the position of dataset loading functions: *_dataset.py to the folder of examples, so as to avoid the problem of cannot find dataset files

### CODE REVIEW

**Comment by rbharath** [comment]
@miaecle Thanks for the patch! Couple requests:

- Can you change the name of the PR to something descriptive? Perhaps "Fix for Dataset Path Problems"
- Can you remove the old versions of the dataset files from `deepchem/datasets`? For example, you've added `examples/bace/bace_datasets.py`, so the old file `deepchem/datasets/bace_datasets.py` should be removed.

**Comment by rbharath** [comment]
@miaecle Thanks! One more request: As the examples stand, they all use a hard-coded base directory with a username. Can you swap the base-directories to reside in `/tmp/` instead? For example, in the `muv_keras.py` file, the directory is currently `base_dir = "/scratch/users/zqwu/muv_keras"`. This would become `base_dir = "/tmp/muv_keras"`.

**Comment by miaecle** [comment]
@rbharath I have done that, hope it works!

**Comment by rbharath** [comment]
@miaecle Looks great! Going to go ahead and merge.

**Pull request merged**
