### PR TITLE
Enables loading PDB bind datasets locally

### PR DESCRIPTION
**Pull request by bbrighttaer**
A modified copy of the `load_pdbbind()` function to enable the use of local dirs and the option to skip certain problematic complexes raised in #1394.

### CODE REVIEW

**Comment by rbharath** [comment]
@bbrighttaer Thanks for your contribution! This looks like it could be a useful utility for folks. It looks like the tests are failing due to `yapf`, our code formatter. Could you install `yapf` (`pip install yapf` should do it) and run `yapf` on the modified files?

```
pip install yapf
yapf -i deepchem/molnet/__init__.py
yapf -i deepchem/molnet/load_function/pdbbind_datasets.py
```

**Comment by bbrighttaer** [comment]
It's an honor, @rbharath. I will do as directed. Thanks.

**Comment by bbrighttaer** [comment]
Hello @rbharath, I just realized the check is failing again after running `yapf` on the modified files. Could you please check it and let me know what the problem might be? Thanks.

**Comment by mapleleaf-soar** [comment]
It seemed that the test on code format **passed** but that on installation of deepchem **failed** after `python setup.py install` refering to details in [The Travis CI jobs log](https://travis-ci.org/deepchem/deepchem/builds/497490411?utm_source=github_status&utm_medium=notification).
I'm new to deepchem and I also got the similar errors when following the [Installing from source in a conda environment](https://github.com/deepchem/deepchem/blob/master/README.md).
Thanks for any suggestion or correctiton. @bbrighttaer @rbharath

**Comment by rbharath** [comment]
@peastman Have you seen this failure before? Looks new on my end

**Comment by peastman** [comment]
What are you referring to?  The only errors I see in travis are unrelated stochastic failures in `test_gan.py` and `test_mcts.py`.

**Comment by peastman** [comment]
I'll rerun both the builds to make sure.

**Comment by rbharath** [comment]
I'm sorry this never got merged in! Looking at it now, the code looks good to me. I'm going to go ahead and merge this in (finally)

**Pull request merged**
