### PR TITLE
Add Python 3.11 Support

### PR DESCRIPTION
**Pull request by shreyasvinaya**
## Description

bump up python to 3.11

## Changelog

- Bump Up all tests to python 3.11
- Remove DQC tests - DQC is being added to deepchem
- Remove HHSuite as dependency for python 3.11

## Checklist

- [ ] Build Scripts
  - [x] Python 3.8
  - [x] Python 3.9
  - [x] Python 3.10
  - [ ] Python 3.11
- [x] Build Core
  - [x] Python 3.8
  - [x] Python 3.9
  - [x] Python 3.10
  - [x] Python 3.11
- [ ] Code Formatting
  - [ ] Python 3.8
  - [x] Python 3.9
  - [ ] Python 3.10
  - [ ] Python 3.11
- [ ] Docs
  - [ ] Python 3.8
  - [x] Python 3.9
  - [ ] Python 3.10
  - [x] Python 3.11
- [ ] Unit Test
  - [x] Python 3.8
  - [x] Python 3.9
  - [x] Python 3.10
  - [x] Python 3.11
  - [ ] All Tests Passing
    - [ ] Python 3.8 
    - [ ] Python 3.9
    - [ ] Python 3.10
    - [ ] Python 3.11
- [ ] Torch
  - [x] Python 3.8
  - [x] Python 3.9
  - [x] Python 3.10
  - [x] Python 3.11
  - [ ] All Tests Passing
    - [ ] Python 3.8 
    - [ ] Python 3.9
    - [ ] Python 3.10
    - [ ] Python 3.11
- [x] TF
  - [x] Python 3.8
  - [x] Python 3.9
  - [x] Python 3.10
  - [x] Python 3.11
  - [x] All Tests Passing
    - [x] Python 3.8 
    - [x] Python 3.9
    - [x] Python 3.10
    - [x] Python 3.11
- [x] Jax
  - [x] Python 3.9
  - [x] Python 3.10
  - [x] Python 3.11
  - [x] All Tests Passing
    - [x] Python 3.9
    - [x] Python 3.10
    - [x] Python 3.11

### CODE REVIEW

**Comment by GreatRSingh** [comment]
@shreyasvinaya hey, test-dqc is failing, you can undo changes to the changes from dqc environment if that cleans the CI a bit, because we are removing it in 1-1.5 month.

**Comment by shreyasvinaya** [comment]
I have had to remove hhsuite as a dependency, it doesnt support python 3.11, @GreatRSingh could you please look for hhsuite alternatives or we should consider adding the functionality of that to deepchem directly

**Comment by MischaPanch** [comment]
Hi. Quick question on the status here, do you plan on merging this?

**Comment by MischaPanch** [comment]
hhsuite seems to be no longer maintained, so I guess it's not good to have it as dependency, as it's holding you back. Supporting python 3.11 is very important as no new projects would want to use older versions of python.

Since I want to use deepchem in some of my projects, I either have to downgrade to python 3.10, or to split up repositories. Both options are a pain... Let me know if I can assist you in the move to 3.11

**Comment by shreyasvinaya** [comment]
Hi @MischaPanch, 
We are currently in discussions to merge this so it will be merged in the near future

**Comment by MischaPanch** [comment]
Great, happy to hear that, thanks for the quick answer!

**Review by rbharath — APPROVED** [review]
LGTM

**Pull request merged**
