### PR TITLE
Swapping split and transform order 

### PR DESCRIPTION
**Pull request by VIGS25**
I started to fix the order of train-valid-test split and the transformations on the data and I realized that the transformers would need to be separate for different datasets (as transformers take a dataset as argument). 

If a transformer takes a `train_dataset` as input, it would compute some statistics from that, which are later used to transform the valid and test, this would introduce dependencies between valid and train datasets and hence underestimate any downstream errors.

The current API of dc.load_xxx would then change to return transformers as a list of lists instead of list as returned now. ~~To the best of my knowledge, transformers are not reused explicitly anywhere after they are returned by the `load_XXX` function and hence changing the API a little will not be breaking, and even if it does, it would be minor.~~

A sample is shown for the `load_bace_classification`, and if alright with you guys, I will fix it similarly for all datasets.

Edit: `model.evaluate` uses transformers, for a dataset. Not sure whether to attempt to fix that, and break a lot of other things or just leave this situation as is

Thoughts - @rbharath & @peastman ?

### CODE REVIEW

**Comment by VIGS25** [comment]
Ah I see one test `TestGraphConvModel`, that uses the transformer returned from `load_function`, and throws up an error.

**Comment by peastman** [comment]
If we're considering changing the API, what about having the Dataset directly keep track of Transformers that have been applied to it?  This would be a bigger change, but it might also be cleaner.  Loading functions wouldn't need to return a list of Transformers, and `predict()` and `evaluate()` could get them from the Dataset so you wouldn't need to pass them in.  We should think carefully about the consequences of this change, though.  If Transformers were used when creating a Dataset, would we always want to apply them during prediction?  Are there times when you want it to apply additional Transformers that weren't used in creating it?

**Comment by VIGS25** [comment]
I would think this is a cleaner approach.

> If Transformers were used when creating a Dataset, would we always want to apply them during prediction?

If we are evaluating on a new dataset, different from the train-valid-test returned by the `load_*` method, then its better to apply the transformations while creating the dataset, and let the `predict()` or `evaluate()` function just run batches of the transformed dataset. 

> Are there times when you want it to apply additional Transformers that weren't used in creating it?

Do you have an example for this? - I am confused as to if it is ever done in a normal machine learning pipeline.

**Comment by VIGS25** [comment]
Thought about this - Realised I had a mistake in my thinking. The test dataset is also transformed with respect to the train statistics, so that they are on the same scale as what the model as learnt from. So we need only one transformer. (https://sebastianraschka.com/faq/docs/scale-training-test.html)

Closing this issue now, will reopen again with the others fixed as well.

**Pull request closed without merging**
