### PR TITLE
Enable passing empty list of tasks for prospective data prediction by classification GraphConvModel 

### LINKED ISSUE #1868: Screening of new molecules causes error
**Description:**

- DeepChem Version: 2.3.0
- Platform: Linux

This could be not a real issue but I could not figured out how to solve this.
According to sources `DataLoader` has a mandatory argument `tasks` which should be a list with names of activities. So, for test set prediction I have this column and I can specify it. But if I want to screen new compounds there is no activity columns in a file. I supposed that passing an empty list would work. But it does not.

So is it mandatory to pass some fake activity column to make prediction for new molecules or there is a more appropriate solution which I missed?

```
dataset_file = '1.smi'
featurizer_func = dc.feat.ConvMolFeaturizer()

# load test set - works
loader = dc.data.CSVLoader(tasks=['Activity'], smiles_field='smi', featurizer=featurizer_func)

# load set for screening - does not work
# loader = dc.data.CSVLoader(tasks=[], smiles_field='smi', featurizer=featurizer_func)

dataset = loader.featurize([dataset_file])
m_imb = dc.models.GraphConvModel(1, model_dir="modl")
m_imb.restore()
pred = m_imb.predict(dataset)
```
error message
```
Traceback (most recent call last):
  File "/home/pavel/python/deepchem-interp/pred.py", line 31, in <module>
    pred = m_imb.predict(dataset)
  File "/home/pavel/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/keras_model.py", line 711, in predict
    return self.predict_on_generator(generator, transformers, outputs)
  File "/home/pavel/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/keras_model.py", line 634, in predict_on_generator
    return self._predict(generator, transformers, outputs, False)
  File "/home/pavel/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/keras_model.py", line 544, in _predict
    for batch in generator:
  File "/home/pavel/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/graph_models.py", line 637, in default_generator
    y_b = to_one_hot(y_b.flatten(), self.n_classes).reshape(
AttributeError: 'NoneType' object has no attribute 'flatten'
```
I found that the `shard_generator` function from `data_loader` module assigns `None` value to `y` and `w` variables. `default_generator` from `GraphConvModel` class tries to make one-hot encoding of `y` which is actualy `None`.

### PR DESCRIPTION
**Pull request by MariBerry**
# Pull Request Template

## Description
Enable passing empty list of tasks for prospective data prediction by classification GraphConvModel 

Fix #1868

 Fix for  Issue  #1868 .  Bug fix: previously, when using classification GraphConvModel for prospective data prediction without passing activity ("tasks") raised an error. Now we can pass just an empty list and prediction will work OK.

## Type of change

Please check the option that is related to your PR.

-  Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

-  My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  -  Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  -  Run `mypy -p deepchem` and check no errors
  -  Run `flake8 <modified file> --count` and check no errors
-  I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
-  I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by rbharath — COMMENTED** [review]
Thanks for taking this on! Before I do a thorough review can you take a look at the failing Github actions tests? It looks like some of these changes are triggering failures in the test suite

**Comment by MariBerry** [comment]
Failed test_gan   is confusing me, because I made no changes to gan.py. Same with test_regression_dtnn. All I changed is one line (!) in class GraphConvModel (992) and it  seems to have passed your tests... Can you help solve it?

**Comment by rbharath** [comment]
Ah thank you for fixing the yapf errors! That makes this PR much cleaner to understand. I took a look through and I think that the tests that are failing are flaky so it might be fine.

Could you add a unit test case that #1868 has been fixed? That would enable to to make sure we don't accidentally break the fix in a future PR :). Also, if you haven't seen it already, https://deepchem.readthedocs.io/en/latest/development_guide/coding.html might be a useful resource. It explains our coding and testing conventions

**Comment by MariBerry** [comment]
> Could you add a unit test case that #1868 has been fixed? That would enable to to make sure we don't accidentally break the fix in a future PR :). Also, if you haven't seen it already, https://deepchem.readthedocs.io/en/latest/development_guide/coding.html might be a useful resource. It explains our coding and testing conventions

Added, although the test is much heavier then the change itself and seems unnecessary to me since the change is minor

**Comment by MariBerry** [comment]
So, is it ok now? can you merge it?

**Comment by MariBerry** [comment]
I made new commits, because i added new feature. BUT had to **revert** it all, becuse I saw that everything goes to the same PR, what i dont mean to do!  Sorry for that. Do I have to create new branch to **add new feature** while this PR is still open?

**Comment by rbharath** [comment]
@MariBerry Looks good! I'm going to hold off on merging shortly though since we've just frozen for the 2.4.0 release. This can make it into 2.4.1 I think though. I will merge in within the next couple of days

To answer your other question, yes each new feature should be a new branch. This can be a little tricky to get right, but a good rule of thumb is to always track your branch and keep each feature branch clean and separate.

**Comment by rbharath** [comment]
Merging in now that DeepChem 2.4.0 is out! This should make it out in 2.5.0 coming out end of February :)

**Pull request merged**
