### PR TITLE
Fix bug in metric computing

### PR DESCRIPTION
**Pull request by zealseeker**
When sample number is 1, `y_pred` will be squeezed and `y_pred[:, 1]` will raise error.

The bug was not detected because we only use auc as the metric in classification, which doesn't have a threshold. it will fail when we use other metrics like recall.

There was warning during https://github.com/deepchem/deepchem/blob/26ecc32158d5f62f0e08449e10b958d1401081fd/deepchem/hyper/tests/test_hyperparam_opt.py#L114
but was just ignored.

There might be better solutions but at least now the programme won't raise the error anymore.

To be safer, I just used the condition `self.threshold is not None` to avoid potential mistake in other circumstances (like regression mode). And the warning still exists.
```
Straightforward test of Tensorflow multitask deepchem classification API. ... C:\Anaconda3\envs\dc\lib\site-packages\deepchem\metrics\__init__.py:370: UserWarning: Error calculating metric mean-roc_auc_score: Found input variables with inconsistent numbers of samples: [1, 2]
  warnings.warn("Error calculating metric %s: %s" % (self.name, e))
C:\Anaconda3\envs\dc\lib\site-packages\deepchem\metrics\__init__.py:370: UserWarning: Error calculating metric mean-roc_auc_score: Found input variables with inconsistent numbers of samples: [1, 2]

Test of TensorGraph singletask deepchem classification API. ... C:\Anaconda3\envs\dc\lib\site-packages\deepchem\data\data_loader.py:269: FutureWarning: featurize() is deprecated and has been renamed to create_dataset(). featurize() will be removed in DeepChem 3.0
  FutureWarning)
C:\Anaconda3\envs\dc\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
C:\Anaconda3\envs\dc\lib\site-packages\deepchem\metrics\__init__.py:370: UserWarning: Error calculating metric matthews_corrcoef: Classification metrics can't handle a mix of continuous and binary targets
  warnings.warn("Error calculating metric %s: %s" % (self.name, e))
C:\Anaconda3\envs\dc\lib\site-packages\deepchem\metrics\__init__.py:370: UserWarning: Error calculating metric recall_score: Classification metrics can't handle a mix of continuous and binary targets
  warnings.warn("Error calculating metric %s: %s" % (self.name, e))
C:\Anaconda3\envs\dc\lib\site-packages\deepchem\metrics\__init__.py:370: UserWarning: Error calculating metric accuracy_score: Classification metrics can't handle a mix of continuous and binary targets
  warnings.warn("Error calculating metric %s: %s" % (self.name, e))
C:\Anaconda3\envs\dc\lib\site-packages\deepchem\metrics\__init__.py:370: UserWarning: Error calculating metric roc_auc_score: Only one class present in y_true. ROC AUC score is not defined in that case.
  warnings.warn("Error calculating metric %s: %s" % (self.name, e))
...
```

### CODE REVIEW

**Comment by rbharath** [comment]
@zealseeker Thank you for the fix! Would it be possible to add a simple unit test that failed under the original code but which this change fixes? That would help us keep track of this issue in future changes

**Comment by zealseeker** [comment]
Hi @rbharath . Is this unit test OK?
Do I need to yapf it to pass the test? But I find that my local yapf result is different from what it should be in CI test.

**Comment by rbharath** [comment]
Could you add a brief docstring to the test explaining what it's testing for? I think it looks good otherwise.

For `yapf`, I think you might possibly have a different `yapf` version. Can you check that you have 
```
$ yapf -- version
yapf 0.22.0
```

**Comment by rbharath** [comment]
@zealseeker This looks great! Going to go ahead and merge in :)

**Pull request merged**
