### PR TITLE
Lower learning rate of a3c test for robustness

### PR DESCRIPTION
**Pull request by lilleswing**
Lower learning rate of a3c test for robustness

### CODE REVIEW

**Comment by peastman** [comment]
Does that actually make it more robust?

**Comment by lilleswing** [comment]
@peastman I did 20 runs with both -- 10 errors with old learning rate 2 errors with new learning rate.  If 2/20 is the true learning rate and we do it twice (@flaky the test) we will only fail 1% of builds because of this test.

**Comment by peastman** [comment]
Let me do some experiments.  I wasn't getting a failure rate anything close to that.

**Comment by lilleswing** [comment]
@peastman python 3.5 is giving the issues -- 2.7 seems fine from the travis runs we have seen.

**Comment by peastman** [comment]
All my testing is on Python 3.

**Comment by peastman** [comment]
I just ran it 10 times and only got one failure.  Also, if the learning rate was the problem, that wouldn't explain the behavior being different on Python 2.7 and 3.5.

**Comment by rbharath** [comment]
I'm going to go ahead and merge this PR in (all our PRs look to fail travis except this one).

LGTM.

**Comment by peastman** [comment]
I wish you hadn't.  I'm quite sure this PR isn't getting at the real problem.

**Comment by rbharath** [comment]
You might quite well be right. On the other hand, all the other PRs have now turned green :)

Perhaps let's keep this one as a stopgap fix for now, and we can address the deeper issue in a follow-up?

**Pull request merged**
