### PR TITLE
Simplified names of TensorGraphMultiTask models

### PR DESCRIPTION
**Pull request by peastman**
This was discussed in #754.

### CODE REVIEW

**Comment by peastman** [comment]
When did doctests get turned on?  Travis is failing with a doctest error in an unrelated file.  And it's actually just an example in a docstring that was never intended to be a test.

**Comment by lilleswing** [comment]
Doctests got turned on February 16th.  Not sure why it is complaining now and not before though....

**Comment by lilleswing** [comment]
```bash
find ./deepchem | grep .py$ |xargs python -m doctest -v
```

**Comment by peastman** [comment]
Ok, ready to merge.

**Comment by rbharath** [comment]
@peastman Looks really nice! Much more readable names now :)

LGTM

**Pull request merged**
