### PR TITLE
Website Overhaul

### PR DESCRIPTION
**Pull request by rbharath**
Will add more details once this is ready to merge. Mostly functional, but need to fix a couple issues and make sure Travis scripts work.

### CODE REVIEW

**Comment by rbharath** [comment]
The new website is now live at http://deepchem.io.s3-website-us-west-1.amazonaws.com/! (Changes should propagate to https://deepchem.io over next several hours).

The core design of the website was borrowed from pytorch.org. Credits for the new logo and banner go to @aanara (who also made the original deepchem logo). The new docs website now renders IPython notebooks on the website. Just the BACE notebook for now, but future PRs will add other notebooks. (H/T @cxhernandez for pointers to https://github.com/msmexplorer/msmexplorer notebook rendering).

@lilleswing, @peastman Would you mind reviewing these changes? The website generation code is one of the least reviewed parts of deepchem so it would be good to get more eyeballs on this code.

**Comment by lilleswing** [comment]
New site looks great! 

### Broken Links
```html
<a class="btn" href="https://github.com/deepchem/examples">Explore Examples</a>
<a class="btn" href="http://deepchem.io/tutorials/">Browse Tutorials</a>
```
I think you meant for the Learn More button to go here
selection_094
http://deepchem.io.s3-website-us-west-1.amazonaws.com/support/
It currently goes here
http://deepchem.io.s3-website-us-west-1.amazonaws.com/about.html
which just talks about how great pytorch is.  Some of the current links on Learn More are also broken.
The About/Support links in the footer have the same issues.
selection_096


### Conda Install Strings
selection_095
for python version you have to add
```bash
python=$python_version
```
to the conda command.

### Would Be Nice
Make Schrodinger link to https://www.schrodinger.com/

**Comment by lilleswing** [comment]
I made the changes here --
https://github.com/lilleswing/deepchem/commit/9b6e799bc17911fc52509091c74c139a2f1bfc4d

I also added a favicon -- you were loading one without it existing.

**Comment by lilleswing** [comment]
The code for creating the docs and uploading them LGTM.

**Comment by peastman** [comment]
When you click the "Learn More" button, it takes you to a page about PyTorch.  Very confusing!

**Comment by peastman** [comment]
Most of the links don't do what you'd expect.

"About" does take you to an about page.  But it also is a completely different looking one with different links at the top.  It looks like you've just jumped to a different site.

"Docs" doesn't take you to any sort of documentation page.  Instead, it takes you to exactly the same page as "About".

"Support" just takes you to the front page for the Github repository.  Especially for someone who isn't familiar with Github, they'll have no idea how they're supposed to get support from that page.

"Explore Examples" leads to a 404 error page.

"Browse Tutorials" leads to an "Access Denied" error page.

**Comment by peastman** [comment]
If you select OS X along with conda or pip, you get the message, "DeepChem on OSX coming soon!"  That makes people think we don't currently support OS X.  We should clarify that it's only the conda and pip installers that aren't available, and they can still install from source.

As far as I can tell, the "Python" and "CUDA" options have no effect on anything.  So why are they there?

**Comment by rbharath** [comment]
@lilleswing Thanks for the updates! Fixes incorporated.

@peastman Removed the CUDA option.

The updated site is now up at http://deepchem.io.s3-website-us-west-1.amazonaws.com/ (will take several hours to propagate to deepchem.io as before). All links should now work and point to reasonable places.

Once Travis passes, I'll merge in this PR since the travis update code can only be tested upon PR merge. Will make further needed fixes in a follow-up PR.

**Comment by rbharath** [comment]
Tentatively, it looks like the Travis Push worked successfully.

**Pull request merged**
