### PR TITLE
changed GPL to MIT license

### PR DESCRIPTION
**Pull request by ankitvgupta**
Addresses https://github.com/deepchem/deepchem/issues/1120

### CODE REVIEW

**Comment by rbharath** [comment]
@ankitvgupta Thanks for the PR! Would you mind running yapf over the modified files? We should be able to merge in then:

```
pip install yapf
yapf -i deepchem/feat/atomic_coordinates.py
deepchem/feat/basic.py
deepchem/feat/coulomb_matrices.py
deepchem/feat/fingerprints.py
deepchem/feat/tests/test_sdf_reader.py
examples/binding_pockets/binding_pocket_rf.py
examples/pdbbind/pdbbind_rf.py
examples/pdbbind/pdbbind_tf.py
```

**Comment by ankitvgupta** [comment]
@rbharath done! Looks like there was only one file affected. Will try again if that fails in case I did something wrong.

**Comment by rbharath** [comment]
Hmm, I think there's a bug in the automatic printout. You might need to manually run `yapf` on all modified files. So:

```
yapf -i deepchem/feat/atomic_coordinates.py
yapf -i deepchem/feat/basic.py
yapf -i deepchem/feat/coulomb_matrices.py
yapf -i deepchem/feat/fingerprints.py
yapf -i deepchem/feat/tests/test_sdf_reader.py
yapf -i examples/binding_pockets/binding_pocket_rf.py
yapf -i examples/pdbbind/pdbbind_rf.py
yapf -i examples/pdbbind/pdbbind_tf.py
```

**Comment by ankitvgupta** [comment]
Yep that's what I did. Looks like only one file was affected.

**Comment by ankitvgupta** [comment]
Woohoo!

**Pull request merged**
