### PR TITLE
Fix commented code in tutorial 3

### PR DESCRIPTION
**Pull request by neel-shah**

### CODE REVIEW

**Comment by peastman** [comment]
> /usr/local/lib/python3.6/dist-packages/deepchem/data/data_loader.py:162: FutureWarning: featurize() is deprecated and has been renamed to create_dataset().featurize() will be removed in DeepChem 3.0
  "featurize() will be removed in DeepChem 3.0", FutureWarning)

How about also changing that call from `featurize()` to `create_dataset()` to get rid of this warning?

**Comment by rbharath** [comment]
@neel-shah Looks good on my end! Once @peastman's suggestion is addressed I think we should be good to merge in

**Comment by neel-shah** [comment]
Thanks @peastman for the comment! I fixed it in the new commit.

**Comment by peastman** [comment]
That looks good.  One other thing you might want to do is rerun the notebook after getting the latest code updates.  The output includes a bunch of warnings about "n_samples is a deprecated argument which is ignored."  That was just fixed earlier today in #2118.

**Comment by neel-shah** [comment]
> rerun the notebook after getting the latest code updates
IIUC we run colab code on the deepchem built from the master, correct? Do I need to do update my code?

I tried running the code again but it still shows the deprecated warnings.

**Comment by rbharath** [comment]
The colab version runs from the latest nightly build, which should have incorporated the fix. It's possible #2118 didn't fix the warning though? Would it be possible for you to try running the notebook locally (instead of on colab) on a freshly installed nightly build to see if you're still getting the deprecation warning?

**Comment by neel-shah** [comment]
I followed the steps in https://deepchem.readthedocs.io/en/latest/installation.html#nightly-build-version to install nightly version of deepchem.

```
(deepchemenv) neelshah-macbookpro1:deepchem neelshah$ python3
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:10:22)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepchem

>>>
>>> deepchem.__version__
'2.4.0-rc1.dev'
```

It shows me exactly same version as what I see on colab. I think the warnings might not have been fixed actually (but please let me know if you still think I should run the colab locally).

**Comment by rbharath** [comment]
Ah the version for all the nightly builds is `2.4.0-rc1.dev` (We don't update the version string for nightly build versions). If possible, it would be useful to try running the notebook locally to see if the warning is still appearing locally. (This would let us know whether we still need to fix the warning)

**Comment by nd-02110114** [comment]
I think the version which includes #2189 modification didn't publish because the CI failed by a strange reasons (this is crashing, not lint or test error) in master branch. Now, I rerun the CI in mater branch. If the CI pass (I think the CI will pass), we could use the version includes #2189 modification.

**Comment by nd-02110114** [comment]
Published the new package
https://pypi.org/project/deepchem/2.4.0rc1.dev20200826012110/#history

**Comment by rbharath** [comment]
@nd-02110114 Great, thanks for the fix! @neel-shah Could you try rerunning on colab to see if the warnings disappear?

**Comment by neel-shah** [comment]
The warnings are gone :)

**Pull request merged**
