### PR TITLE
Rdkit Grid Featurizer For Pdbbind benchmark

### PR DESCRIPTION
**Pull request by lilleswing**
A bad merge of Sequential Models forced me to create a new branch/pull request.  
Old PR
https://github.com/deepchem/deepchem/pull/436

Gets comparable results on the benchmark without using Openbabel.  We use Pdbfixer to clean up the inputs.

|Algorithm | Dataset | Train | Validate | 
| -- | -- | --| --|
| OB | Refined | 0.963 | 0.511 |
| OB | Full | 0.983 | 0.528 | 
| rdkit | Refined | .98 | .565 |
| rdkit | Full | .97 | .48 | 

### Notes:
I still have not implemented Hydrogen Bonds.  Currently I assume no two atoms create hydrogens bonds with each other.

_is_salt_bridge needs some test cases.  While we are supposedly calculating the same charges I worry that there are differences in units/magnitudes between rdkit charges and OB charges.  We use the exact same algorithm and magnitudes for attempting to see if there are salt bridges.

I use Pdbfixer for BOTH the ligands and proteins. ~~In order to do the ligands I write the ligand to a temprary file in .pdb format so Pdbfixer can read it in.  It would be nice if Pdbfixer could read from a StringIO object instead of a string filename~~

You are supposed to use an encoding magic comment if you have utf-8 characters in your comments
https://www.python.org/dev/peps/pep-0263/

### Next Steps:
There is still a lot of usage of OpenBabel in the docking package (even though none of that code is used for any benchmarks).  I will slowly port it over attempting to keep passing existing tests.

Still Open Issues:
1) Using mdtraj to find hydrogen bonds @evanfeinberg @cxhernandez
Right now we load the protein and ligand in separately to PDBFixer.  We would have to load in the merged representation into PDBFixer again and only count hydrogen bonds between the merged entities.
```python
def is_hydrogen_bond(protein_xyz, protein, ligand_xyz, ligand, contact,
                     hbond_angle_cutoff):
```
so we already have xyz coordinents of both protein and ligand.  Is it feasable to calculate hydrogen bonds via mdtraj using this api?

### CODE REVIEW

**Comment by lilleswing** [comment]
@rbharath this one is verified to be hitting the benchmarks.  Ready to merge when travis is green.

**Comment by cxhernandez** [comment]
> so we already have xyz coordinents of both protein and ligand. Is it feasable to calculate hydrogen bonds via mdtraj using this api?

Assuming `protein` and `ligand` are topologies. This should work just fine.

To generate an `mdtraj.Trajectory` object from a `pdbfixer.PDBFixer` one, you can do the following:

```python
import numpy as np
from pdbfixer import PDBFixer
import mdtraj as md

fixer = PDBFixer('my_file.pdb')

xyz  = np.array(fixer.positions._value)
top = md.Topology.from_openmm(fixer.topology)

traj = md.Trajectory(xyz, top)
```

You'll also have to add the ligand to the protein system for the cal.

As far as setting `contact` and `hbond_angle_cutoff`, MDTraj has three standard methods: [`baker_hubbard`](http://mdtraj.org/1.8.0/api/generated/mdtraj.baker_hubbard.html#mdtraj.baker_hubbard), [`kabsch_sander`](http://mdtraj.org/1.8.0/api/generated/mdtraj.kabsch_sander.html?highlight=kabsch#mdtraj.kabsch_sander), and [`wernet_nilsson`](http://mdtraj.org/1.8.0/api/generated/mdtraj.wernet_nilsson.html#mdtraj.wernet_nilsson). Each one has different hard-coded criteria for those parameters, so you might have to dig through the source code if you want to set them yourself.

**Comment by peastman** [comment]
This line is dangerous:

```Python
xyz  = np.array(fixer.positions._value)
```

You're assuming the values will be in nanometers, which isn't guaranteed.  Here's a better way to write it:

```Python
import simtk.unit as unit
...
xyz = np.array(fixer.positions.value_in_unit(unit.nanometers))
```

**Comment by rbharath** [comment]
@lilleswing Looks good! Let's merge in once @peastman's comment is addressed.

**Comment by miaecle** [comment]
@lilleswing @rbharath A quick question, are the featurized datasets on aws up to date? Planning to directly use featurized data in benchmarking and molnet module.

**Comment by rbharath** [comment]
Yes, I believe so. @joegomes uploaded the new ones yesterday I believe.

**Comment by joegomes** [comment]
@miaecle Yes they are up to date

**Pull request merged**
