### PR TITLE
Use tf.matmul for batch matrix multiplication in MPNN's Edge Network

### PR DESCRIPTION
**Pull request by WesleyyC**
Please see #1188 for details.

### CODE REVIEW

**Comment by WesleyyC** [comment]
I think the build is failing on
```
The command "nosetests --with-flaky -a '!slow' --with-timer --with-coverage --cover-package=deepchem -v deepchem --nologcapture" exited with 1.
```

Can you advise?

**Comment by miaecle** [comment]
The fail seems to be from HingeLoss error, which will be fixed in #1189 . You could pull the master branch after that PR is been merged.

**Comment by lilleswing** [comment]
PR #1189 has been merged.

**Comment by WesleyyC** [comment]
Closing and creating a new one due to some minor git mess up.

**Pull request closed without merging**
