### PR TITLE
Splitting function and argparse 

### PR DESCRIPTION
**Pull request by miaecle**
This PR merges choice of different splitting function(index, random, scaffold) into benchmark script, and adds args to simplify running:
-m, choice of model
-d, choice of dataset
-s, choice of splitting function

### CODE REVIEW

**Comment by rbharath** [comment]
@miaecle Very cool! Thanks for getting this in quickly. Could you update README.md with the new benchmark numbers for the different splits?

**Comment by miaecle** [comment]
@rbharath I have included performances for random splitting(this is actually not based on constant tf seed) and scaffold splitting(this is based on constant seed). Still working on a full run of benchmark to give all the performances based on constant seed.

**Comment by rbharath** [comment]
@miaecle Code looks good! One quick request before merging: Could you move the dataset sizes into a separate table so that the index split performances table looks like the random/scaffold split table? That should clean up the presentation nicely.

**Comment by miaecle** [comment]
@rbharath Thanks a lot for checking the codes! I also think there should be better ways to present the performances, like should we put all performances(of 3 splitting methods) together into a big chart or keep to the three small ones?

**Comment by rbharath** [comment]
@miaecle I actually like the three small charts (it emphasizes that the numbers between different splits aren't directly comparable). I think the only change we should do is make the first chart look like the others and make a separate table for dataset info (N-samples/N-tasks for all datasets)

**Comment by miaecle** [comment]
@rbharath OK got it! I will make the change, so we still keep the time for running in the first chart and separate the number of examples.

**Comment by rbharath** [comment]
@miaecle LGTM! Will merge once tests finish running.

**Comment by miaecle** [comment]
@rbharath Thanks for the suggestion! Also, would you mind waiting for another day to get the stable performances for index splitting(I am currently running it)? or I can just do another PR after it is finished.

**Comment by rbharath** [comment]
@miaecle No worries, will wait for the stable performances for index splitting. As another thought, it might make sense to spit the load/run times into a separate table as well (so the index table would look exactly like other two tables), and we'd have a timings table and dataset-info table for a total of 5 tables.

**Comment by miaecle** [comment]
@rbharath Yes, I totally agree with that! It will be much more tidy to have all the things paralleled and separated. Hopefully, I will update the chart tomorrow with the time separated too.

**Pull request closed without merging**
