### PR TITLE
MaxMin Splitter implementation.

### PR DESCRIPTION
**Pull request by proteneer**
This implements #889 as a new split. Note that this works with older versions of the RDKit as well, but it is significantly faster with the 2017.9 release.

I used the default settings of:

1. DiceSimilarity
2. 1024 bit radius 2 morgan finger prints
3. I could reset the seed to something else, not sure what's the best way to handle this.

@miaecle Would be cool to include this as a new benchmark option.

### CODE REVIEW

**Comment by proteneer** [comment]
Also, for all practical purposes, this will be fast enough with the new RDKit for all datasets of < 10 million.

**Comment by rbharath** [comment]
@proteneer This is a cool feature! Having better splits will make our benchmarks more meaningful, and now that moleculenet.ai benchmarks run on Jenkins, we should be able to incorporate them.

Should be good to merge once tests pass.

**Comment by proteneer** [comment]
I think RDKit changed the API recently. I'm using 2016.9 which I think has a different API for this than 2017.3.

**Comment by lilleswing** [comment]
None is not an int -- I finished the CR up for you.

**Pull request merged**
