### PR TITLE
[WIP] #1143: Molecular Featurization Tutorial

### PR DESCRIPTION
**Pull request by VIGS25**
Addressing #1143 , this PR adds in the tutorial for featurizing molecules. 

1. Tutorials for `BPSymmetryFunction`, `CoulombMatrix`, `CoulombMatrixEig` and `RDKitDescriptors` have been added.
2. Tutorials for `ConvMolFeaturizer`, `WeaveFeaturizer`, `CircularFingerprints` and `AdjacencyFingerprint` is left.

@rbharath: Thoughts on the same?

### CODE REVIEW

**Comment by rbharath** [comment]
@VIGS25 This looks great! I'd recommend adding this to the new `examples/tutorials` series. That way, it can be part of a "curriculum" for new DeepChem users

**Comment by VIGS25** [comment]
Done!

**Comment by rbharath** [comment]
Sorry, just realized I never merged this in! Merging it in now :)

**Comment by VIGS25** [comment]
Ah my bad, this is still missing the 4 featurizers, but the 'Done' was for adding it to `examples/tutorials`.

**Pull request merged**
