### PR TITLE
Fix failing slow test

### PR DESCRIPTION
**Pull request by peastman**
This fixes almost all of the remaining slow tests that were failing.  It turned out that AtomicConvFeaturizer had never been converted to work with Keras, so it had been broken for a while.  Apparently no one noticed?  I also modified VinaPoseGenerator to work on Mac and Windows.  Previously it was written in a way that only worked on Linux.

The one failure I'm still stuck on is `test_atomic_conv()` in test_atomic_conv.py.  The output of the model in that test is exactly 0, both before and after training.  It seems to be incapable of outputting any other value, but I haven't figured out why.  Does anyone else have an idea?

### CODE REVIEW

**Comment by rbharath** [comment]
This PR looks great!

The bug in `test_atomic_conv.py` is unfortunate. It suggests `AtomicConvModel` isn't actually training properly... I can take a debugging pass on this in a bit.

**Comment by rbharath** [comment]
Took a look at Travis and it looks like there are number of Travis failures from KerasModel for some reason. It's not clear what in this PR could have caused it. Do you have ideas on what might be causing the issues?

**Comment by peastman** [comment]
I think this is ready to merge.  The one test failure is in `test_roulette`, which isn't related to this PR.

**Comment by rbharath** [comment]
Sounds good! Thanks for the fixes here :)

**Pull request merged**
