### PR TITLE
Changes to allow testing of pcba_128 alongside updated pcba_146 dataset

### PR DESCRIPTION
**Pull request by LRParser**
I suggest that we add a new dataset, pcba_146, alongside the traditional pcba_128 dataset, which will provide a usage pattern for tests into whether larger networks continue to improve performance. I had hoped to see that multitask learning would have provided a further improvement, but unfortunately it showed only a small change:

pcba_128,index,classification,tf,mean-roc_auc_score,train,0.792290689036,valid,0.714256217171,test,0.716932458805,time_for_running,2431.0320513248444
pcba_128,random,classification,tf,mean-roc_auc_score,train,0.776874830358,valid,0.736164697428,test,0.744172976222,time_for_running,2412.287951231003
pcba_146,index,classification,tf,mean-roc_auc_score,train,0.781317893135,valid,0.705518067369,test,0.7089313186,time_for_running,2778.7728264331818
pcba_146,random,classification,tf,mean-roc_auc_score,train,0.779320325446,valid,0.739823827805,test,0.744264509328,time_for_running,2725.5335505008698

It seems that for a random split pcba_146 performs slightly better, for an index split pcba_128 performs somewhat better. Hopefully this is a good starting point for folks to look into further multitask learning comparisons. Perhaps the additional 18 assays just aren't enough (yet) to show more than just a slight improvement in AUC.

### CODE REVIEW

**Comment by rbharath** [comment]
Sorry for the slow review; been sick the last few days and just catching up.

I like the idea of adding on more assays, but is there a particular reason for choosing the extra 18 assays in PCBA 146? I believe the original 128 were those that met some size criteria in a query to PCBA.

**Comment by LRParser** [comment]
The 146 was all of the original 128 that met the query when it was first run (perhaps in 2016?) plus all those that now meet the same criteria (in 2018) - so it is 18 more than the original 128. Perhaps this is why it is not large enough to show improved learning. In another PR I will try to see if other datasets converge better. The gene-linked assays were promising but I do not know how to turn them into a benchmark just yet. In any case - hope you are feeling better and congrats on the PhD defense!

**Comment by rbharath** [comment]
Ah that makes sense. Have you verified that the generated pcba-128 dataset matches the original pcba dataset? If so I think we should be good to merge.

**Comment by LRParser** [comment]
Thanks for feedback. Working on verifying via pandas pd.equals and will update this in a few days

**Comment by LRParser** [comment]
I messed up the rebase - creating a new PR.

**Pull request closed without merging**
