### PR TITLE
Splitter Tutorial

### PR DESCRIPTION
**Pull request by abster12**
Made the changes to the tutorial as recommended and added a test for IndiceSplitter

### CODE REVIEW

**Comment by abster12** [comment]
I added all the splitters and made changes according to your recommendations. Could you please review it again.

**Comment by lilleswing** [comment]
The tutorial looks great!

You need to format the code edited in this branch though.

```python
yapf -i deepchem/splits/tests/test_splitter.py
```

**Comment by lilleswing** [comment]
Is this still [WIP]?  or is it complete?  it looks good to me.

**Comment by abster12** [comment]
Its complete.

**Comment by lilleswing** [comment]
It is live on our website
https://deepchem.io/docs/notebooks/Splitters_Tutorial.html

**Comment by rbharath** [comment]
Congrats @abster12! This is a great contribution to the project :)

**Pull request merged**
