### PR TITLE
Can create a PyTorch Dataset from a DeepChem Dataset

### LINKED ISSUE #1800: Create PyTorch dataset
Since our goal is for DeepChem's Dataset class to easily interoperate with all machine learning frameworks, I'd like to add support for creating a PyTorch Dataset from it.  I think this will mostly be simple: just create a subclass of torch.utils.IterableDataset that iterates over the data.  A little care will be needed to work correctly with multiprocessing, but that shouldn't be hard.

I don't want to actually add PyTorch as a dependency of DeepChem, of course.  I can mostly handle that by only importing it inside the function.  The test cases will need to import it too, of course, so for the moment I might mark those tests as slow so travis won't try to run them.  Once we migrate molnet into its own repository, we can include PyTorch in the CI for that repo.

### PR DESCRIPTION
**Pull request by peastman**
Fixes #1800.  I think I have the tests set up correctly so they'll just be skipped if PyTorch isn't installed (since it isn't on travis).

### CODE REVIEW

**Comment by peastman** [comment]
Travis builds are passing: https://travis-ci.org/github/deepchem/deepchem/builds/674958377

**Comment by peastman** [comment]
I'm trying to figure out how to get travis results to show up again, but apparently I don't have permission to access the deepchem organization on travis.

**Comment by rbharath** [comment]
I checked just now and it appears I don't have permissions either! I'm not entirely sure what's happening. Travis-CI looks to be authorized for the deepchem github org, but it's not showing up on their page

**Comment by rbharath** [comment]
The PR looks good! Going to merge in

**Pull request merged**
