### PR TITLE
Update torchvision version requirement

### LINKED ISSUE #2915: env_torch.gpu.yml requires conflicting versions (torch and torchvision 0.11)
## 🐛 Bug

env_torch.gpu.yml requires both torch and torchvision 0.11, resulting in error when installing:

```
The conflict is caused by:
    The user requested torch==1.11.0+cu113
    torchvision 0.11.0+cu113 depends on torch==1.10.0+cu113
```

## To Reproduce

Run `conda env update --file env_torch.gpu.yml`

```
The conflict is caused by:
    The user requested torch==1.11.0+cu113
    torchvision 0.11.0+cu113 depends on torch==1.10.0+cu113
```

Expect the versions to be compatible.

## Environment

* OS: Windows 11 (WSL2 Ubuntu)
* Python version: 3.8

### PR DESCRIPTION
**Pull request by Matthew-Hostetler**
# Pull Request Template

## Description

Fixes #2915 

## Type of change

Please check the option that is related to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [ ] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rbharath** [comment]
@Matthew-Hostetler Thanks for the PR!

@arunppsg Could you take a quick look when you get a chance and confirm version update is fine?

**Comment by Matthew-Hostetler** [comment]
Seems there is some flakiness with tests, though I did spot what looks like an import error for `test_tensorboard` in some of the Torch tests.

I am not sure how this was working before though, if previously the versions were incompatible?

**Comment by Matthew-Hostetler** [comment]
The import error is for `torch.utils.tensorboard` which should be unaffected by this change though.

**Comment by arunppsg** [comment]
LGTM! The import error is not related to this PR. It's something which we have to fix separately. Thanks for your contribution!

**Pull request merged**
