### PR TITLE
Add link to README.md

### PR DESCRIPTION
**Pull request by hsiaoyi0504**

### CODE REVIEW

**Comment by rbharath** [comment]
@hsiaoyi0504 Thanks for the fix! Once you've signed the CLA, we should be good to merge.

**Comment by hsiaoyi0504** [comment]
@rbharath Already done that ! Thanks !

**Comment by lilleswing** [comment]
I fixed the doc tests here (https://github.com/deepchem/deepchem/pull/1013)
I still don't know why it changed though.... but just merge my request in first.

**Comment by rbharath** [comment]
@hsiaoyi0504 Congrats on your first merged DeepChem PR!

LGTM

**Pull request merged**
