### PR TITLE
Update models.rst

### LINKED ISSUE #2827: Docs of JaxLayers not rendering
## 🐛 Bug

In DeepChem docs for Jax layers, [PINNModel](https://deepchem.readthedocs.io/en/latest/api_reference/models.html#jax-models), for some reason, the docs of `PINNModel` is not getting rendered. This might relatively be a simple fix.

### PR DESCRIPTION
**Pull request by neerajanand-coder**
# Pull Request Template

## Description

Fix #2827 

## Type of change

Please check the option that is related to your PR.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - In this case, we recommend to discuss your modification on GitHub issues before creating the PR
- [ ] Documentations (modification for documents)

## Checklist

- [X] My code follows [the style guidelines of this project](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html)
  - [ ] Run `yapf -i <modified file>` and check no errors (**yapf version must be  0.22.0**)
  - [ ] Run `mypy -p deepchem` and check no errors
  - [ ] Run `flake8 <modified file> --count` and check no errors
  - [ ] Run `python -m doctest <modified file>` and check no errors
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New unit tests pass locally with my changes
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by arunppsg** [comment]
I just copied the change to my local and rendered the docs and I was not able to view the updates. Perhaps, this can be a local problem in my machine. Maybe can you install sphinx and check once whether the docs get properly rendered?

**Comment by neerajanand-coder** [comment]
Sure sir

**Comment by neerajanand-coder** [comment]
Sir,
I have checked, the docs get properly rendered.

**Comment by arunppsg** [comment]
LGTM! I hope the docs for `JaxModels` and `dc.models.PINNModel` will get rendered properly. I will merge it in. Thanks for the PR!

**Pull request merged**
