### PR TITLE
Install tensorflow with conda

### PR DESCRIPTION
**Pull request by lilleswing**
Install Tensorflow with Conda.

I'll also test after Travis passes if we can upgrade to 1.1.0.

### CODE REVIEW

**Comment by lilleswing** [comment]
Installing tensorflow-gpu via conda causes rdkit to roll back to it's 2015 version which breaks a lot of things :(

selection_016

**Comment by mwojcikowski** [comment]
Do you have omnia channel active all the time? I had similar issues with rdkit, for some reason conda packages of RDKit lock Numpy version, but RDKit itself is really generous in that term... 

Maybe it would be best to separate deepchem channel with no further dependencies, or at least fewer like conda-forge.

**Comment by lilleswing** [comment]
@mwojcikowski a single conda install would be great.  We have omnia deepchem but it is very old (< 1.0.0).  Any work on a single conda recipe would be greatly appreciated!  (Right now we are running into more installation problems due to dependencies changing and lib_boost even on mainline)

**Comment by rbharath** [comment]
@lilleswing I believe @cxhernandez updated omnia to run the latest DeepChem recently.

**Pull request closed without merging**
