### PR TITLE
Fixed writing to tensorboard from callback

### LINKED ISSUE #2245: Using ValidationCallback callback with Tensorboard produces error
Following up on a Gitter convo, which I will paste below:
Using Deepchem nightly build from earlier this week ('2.4.0-rc1.dev').

I am trying to use the ValidationCallback callback with Tensorboard active in the model. I am getting the following error (I'll put the full trace at the end, for tidiness):
`AttributeError: 'GraphConvModel' object has no attribute '_log_value_to_tensorboard'`

I looked for the `_log_value_to_tensorboard` function through the inherited classes, and could not find it. Am I missing something, or is logging to Tensorboard not implemented for use with ValidationCallback?

Here are the commands I am executing when the error occurs:
```
callbacks = [
    dc.models.ValidationCallback(
        dataset=val_dataset,
        interval=200,
        metrics=metrics,
        save_dir=val_dir ,
        save_on_minimum=True
    )
]
gcm = dc.models.GraphConvModel(
    n_tasks=1, 
    mode='regression', 
    model_dir=log_dir, 
    tensorboard=True, 
    log_frequency=10
)
gcm.fit(
    train_dataset, 
    nb_epoch=5, 
    callbacks=callbacks
)
```

Here is the full traceback:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-134-5c50388e74e5> in <module>
----> 1 gcm.fit(train_dataset, nb_epoch=1, callbacks=callbacks)

~/miniconda3/envs/astar/lib/python3.7/site-packages/deepchem/models/keras_model.py in fit(self, dataset, nb_epoch, max_checkpoints_to_keep, checkpoint_interval, deterministic, restore, variables, loss, callbacks, all_losses)
    324             dataset, epochs=nb_epoch,
    325             deterministic=deterministic), max_checkpoints_to_keep,
--> 326         checkpoint_interval, restore, variables, loss, callbacks, all_losses)
    327 
    328   def fit_generator(self,

~/miniconda3/envs/astar/lib/python3.7/site-packages/deepchem/models/keras_model.py in fit_generator(self, generator, max_checkpoints_to_keep, checkpoint_interval, restore, variables, loss, callbacks, all_losses)
    432         manager.save()
    433       for c in callbacks:
--> 434         c(self, current_step)
    435       if self.tensorboard and should_log:
    436         with self._summary_writer.as_default():

~/miniconda3/envs/astar/lib/python3.7/site-packages/deepchem/models/callbacks.py in __call__(self, model, step)
     79     if model.tensorboard:
     80       for key in scores:
---> 81         model._log_value_to_tensorboard(tag=key, simple_value=scores[key])
     82     if model.wandb:
     83       import wandb

AttributeError: 'GraphConvModel' object has no attribute '_log_value_to_tensorboard'
```

### PR DESCRIPTION
**Pull request by peastman**
Fixes #2245.

### CODE REVIEW

**Comment by peastman** [comment]
The test failures are caused by an error in `test_weave_fit_simple_infinity_distance()`.  I don't think it's related to this change?

**Review by rbharath — APPROVED** [review]
Thanks for the fix! Feel free to merge when ready :)

**Comment by cjgalvin** [comment]
Thanks for putting in a fix on this issue so quickly. This merge will show up in the nightly build from tomorrow, right?

**Comment by peastman** [comment]
Right.

**Pull request merged**
