### PR TITLE
upgrading to pytorch 1.8.1

### PR DESCRIPTION
**Pull request by VIGNESHinZONE**
## Description
Upgrading to Pytorch 1.7.1

Fix https://github.com/deepchem/deepchem/issues/2517

### CODE REVIEW

**Comment by rbharath** [comment]
@VIGNESHinZONE Could you try swapping this to a direct pytorch 1.8.1 upgrade to see if that fixes the CUDA issue?

**Comment by VIGNESHinZONE** [comment]
@rbharath I understand what's causing the problem, can't seem to figure out to go about fixing it. 

1) `torch-cluster` is throwing a build error, which has a dependency on Pytorch. But Im not sure as to why PyTorch isn't being installed before torch-cluster.

**Comment by rbharath** [comment]
As a quick question, where are we using torch-cluster? It's not one of our dependencies is it?

**Comment by VIGNESHinZONE** [comment]
`torch-cluster` is a dependecy for `torch-geometric` (as per the [documentation](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#installation-via-binaries))

**Pull request closed without merging**
