### PR TITLE
Quantum machine example

### PR DESCRIPTION
**Pull request by joegomes**
This PR adds:
    - Quantum machine example and dataset
    - MAE evaluator (used in qmachine paper)

In the near-future, the description for each section of the example will be expanded.  Currently, this notebook performs a hyperparameter search to minimize MAE on the quantum machine dataset using random forest, kernal ridge regression, and single-task dnn models.

### CODE REVIEW

**Comment by hainm** [comment]
hi,

is there any way to avoid loading pickled files?

**Comment by joegomes** [comment]
@hainm I'm currently loading from the pickle to speed things up while testing the hyperparameter search.  In the next revision of this example I plan on using the CoulombMatrixEig featurizer to featurize directly from the .SDF file I created from their [data](http://quantum-machine.org/datasets/#qm7).  Is that what you mean by avoiding pickled files?

**Comment by hainm** [comment]
>  Is that what you mean by avoiding pickled files?

Hi, just for security reason (http://kevinlondon.com/2015/08/15/dangerous-python-functions-pt2.html)

**Comment by rbharath** [comment]
@joegomes LGTM! The numbers for the KRR look to match the qmachine paper now. Will go ahead and merge in now.

**Pull request merged**
