### PR TITLE
Fixed CI errors

### PR DESCRIPTION
**Pull request by peastman**
Fixes errors introduced in #2371.

### CODE REVIEW

**Comment by peastman** [comment]
It looks like numpy 1.20.0 added type annotations, and that caused lots of new errors to start getting reported.  This will take a while to fix...

**Comment by nd-02110114** [comment]
The Numpy 1.20 contains a lot of breaking changes. 
https://github.com/numpy/numpy/releases/tag/v1.20.0
The changes may cause test failures even if you fix mypy errors. It is better to set `numpy < 1.20` in `setup.py`.

**Comment by peastman** [comment]
That might be best.  Some of the problems it's reporting are genuine errors, so I'll try to fix those, but I won't do anything that involves numpy 1.20 specific type annotations.

**Comment by peastman** [comment]
In addition to the mypy errors with numpy 1.20, it appears we have a *lot* of tests that fail with TensorFlow 2.4.  This is turning into a steadily growing project...

**Comment by peastman** [comment]
@ncfrey any idea why we're getting this doctest failure on the Ubuntu Python 3.6 build (but not any of the others)?

```
______________ [doctest] deepchem.utils.vina_utils.prepare_inputs ______________
170   Examples
171   --------
172   >>> p, m = prepare_inputs('3cyx', 'CCC')
173   >>> p.GetNumAtoms()
174   1415
175   >>> m.GetNumAtoms()
176   11
177 
178   >>> p, m = prepare_inputs('3cyx', 'CCC', remove_heterogens=False)
179   >>> p.GetNumAtoms()
Expected:
    1720
Got:
    1721
```

When I run it locally, I get 1720.

**Comment by ncfrey** [comment]
> @ncfrey any idea why we're getting this doctest failure on the Ubuntu Python 3.6 build (but not any of the others)?

Hm, I run Ubuntu Python 3.6 locally and don't get that error. I'm not sure why it's happening, but I'll look into it.

**Comment by peastman** [comment]
All tests passed!  I'm not sure what happened with that doctest.  Perhaps it's stochastic and will fail a small fraction of the time?  Anyway, I think this is ready merge if the changes look ok.

**Comment by rbharath** [comment]
Oh wow! Awesome fixes here :). Will merge this in right away so we get the CI green

**Pull request merged**
