### PR TITLE
Reorganized models directory

### PR DESCRIPTION
**Pull request by peastman**
Now that a lot of the models aren't based on TensorGraph anymore, it doesn't make sense for them to be in the `tensorgraph` submodule anymore, so I reorganized them.

### CODE REVIEW

**Comment by rbharath** [comment]
Feel free to merge in once Travis is done running :)

**Comment by peastman** [comment]
Python 2.7 (but not 3.5) is getting lots of errors like the following.  I thought it might just be a temporary problem, but rerunning it didn't help.

```
======================================================================
ERROR: test_rotation (deepchem.trans.tests.test_transformers.TestTransformers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/deepchem/deepchem/deepchem/trans/tests/test_transformers.py", line 35, in setUp
    mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 260, in read_data_sets
    source_url + TRAIN_IMAGES)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 252, in maybe_download
    temp_file_name, _ = urlretrieve_with_retry(source_url)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 205, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 233, in urlretrieve_with_retry
    return urllib.request.urlretrieve(url, filename)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/httplib.py", line 1055, in endheaders
    self._send_output(message_body)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/httplib.py", line 1280, in connect
    server_hostname=server_hostname)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```

It looks related to https://github.com/tensorflow/tensorflow/issues/10779, but that's quite an old issue.  Any ideas?

**Comment by peastman** [comment]
And *now* a whole bunch of tests are failing with errors that look like this.

```
======================================================================
ERROR: test_blurring (deepchem.trans.tests.test_transformers.TestTransformers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/deepchem/deepchem/deepchem/trans/tests/test_transformers.py", line 36, in setUp
    mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
  File "/home/travis/anaconda/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/travis/anaconda/envs/deepchem/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 290, in read_data_sets
    train = DataSet(train_images, train_labels, **options)
  File "/home/travis/anaconda/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/travis/anaconda/envs/deepchem/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 161, in __init__
    images = numpy.multiply(images, 1.0 / 255.0)
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (55000, 784) and data type float32
```

I don't see how these could possibly be related to this PR.  This is getting very very frustrating!

**Comment by peastman** [comment]
I'm closing this since these changes have now been made elsewhere.

**Pull request closed without merging**
